import Link from 'next/link'
import { ArrowUpRight, Check } from 'lucide-react'
import { createMetadata } from '@/lib/seo'
import {
  MotionSection,
  MotionItem,
  MotionHero,
  MotionHeroItem,
} from '@/components/partnerships/MotionLayer'
import { TwoLayerSignature } from './TwoLayerSignature'
import { PilotCTA } from './PilotCTA'

/*
 * Private partnership proposal — FrankX → Van Ede & Partners.
 *
 * Static sibling under /partnerships. This static segment takes precedence over
 * the registry-driven [slug] route, and the slug is deliberately NOT added to
 * content/partnerships/index.ts — so the page never appears on the public hub
 * and is reachable only by direct link. noindex,nofollow is set below.
 *
 * Scope is fixed off-the-shelf formats at fixed fees only: two offers, one CTA,
 * one signature visual. Restraint is the design — do not add pricing tables,
 * FAQs, or extra sections.
 */

export const metadata = createMetadata({
  title: 'FrankX × Van Ede & Partners — Partnership Proposal',
  description:
    'A private proposal: proven, ready-to-book AI-guided workshops for Van Ede clients in transition, and AI fluency for Van Ede coaches. Human guidance, amplified by intelligence.',
  path: '/partnerships/van-ede',
  // Use the branded OG generated by ./opengraph-image.tsx. createMetadata always
  // sets openGraph.images, which would otherwise suppress the file-convention
  // auto-injection and fall back to the site default — so point at it explicitly.
  image: '/partnerships/van-ede/opengraph-image',
  noindex: true,
})

// Eyebrow used before every section heading — matches the live /partnerships surface.
function Eyebrow({ children }: { children: React.ReactNode }) {
  return (
    <p className="text-[11px] tracking-[0.25em] uppercase text-emerald-400/60 font-medium mb-4">
      {children}
    </p>
  )
}

const DISPLAY_FONT = 'var(--font-poppins, Poppins), Inter, sans-serif'

export default function VanEdeProposalPage() {
  return (
    <main>
      {/* ───────────────────────── Hero + signature ───────────────────────── */}
      <section
        aria-labelledby="hero-heading"
        className="relative overflow-hidden pt-28 pb-16 lg:pt-36 lg:pb-20"
      >
        <div
          aria-hidden
          className="absolute inset-0 bg-gradient-to-b from-emerald-500/[0.06] via-transparent to-transparent"
        />
        <div className="relative max-w-5xl mx-auto px-6 lg:px-8">
          <MotionHero>
            <MotionHeroItem delay={0}>
              <Eyebrow>Partnership proposal &middot; for Van Ede &amp; Partners</Eyebrow>
            </MotionHeroItem>
            <MotionHeroItem delay={0.1}>
              <h1
                id="hero-heading"
                className="text-4xl sm:text-5xl lg:text-6xl font-bold text-white leading-[1.05] mb-6 max-w-3xl"
                style={{ fontFamily: DISPLAY_FONT, letterSpacing: '-0.025em' }}
              >
                Human guidance, amplified by intelligence.
              </h1>
            </MotionHeroItem>
            <MotionHeroItem delay={0.2}>
              <p className="text-lg text-zinc-300 leading-[1.7] max-w-2xl mb-4">
                Van Ede gives work meaning &mdash; the coaches, the trust, the{' '}
                <span className="text-zinc-100">Sociaal Plan</span> mandates. FrankX
                adds the intelligence layer: AI-guided formats, already proven in
                the field. This page proposes one small, reversible first step.
              </p>
            </MotionHeroItem>
            <MotionHeroItem delay={0.3}>
              <p className="text-sm text-zinc-500 leading-relaxed max-w-2xl mb-12">
                Everything here is an existing format, delivered as-is, at a fixed
                fee. Nothing to build. Proven, ready, fast to book.
              </p>
            </MotionHeroItem>
            <MotionHeroItem delay={0.4}>
              <TwoLayerSignature />
            </MotionHeroItem>
          </MotionHero>
        </div>
      </section>

      {/* ───────────────────────── The two offers ───────────────────────── */}
      <MotionSection
        aria-labelledby="offers-heading"
        className="border-t border-white/5 py-20 lg:py-28"
      >
        <div className="max-w-5xl mx-auto px-6 lg:px-8">
          <MotionItem className="mb-12 max-w-2xl">
            <Eyebrow>What FrankX brings</Eyebrow>
            <h2
              id="offers-heading"
              className="text-2xl sm:text-3xl font-semibold text-white mb-3"
              style={{ letterSpacing: '-0.02em' }}
            >
              Two proven formats. Fixed fees. Ready to book.
            </h2>
            <p className="text-base text-zinc-300 leading-[1.7]">
              No custom software, no co-development. Two things Van Ede can put to
              work this quarter.
            </p>
          </MotionItem>

          <div className="grid grid-cols-1 lg:grid-cols-5 gap-5">
            {/* O1 — flagship */}
            <MotionItem className="lg:col-span-3">
              <article className="h-full rounded-3xl border border-emerald-500/25 p-8 lg:p-10 bg-white/[0.02]">
                <div className="flex items-center gap-3 mb-5">
                  <span className="inline-flex items-center px-2.5 py-1 rounded-full text-[11px] font-medium bg-emerald-500/15 text-emerald-300 border border-emerald-500/30 tracking-wide">
                    PROVEN FORMAT
                  </span>
                  <span className="text-[11px] tracking-[0.2em] uppercase text-emerald-400/60 font-medium">
                    For clients in transition
                  </span>
                </div>
                <h3
                  className="text-xl sm:text-2xl font-semibold text-white mb-3"
                  style={{ letterSpacing: '-0.015em' }}
                >
                  AI-Guided Direction Workshops
                </h3>
                <p className="text-base text-zinc-300 leading-[1.7] mb-6">
                  2.5 hours, live, human-led, AI-guided. For Van Ede clients in
                  transition. Delivered as-is from a format that already works
                  &mdash; which is why booking takes days, not months. Three
                  ready variants:
                </p>

                <ul className="space-y-4 mb-8">
                  {[
                    {
                      name: 'Direction in the AI Era',
                      desc: 'Ikigai and purpose, with AI as a mirror, not an oracle.',
                    },
                    {
                      name: 'AI-Powered Job Search',
                      desc: 'CV, LinkedIn and interview prep with modern tools, done right.',
                    },
                    {
                      name: 'Launch Lean with AI',
                      desc: 'For Leergang Ondernemerschap participants — one person, a real business, AI as the first team.',
                    },
                  ].map((v) => (
                    <li key={v.name} className="flex gap-3">
                      <Check className="w-4 h-4 mt-1 shrink-0 text-emerald-400" aria-hidden />
                      <span className="text-sm leading-relaxed">
                        <span className="text-white font-medium">{v.name}</span>
                        <span className="text-zinc-400"> &mdash; {v.desc}</span>
                      </span>
                    </li>
                  ))}
                </ul>

                {/* Card footer — the skimmer's takeaway */}
                <div className="border-t border-white/[0.08] pt-5">
                  <p className="text-sm text-zinc-300 leading-relaxed">
                    <span className="text-white font-medium">Fixed fee per cohort</span>
                    , billable against the training budgets nearly every Sociaal
                    Plan already carries.
                  </p>
                  <p className="mt-2 text-sm text-emerald-300/90 leading-relaxed">
                    New revenue from money already allocated.
                  </p>
                </div>
              </article>
            </MotionItem>

            {/* O2 — coach enablement */}
            <MotionItem className="lg:col-span-2">
              <article className="h-full rounded-3xl border border-white/[0.08] p-8 lg:p-10 bg-white/[0.02]">
                <div className="mb-5">
                  <span className="text-[11px] tracking-[0.2em] uppercase text-emerald-400/60 font-medium">
                    For the coaches
                  </span>
                </div>
                <h3
                  className="text-xl sm:text-2xl font-semibold text-white mb-3"
                  style={{ letterSpacing: '-0.015em' }}
                >
                  Coach Enablement &mdash; AI Fluency for Consultants
                </h3>
                <p className="text-base text-zinc-300 leading-[1.7] mb-6">
                  A half-day masterclass plus a ready-made toolkit for Van Ede
                  coaches and psychologists.
                </p>

                <ul className="space-y-4 mb-8">
                  {[
                    'Session prep and synthesis in minutes.',
                    'Client-safe AI use — privacy, boundaries, and what never to delegate.',
                    'Consistent quality across offices.',
                  ].map((point) => (
                    <li key={point} className="flex gap-3">
                      <Check className="w-4 h-4 mt-1 shrink-0 text-emerald-400" aria-hidden />
                      <span className="text-sm text-zinc-300 leading-relaxed">{point}</span>
                    </li>
                  ))}
                </ul>

                <div className="border-t border-white/[0.08] pt-5">
                  <p className="text-sm text-zinc-300 leading-relaxed">
                    <span className="text-white font-medium">Fixed fee per session.</span>
                  </p>
                  <p className="mt-2 text-sm text-emerald-300/90 leading-relaxed">
                    Every coach more productive, the brand visibly modern.
                  </p>
                </div>
              </article>
            </MotionItem>
          </div>
        </div>
      </MotionSection>

      {/* ───────────────────────── Why now ───────────────────────── */}
      <MotionSection
        aria-labelledby="why-heading"
        className="border-t border-white/5 py-20 lg:py-28"
      >
        <div className="max-w-5xl mx-auto px-6 lg:px-8">
          <MotionItem className="mb-12 max-w-2xl">
            <Eyebrow>Why now</Eyebrow>
            <h2
              id="why-heading"
              className="text-2xl sm:text-3xl font-semibold text-white mb-3"
              style={{ letterSpacing: '-0.02em' }}
            >
              The economics line up this year.
            </h2>
          </MotionItem>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
            {[
              {
                k: 'Budget already allocated',
                v: '€3,500+ per-employee training budgets already sit in nearly every Sociaal Plan, and today they flow to external providers. These workshops let Van Ede capture spend that is already committed.',
              },
              {
                k: 'Candidates expect it',
                v: 'People in transition now face an AI-shaped labor market. They expect the partner guiding them through it to be fluent in it.',
              },
              {
                k: 'The position is open',
                v: '"The AI-forward outplacement partner" is an unclaimed position in the Dutch market. It is there for whoever moves first.',
              },
            ].map((c) => (
              <MotionItem
                key={c.k}
                className="rounded-2xl bg-white/[0.025] border border-white/[0.08] p-6"
              >
                <p className="text-[11px] tracking-[0.2em] uppercase text-emerald-400/60 font-medium mb-3">
                  {c.k}
                </p>
                <p className="text-sm text-zinc-300 leading-[1.7]">{c.v}</p>
              </MotionItem>
            ))}
          </div>
        </div>
      </MotionSection>

      {/* ───────────────────────── Proof — both sides of the table ───────────────────────── */}
      <MotionSection
        aria-labelledby="proof-heading"
        className="border-t border-white/5 py-20 lg:py-28"
      >
        <div className="max-w-4xl mx-auto px-6 lg:px-8">
          <MotionItem>
            <Eyebrow>Why this proposal, from this person</Eyebrow>
            <h2 id="proof-heading" className="sr-only">
              Proof
            </h2>
            <blockquote
              className="text-xl sm:text-2xl lg:text-3xl text-white leading-[1.5] font-medium"
              style={{ letterSpacing: '-0.015em' }}
            >
              &ldquo;I have sat on both sides of this table. I am a Van Ede client
              in transition &mdash; and the architect who spent four years building
              AI systems for Europe&rsquo;s largest enterprises. I know exactly where
              intelligence belongs in this work &mdash; and where only a human coach
              will do.&rdquo;
            </blockquote>
          </MotionItem>

          <MotionItem className="mt-10 grid grid-cols-1 sm:grid-cols-2 gap-x-8 gap-y-3">
            {[
              '4+ years at Oracle EMEA AI Center of Excellence',
              'BMW, Volkswagen, KPN, Daimler Trucks, Roche',
              'Sold-out NLDigital workshop — 38 registrations, their record',
              'FrankX Operations BV, Amsterdam',
            ].map((cred) => (
              <div key={cred} className="flex gap-3">
                <span aria-hidden className="mt-2 w-1.5 h-1.5 shrink-0 rounded-full bg-emerald-400" />
                <p className="text-sm text-zinc-300 leading-relaxed">{cred}</p>
              </div>
            ))}
          </MotionItem>
          <MotionItem className="mt-6">
            <Link
              href="/workshops"
              className="inline-flex items-center gap-1.5 text-sm text-emerald-300 hover:text-emerald-200 font-medium focus:outline-none focus:ring-2 focus:ring-emerald-400/60 rounded"
            >
              See the workshops practice
              <ArrowUpRight className="w-3.5 h-3.5" aria-hidden />
            </Link>
          </MotionItem>
        </div>
      </MotionSection>

      {/* ───────────────────────── The pilot — the only CTA ───────────────────────── */}
      <MotionSection
        aria-labelledby="pilot-heading"
        className="border-t border-white/5 py-20 lg:py-28"
      >
        <div className="max-w-4xl mx-auto px-6 lg:px-8">
          <MotionItem
            className="relative rounded-3xl border border-emerald-500/25 p-8 sm:p-12 overflow-hidden"
            style={{
              background:
                'radial-gradient(ellipse at top right, rgba(6,182,212,0.04) 0%, transparent 55%), radial-gradient(ellipse at center, rgba(16,185,129,0.06) 0%, rgba(255,255,255,0.02) 40%, transparent 70%)',
            }}
          >
            <Eyebrow>The first step</Eyebrow>
            <h2
              id="pilot-heading"
              className="text-2xl sm:text-3xl font-semibold text-white mb-3"
              style={{ letterSpacing: '-0.02em' }}
            >
              One cohort. One measurement. One decision.
            </h2>
            <p className="text-base text-zinc-300 leading-[1.7] max-w-2xl mb-8">
              One 2.5-hour workshop for one outplacement cohort, with Van Ede
              coaches observing. Participant clarity scored before and after,
              same-day coach feedback, and a one-page outcome report within a week.
              Then Van Ede decides whether to make it a standing format.
            </p>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-8">
              {[
                { n: '1', t: 'Run', d: 'One cohort, coaches in the room.' },
                { n: '2', t: 'Measure', d: 'Clarity scored before and after; same-day feedback.' },
                { n: '3', t: 'Decide', d: 'One-page report within a week. Then choose.' },
              ].map((s) => (
                <div key={s.n} className="rounded-2xl bg-white/[0.03] border border-white/[0.08] p-5">
                  <span className="text-emerald-400 font-mono text-xs">{s.n}</span>
                  <p className="mt-1 text-white font-medium text-sm">{s.t}</p>
                  <p className="mt-1 text-sm text-zinc-400 leading-relaxed">{s.d}</p>
                </div>
              ))}
            </div>

            <p className="text-sm text-zinc-300 leading-[1.7] max-w-2xl mb-8 border-l-2 border-emerald-500/40 pl-4">
              <span className="text-white font-medium">Risk to Van Ede: one room, one afternoon.</span>{' '}
              No license, no commitment, no exclusivity. Because the format already
              exists, the first cohort can run within weeks.
            </p>

            <PilotCTA />
          </MotionItem>
        </div>
      </MotionSection>

      {/* ───────────────────────── Where this can go ───────────────────────── */}
      <MotionSection
        aria-labelledby="future-heading"
        className="border-t border-white/5 py-16 lg:py-20"
      >
        <div className="max-w-3xl mx-auto px-6 lg:px-8">
          <MotionItem>
            <Eyebrow>Where this can go</Eyebrow>
            <h2 id="future-heading" className="sr-only">
              Where this can go
            </h2>
            <p className="text-base text-zinc-300 leading-[1.7]">
              Once workshops run, natural extensions exist &mdash; AI-supported
              trajectories, joint propositions toward corporate clients. We&rsquo;ll
              explore those only if the workshops prove themselves first.
            </p>
          </MotionItem>
        </div>
      </MotionSection>

      {/* ───────────────────────── Close ───────────────────────── */}
      <MotionSection className="border-t border-white/5 py-20 lg:py-28">
        <div className="max-w-3xl mx-auto px-6 lg:px-8 text-center">
          <MotionItem>
            <h2
              className="text-2xl sm:text-3xl lg:text-4xl font-semibold text-white mb-8 leading-snug"
              style={{ fontFamily: DISPLAY_FONT, letterSpacing: '-0.02em' }}
            >
              Werk zin geven &mdash; at the scale this decade demands.
            </h2>
            <div className="flex justify-center mb-10">
              <PilotCTA />
            </div>
            <div className="flex flex-wrap items-center justify-center gap-x-6 gap-y-2 text-sm text-zinc-400">
              <a
                href="tel:+31627215026"
                className="hover:text-emerald-300 focus:outline-none focus:ring-2 focus:ring-emerald-400/60 rounded"
              >
                +31 6 27 21 50 26
              </a>
              <a
                href="https://frankx.ai"
                className="hover:text-emerald-300 focus:outline-none focus:ring-2 focus:ring-emerald-400/60 rounded"
              >
                frankx.ai
              </a>
              <Link
                href="/workshops"
                className="hover:text-emerald-300 focus:outline-none focus:ring-2 focus:ring-emerald-400/60 rounded"
              >
                frankx.ai/workshops
              </Link>
            </div>
          </MotionItem>
        </div>
      </MotionSection>

      {/* Private footer — confidentiality line */}
      <footer className="border-t border-white/5 py-10">
        <div className="max-w-3xl mx-auto px-6 lg:px-8 text-center">
          <p className="text-xs text-zinc-500">
            Prepared exclusively for Van Ede &amp; Partners &middot; please share
            internally as useful.
          </p>
        </div>
      </footer>
    </main>
  )
}
