import type { BookConfig } from '../types';

export const booksRegistry: BookConfig[] = [
  // ─── 1. Love & Poetry ───────────────────────────────────────────
  {
    slug: 'love-and-poetry',
    title: 'Love & Poetry',
    subtitle: 'Verses That Move the Soul',
    author: 'Frank Riemer',
    publishDate: '2026',
    description:
      'A curated collection of the world\'s most beautiful love poetry — Rumi, Rilke, Goethe, Gibran — woven with original verse. Spanning centuries, cultures, and languages.',
    keywords: ['love poetry', 'Rumi', 'Rilke', 'Goethe', 'poetry collection', 'romantic poetry'],
    coverImage: '/images/books/love-and-poetry-cover.png',
    theme: {
      id: 'love-and-poetry',
      name: 'Love & Poetry',
      primary: 'rose',
      accent: 'gold',
      bgDark: '#0a0a0f',
      headingFont: 'serif',
      bodyFont: 'serif',
    },
    status: 'published',
    categories: ['Poetry', 'Love', 'Literature'],
    contentDir: 'content/books/love-and-poetry',
    chapters: [
      {
        slug: 'chapter-01-rumi-speaks',
        title: 'Rumi Speaks',
        number: 1,
        readingTime: '8 min',
        description: 'The mystic poet of love — seven meditations on the heart.',
        published: true,
        type: 'poetry',
        epigraph: {
          text: 'Let yourself be silently drawn by the strange pull of what you really love.',
          author: 'Rumi',
        },
      },
      {
        slug: 'chapter-02-dichter-der-liebe',
        title: 'Dichter der Liebe',
        number: 2,
        readingTime: '10 min',
        description: 'German poets of love — Fried, Goethe, and Rilke in their native tongue.',
        published: true,
        type: 'poetry',
        epigraph: {
          text: 'Es ist was es ist, sagt die Liebe.',
          author: 'Erich Fried',
        },
      },
      {
        slug: 'chapter-03-nha-tho-tinh-yeu',
        title: 'Nha Tho Tinh Yeu',
        number: 3,
        readingTime: '8 min',
        description: 'Vietnamese love poetry — the language of water, lotus, and longing.',
        published: true,
        type: 'poetry',
      },
      {
        slug: 'chapter-04-wisdom-of-the-ages',
        title: 'Wisdom of the Ages',
        number: 4,
        readingTime: '10 min',
        description: 'Gibran, Coelho, Saint-Exupery, Thich Nhat Hanh — love as philosophy.',
        published: true,
        type: 'quotes',
      },
      {
        slug: 'chapter-05-a-poem-for-you',
        title: 'A Poem for You',
        number: 5,
        readingTime: '6 min',
        description: 'Original poetry — verses written from lived experience.',
        published: true,
        type: 'poetry',
      },
      {
        slug: 'chapter-06-nerudas-fire',
        title: 'Neruda\'s Fire',
        number: 6,
        readingTime: '10 min',
        description: 'Pablo Neruda — the poet of elemental passion and desire.',
        published: true,
        type: 'poetry',
        epigraph: {
          text: 'I want to do with you what spring does with the cherry trees.',
          author: 'Pablo Neruda',
        },
      },
      {
        slug: 'chapter-07-mary-olivers-instructions',
        title: 'Mary Oliver\'s Instructions',
        number: 7,
        readingTime: '10 min',
        description: 'Mary Oliver — attention, astonishment, and the poetry of the natural world.',
        published: true,
        type: 'poetry',
        epigraph: {
          text: 'Instructions for living a life: Pay attention. Be astonished. Tell about it.',
          author: 'Mary Oliver',
        },
      },
      {
        slug: 'chapter-08-hafiz-and-the-gift',
        title: 'Hafiz and the Gift',
        number: 8,
        readingTime: '10 min',
        description: 'Hafiz — the Persian poet of divine intoxication and radical joy.',
        published: true,
        type: 'poetry',
        epigraph: {
          text: 'I wish I could show you, when you are lonely or in darkness, the astonishing light of your own being.',
          author: 'Hafiz',
        },
      },
    ],
  },

  // ─── 2. Spartan Mindset ─────────────────────────────────────────
  {
    slug: 'spartan-mindset',
    title: 'Spartan Mindset',
    subtitle: 'The Discipline of One More',
    author: 'Frank Riemer',
    publishDate: '2026',
    description:
      'A manual for the relentless. Discipline, training, and the philosophy of pushing past limits. Every chapter is a rep you didn\'t think you had.',
    keywords: ['discipline', 'gym training', 'mental toughness', 'spartan', 'mindset', 'fitness philosophy'],
    coverImage: '/images/books/spartan-mindset-cover.png',
    theme: {
      id: 'spartan-mindset',
      name: 'Spartan Mindset',
      primary: 'red',
      accent: 'stone',
      bgDark: '#030712',
      headingFont: 'sans',
      bodyFont: 'sans',
    },
    status: 'published',
    categories: ['Self-Development', 'Fitness', 'Mindset'],
    contentDir: 'content/books/spartan-mindset',
    chapters: [
      {
        slug: 'chapter-01-the-spartan-code',
        title: 'The Spartan Code',
        number: 1,
        readingTime: '12 min',
        description: 'The rules that govern the relentless. Non-negotiable principles for an unbreakable life.',
        published: true,
        type: 'prose',
        epigraph: {
          text: 'Spartans do not ask how many are the enemy but where are they.',
          author: 'Plutarch',
        },
      },
      {
        slug: 'chapter-02-iron-discipline',
        title: 'Iron Discipline',
        number: 2,
        readingTime: '14 min',
        description: 'How to build a body and mind that does not negotiate with weakness.',
        published: true,
        type: 'prose',
      },
      {
        slug: 'chapter-03-one-more-rep',
        title: 'One More Rep',
        number: 3,
        readingTime: '10 min',
        description: 'The philosophy that separates the ordinary from the exceptional.',
        published: true,
        type: 'prose',
        epigraph: {
          text: 'The last three or four reps is what makes the muscle grow.',
          author: 'Arnold Schwarzenegger',
        },
      },
      {
        slug: 'chapter-04-the-forge',
        title: 'The Forge',
        number: 4,
        readingTime: '12 min',
        description: 'Transforming pain into power. The training that builds character.',
        published: true,
        type: 'prose',
      },
      {
        slug: 'chapter-05-mind-over-matter',
        title: 'Mind Over Matter',
        number: 5,
        readingTime: '11 min',
        description: 'When the body says stop, the mind says one more.',
        published: true,
        type: 'prose',
      },
      {
        slug: 'chapter-06-the-arena',
        title: 'The Arena',
        number: 6,
        readingTime: '10 min',
        description: 'Where warriors are made. The crucible of competition and growth.',
        published: true,
        type: 'prose',
      },
      {
        slug: 'chapter-07-fuel-and-recovery',
        title: 'Fuel and Recovery',
        number: 7,
        readingTime: '10 min',
        description: 'The weapons you build with. Nutrition, rest, and strategic recovery.',
        published: true,
        type: 'prose',
      },
      {
        slug: 'chapter-08-the-brotherhood',
        title: 'The Brotherhood',
        number: 8,
        readingTime: '10 min',
        description: 'The phalanx. The power of training alongside those who share your standards.',
        published: true,
        type: 'prose',
      },
      {
        slug: 'chapter-09-stoic-foundations',
        title: 'Stoic Foundations',
        number: 9,
        readingTime: '10 min',
        description: 'The philosophical bedrock. Stoic wisdom applied to modern discipline.',
        published: true,
        type: 'prose',
      },
      {
        slug: 'chapter-10-the-long-game',
        title: 'The Long Game',
        number: 10,
        readingTime: '10 min',
        description: 'The discipline of decades. Playing for a lifetime, not a season.',
        published: true,
        type: 'prose',
      },
    ],
  },

  // ─── 3. The Golden Age of Creators ──────────────────────────────
  {
    slug: 'golden-age',
    title: 'The Golden Age of Creators',
    subtitle: 'The Democratization of Creative Capability and Distribution',
    author: 'Frank Riemer',
    publishDate: '2026',
    description:
      'A transformative exploration of how the creator economy crossed $250 billion, how 45 million people now create professionally, and how the barriers to creative expression have evaporated.',
    keywords: ['creator economy', 'AI and creativity', 'golden age of intelligence', 'creative entrepreneurship'],
    coverImage: '/images/golden-age/hero-golden-age.png',
    theme: {
      id: 'golden-age',
      name: 'The Golden Age of Creators',
      primary: 'amber',
      accent: 'indigo',
      bgDark: '#0F172A',
      headingFont: 'serif',
      bodyFont: 'sans',
    },
    status: 'published',
    categories: ['Creator Economy', 'AI', 'Business'],
    contentDir: 'content/golden-age-book',
    chapters: [
      {
        slug: 'chapter-01-when-creation-calls',
        title: 'When Creation Calls',
        number: 1,
        readingTime: '18 min',
        description: 'The question beneath all questions: What am I here to create?',
        published: true,
        type: 'prose',
        image: '/images/golden-age/chapter-01-when-creation-calls.png',
      },
      {
        slug: 'chapter-02-the-orchestration-age',
        title: 'The Orchestration Age',
        number: 2,
        readingTime: '14 min',
        description: 'From using AI to conducting AI agents like an orchestra.',
        published: true,
        type: 'prose',
        image: '/images/golden-age/chapter-02-the-orchestration-age.png',
      },
      {
        slug: 'chapter-03-the-first-gesture',
        title: 'The First Gesture',
        number: 3,
        readingTime: '15 min',
        description: 'The genesis moment — when intent becomes creation and the first mark is made.',
        published: true,
        type: 'prose',
        image: '/images/golden-age/chapter-03-the-first-gesture.png',
      },
      {
        slug: 'chapter-04-the-tools-of-the-golden-age',
        title: 'The Tools of the Golden Age',
        number: 4,
        readingTime: '15 min',
        description: 'The tools that shape our thinking and unlock creative capability at scale.',
        published: true,
        type: 'prose',
      },
      {
        slug: 'chapter-05-building-your-golden-age',
        title: 'Building Your Golden Age',
        number: 5,
        readingTime: '15 min',
        description: 'An investment in knowledge pays the best interest. Your personal golden age starts here.',
        published: true,
        type: 'prose',
      },
    ],
  },

  // ─── 4. The Art of Self-Development ─────────────────────────────
  {
    slug: 'self-development',
    title: 'The Art of Self-Development',
    subtitle: 'Seven Pillars of a Complete Life',
    author: 'Frank Riemer',
    publishDate: '2026',
    description:
      'A systematic approach to building every dimension of your life — energy, mind, soul, craft, capital, circle, and legacy. Not theory. Routines that work.',
    keywords: ['self-development', 'personal growth', 'routines', 'habits', 'life design'],
    coverImage: '/images/books/self-development-cover.png',
    theme: {
      id: 'self-development',
      name: 'The Art of Self-Development',
      primary: 'emerald',
      accent: 'cyan',
      bgDark: '#030f0a',
      headingFont: 'sans',
      bodyFont: 'sans',
    },
    status: 'published',
    categories: ['Self-Development', 'Habits', 'Lifestyle'],
    contentDir: 'content/books/self-development',
    chapters: [
      { slug: 'chapter-01-energy', title: 'Energy', number: 1, readingTime: '12 min', description: 'Master your physical and vital energy through breathwork, nutrition, and movement.', published: true, type: 'prose' },
      { slug: 'chapter-02-mind', title: 'Mind', number: 2, readingTime: '14 min', description: 'Develop mental clarity, cognitive edge, and psychological resilience.', published: true, type: 'prose' },
      { slug: 'chapter-03-soul', title: 'Soul', number: 3, readingTime: '11 min', description: 'Connect with your deeper purpose and spiritual essence.', published: true, type: 'prose' },
      { slug: 'chapter-04-craft', title: 'Craft', number: 4, readingTime: '13 min', description: 'Sharpen your skills, build mastery, and create work that matters.', published: true, type: 'prose' },
      { slug: 'chapter-05-capital', title: 'Capital', number: 5, readingTime: '12 min', description: 'Build financial intelligence and create multiple income streams.', published: true, type: 'prose' },
      { slug: 'chapter-06-circle', title: 'Circle', number: 6, readingTime: '10 min', description: 'Curate your relationships and build a network of excellence.', published: true, type: 'prose' },
      { slug: 'chapter-07-legacy', title: 'Legacy', number: 7, readingTime: '11 min', description: 'Design a life that outlasts you. Build something that endures.', published: true, type: 'prose' },
      { slug: 'chapter-08-rituals', title: 'Rituals', number: 8, readingTime: '10 min', description: 'We are what we repeatedly do. The daily rituals that compound into excellence.', published: true, type: 'prose' },
      { slug: 'chapter-09-environment', title: 'Environment', number: 9, readingTime: '10 min', description: 'We shape our buildings, and afterwards our buildings shape us. Design your surroundings.', published: true, type: 'prose' },
      { slug: 'chapter-10-integration', title: 'Integration', number: 10, readingTime: '10 min', description: 'Build a new model that makes the existing model obsolete. Bringing all pillars together.', published: true, type: 'prose' },
    ],
  },

  // ─── 5. Imagination ─────────────────────────────────────────────
  {
    slug: 'imagination',
    title: 'Imagination',
    subtitle: 'Unlocking the Power of the Mind',
    author: 'Frank Riemer',
    publishDate: '2026',
    description:
      'Your imagination is the most powerful technology you possess. This book teaches you how to wield it — creative visualization, mental models, and the architecture of thought.',
    keywords: ['imagination', 'creative visualization', 'mental models', 'cognitive expansion', 'mind power'],
    coverImage: '/images/books/imagination-cover.png',
    theme: {
      id: 'imagination',
      name: 'Imagination',
      primary: 'violet',
      accent: 'cyan',
      bgDark: '#0a0a12',
      headingFont: 'serif',
      bodyFont: 'sans',
    },
    status: 'published',
    categories: ['Mind', 'Creativity', 'Psychology'],
    contentDir: 'content/books/imagination',
    chapters: [
      { slug: 'chapter-01-the-inner-theater', title: 'The Inner Theater', number: 1, readingTime: '12 min', description: 'The stage inside your mind where all creation begins.', published: true, type: 'prose' },
      { slug: 'chapter-02-creative-visualization', title: 'Creative Visualization', number: 2, readingTime: '14 min', description: 'The science and art of seeing what doesn\'t yet exist.', published: true, type: 'prose' },
      { slug: 'chapter-03-mental-models', title: 'Mental Models', number: 3, readingTime: '15 min', description: 'The frameworks that shape how innovators think.', published: true, type: 'prose' },
      { slug: 'chapter-04-the-architects-eye', title: 'The Architect\'s Eye', number: 4, readingTime: '12 min', description: 'Training yourself to see structure in chaos and possibility in constraint.', published: true, type: 'prose' },
      { slug: 'chapter-05-beyond-the-visible', title: 'Beyond the Visible', number: 5, readingTime: '10 min', description: 'When imagination becomes your operating system.', published: true, type: 'prose' },
      { slug: 'chapter-06-the-inventors-method', title: 'The Inventor\'s Method', number: 6, readingTime: '10 min', description: 'Finding 10,000 ways that work. The iterative power of imaginative experimentation.', published: true, type: 'prose' },
      { slug: 'chapter-07-collective-imagination', title: 'Collective Imagination', number: 7, readingTime: '10 min', description: 'When a small group of committed minds imagines together, worlds change.', published: true, type: 'prose' },
      { slug: 'chapter-08-the-imagination-economy', title: 'The Imagination Economy', number: 8, readingTime: '10 min', description: 'The best way to predict the future is to invent it. Imagination as economic force.', published: true, type: 'prose' },
    ],
  },

  // ─── 6. Manifestation ───────────────────────────────────────────
  {
    slug: 'manifestation',
    title: 'Manifestation',
    subtitle: 'The Architecture of Reality',
    author: 'Frank Riemer',
    publishDate: '2026',
    description:
      'Not wishful thinking. Not magic. The grounded, psychological, and strategic approach to turning thought into reality — updated for the AI age.',
    keywords: ['manifestation', 'law of attraction', 'psychology of intention', 'goal achievement', 'mental architecture'],
    coverImage: '/images/books/manifestation-cover.png',
    theme: {
      id: 'manifestation',
      name: 'Manifestation',
      primary: 'gold',
      accent: 'purple',
      bgDark: '#0f0a05',
      headingFont: 'serif',
      bodyFont: 'sans',
    },
    status: 'published',
    categories: ['Mindset', 'Psychology', 'Self-Development'],
    contentDir: 'content/books/manifestation',
    chapters: [
      { slug: 'chapter-01-the-architecture-of-reality', title: 'The Architecture of Reality', number: 1, readingTime: '14 min', description: 'Reality is not fixed. It is constructed — and you are the architect.', published: true, type: 'prose' },
      { slug: 'chapter-02-thought-as-blueprint', title: 'Thought as Blueprint', number: 2, readingTime: '12 min', description: 'How thought patterns become life patterns.', published: true, type: 'prose' },
      { slug: 'chapter-03-the-frequency-principle', title: 'The Frequency Principle', number: 3, readingTime: '13 min', description: 'Aligning your energy with what you want to attract.', published: true, type: 'prose' },
      { slug: 'chapter-04-aligned-action', title: 'Aligned Action', number: 4, readingTime: '11 min', description: 'Manifestation without action is daydreaming. Action without alignment is hustle.', published: true, type: 'prose' },
      { slug: 'chapter-05-the-evidence-journal', title: 'The Evidence Journal', number: 5, readingTime: '10 min', description: 'Tracking proof that the universe is responding.', published: true, type: 'exercises' },
      { slug: 'chapter-06-the-science-of-belief', title: 'The Science of Belief', number: 6, readingTime: '10 min', description: 'Whether you think you can or you think you can\'t, you\'re right. The neuroscience of conviction.', published: true, type: 'prose' },
      { slug: 'chapter-07-environmental-architecture', title: 'Environmental Architecture', number: 7, readingTime: '10 min', description: 'You fall to the level of your systems. Designing environments that manifest your goals.', published: true, type: 'prose' },
      { slug: 'chapter-08-the-compound-life', title: 'The Compound Life', number: 8, readingTime: '10 min', description: 'The first rule of compounding: never interrupt it unnecessarily. Long-term manifestation.', published: true, type: 'prose' },
    ],
  },

  // ─── 7. The Architect's Playbook ────────────────────────────────
  {
    slug: 'architects-playbook',
    title: 'The Architect\'s Playbook',
    subtitle: 'Enterprise AI Systems Design',
    author: 'Frank Riemer',
    publishDate: '2026',
    description:
      'The definitive playbook for designing enterprise AI systems — from architecture patterns to production deployment. Built from real-world experience at Oracle EMEA AI Center of Excellence.',
    keywords: ['AI architecture', 'enterprise AI', 'system design', 'AI playbook', 'Oracle AI'],
    coverImage: '/images/books/architects-playbook-cover-v1.png',
    theme: {
      id: 'architects-playbook',
      name: 'The Architect\'s Playbook',
      primary: 'emerald',
      accent: 'cyan',
      bgDark: '#030f0a',
      headingFont: 'sans',
      bodyFont: 'sans',
    },
    status: 'published',
    categories: ['AI', 'Architecture', 'Enterprise'],
    contentDir: 'content/books/architects-playbook',
    chapters: [],
  },

  // ─── 8. VIBE ────────────────────────────────────────────────────
  {
    slug: 'vibe',
    title: 'VIBE',
    subtitle: 'The Art of Vibe-Driven Creation',
    author: 'Frank Riemer',
    publishDate: '2026',
    description:
      'VIBE coding, VIBE creating, VIBE living. How to channel creative energy into shipped products using AI as your co-pilot.',
    keywords: ['vibe coding', 'AI creation', 'creative flow', 'vibe-driven development'],
    coverImage: '/images/books/vibe-cover.png',
    theme: {
      id: 'vibe',
      name: 'VIBE',
      primary: 'blue',
      accent: 'violet',
      bgDark: '#0a0a1a',
      headingFont: 'sans',
      bodyFont: 'sans',
    },
    status: 'published',
    categories: ['AI', 'Creator Economy', 'Development'],
    contentDir: 'content/books/vibe',
    chapters: [],
  },

  // ─── 9. Agentic Builder ─────────────────────────────────────────
  {
    slug: 'agentic-builder',
    title: 'Agentic Builder',
    subtitle: 'Building with AI Agents',
    author: 'Frank Riemer',
    publishDate: '2026',
    description:
      'The practical guide to building with AI agents — from single-agent tools to multi-agent orchestration systems. Patterns, pitfalls, and production-ready architectures.',
    keywords: ['AI agents', 'agentic AI', 'multi-agent systems', 'agent orchestration', 'AI builder'],
    coverImage: '/images/books/agentic-builder-cover.png',
    theme: {
      id: 'agentic-builder',
      name: 'Agentic Builder',
      primary: 'emerald',
      accent: 'cyan',
      bgDark: '#030f0a',
      headingFont: 'sans',
      bodyFont: 'sans',
    },
    status: 'published',
    categories: ['AI', 'Development', 'Architecture'],
    contentDir: 'content/books/agentic-builder',
    chapters: [],
  },

  // ─── 10. GenCreator ─────────────────────────────────────────────
  {
    slug: 'gencreator',
    title: 'GenCreator',
    subtitle: 'The AI-Native Creator Operating System',
    author: 'Frank Riemer',
    publishDate: '2026',
    description:
      'The creator-specific AI Center of Excellence. How to build your personal creative engine using AI tools, workflows, and frameworks that compound over time.',
    keywords: ['GenCreator', 'AI creator', 'creator operating system', 'AI content creation'],
    coverImage: '/images/books/gencreator-cover.png',
    theme: {
      id: 'gencreator',
      name: 'GenCreator',
      primary: 'amber',
      accent: 'indigo',
      bgDark: '#0F172A',
      headingFont: 'sans',
      bodyFont: 'sans',
    },
    status: 'published',
    categories: ['Creator Economy', 'AI', 'Productivity'],
    contentDir: 'content/books/gencreator',
    chapters: [],
  },

  // ─── 11. Vibe OS ────────────────────────────────────────────────
  {
    slug: 'vibe-os',
    title: 'Vibe OS',
    subtitle: 'Your Personal Operating System for the AI Age',
    author: 'Frank Riemer',
    publishDate: '2026',
    description:
      'The operating system for living and creating in the AI age. Systems, routines, and frameworks for channeling creative energy into consistent output.',
    keywords: ['Vibe OS', 'personal operating system', 'AI productivity', 'creative systems'],
    coverImage: '/images/books/vibe-os-cover.png',
    theme: {
      id: 'vibe-os',
      name: 'Vibe OS',
      primary: 'green',
      accent: 'cyan',
      bgDark: '#030f0a',
      headingFont: 'sans',
      bodyFont: 'sans',
    },
    status: 'published',
    categories: ['Productivity', 'AI', 'Systems'],
    contentDir: 'content/books/vibe-os',
    chapters: [],
  },

  // ─── 12. Decentralized Creator ──────────────────────────────────
  {
    slug: 'decentralized-creator',
    title: 'Decentralized Creator',
    subtitle: 'Own Your Creative Stack',
    author: 'Frank Riemer',
    publishDate: '2026',
    description:
      'How to build a creative empire you fully own — from self-hosted infrastructure to sovereign distribution channels. Independence through technology.',
    keywords: ['decentralized creator', 'self-hosted', 'creator independence', 'Web3 creator'],
    coverImage: '/images/books/decentralized-creator-cover.png',
    theme: {
      id: 'decentralized-creator',
      name: 'Decentralized Creator',
      primary: 'cyan',
      accent: 'violet',
      bgDark: '#0a0a1a',
      headingFont: 'sans',
      bodyFont: 'sans',
    },
    status: 'published',
    categories: ['Creator Economy', 'Technology', 'Independence'],
    contentDir: 'content/books/decentralized-creator',
    chapters: [],
  },

  // ─── 13. MCP Builder's Guide ────────────────────────────────────
  {
    slug: 'mcp-builders-guide',
    title: 'MCP Builder\'s Guide',
    subtitle: 'Model Context Protocol from Zero to Production',
    author: 'Frank Riemer',
    publishDate: '2026',
    description:
      'The comprehensive guide to building with the Model Context Protocol — from understanding the spec to shipping production MCP servers and clients.',
    keywords: ['MCP', 'Model Context Protocol', 'AI tools', 'MCP server', 'AI integration'],
    coverImage: '/images/books/mcp-builders-guide-cover.png',
    theme: {
      id: 'mcp-builders-guide',
      name: 'MCP Builder\'s Guide',
      primary: 'emerald',
      accent: 'cyan',
      bgDark: '#030f0a',
      headingFont: 'sans',
      bodyFont: 'sans',
    },
    status: 'published',
    categories: ['AI', 'Development', 'MCP'],
    contentDir: 'content/books/mcp-builders-guide',
    chapters: [],
  },

  // ─── 14. Personal AI CoE ───────────────────────────────────────
  {
    slug: 'personal-ai-coe',
    title: 'Personal AI CoE',
    subtitle: 'Enterprise AI Frameworks for Everyone',
    author: 'Frank Riemer',
    publishDate: '2026',
    description:
      'The same 6-pillar AI Center of Excellence architecture Frank builds for Fortune 500 companies at Oracle — translated for individuals, creators, and families at 1/5000th the cost.',
    keywords: ['AI CoE', 'personal AI', 'AI center of excellence', 'AI strategy', 'enterprise AI for individuals'],
    coverImage: '/images/books/personal-ai-coe-cover.png',
    theme: {
      id: 'personal-ai-coe',
      name: 'Personal AI CoE',
      primary: 'violet',
      accent: 'amber',
      bgDark: '#0a0a12',
      headingFont: 'sans',
      bodyFont: 'sans',
    },
    status: 'published',
    categories: ['AI', 'Strategy', 'Self-Development'],
    contentDir: 'content/books/personal-ai-coe',
    chapters: [],
  },

  // ─── 15. The Great Transition ───────────────────────────────────
  {
    slug: 'great-transition',
    title: 'The Great Transition',
    subtitle: 'From Employee to Builder',
    author: 'Frank Riemer',
    publishDate: '2026',
    description:
      'Something is happening. The old deal is breaking. This book maps the transition from employment to ownership — and gives you the first 90 days of your builder journey.',
    keywords: ['great transition', 'creator economy', 'entrepreneurship', 'career transition', 'building in public'],
    coverImage: '/images/books/great-transition-cover.png',
    theme: {
      id: 'great-transition',
      name: 'The Great Transition',
      primary: 'amber',
      accent: 'indigo',
      bgDark: '#0F172A',
      headingFont: 'serif',
      bodyFont: 'sans',
    },
    status: 'published',
    categories: ['Business', 'Creator Economy', 'Career'],
    contentDir: 'content/books/great-transition',
    chapters: [
      { slug: 'chapter-01-something-is-happening', title: 'Something Is Happening', number: 1, readingTime: '10 min', description: 'The shift everyone feels but few can name. The world is changing beneath our feet.', published: true, type: 'prose' },
      { slug: 'chapter-02-the-old-deal', title: 'The Old Deal', number: 2, readingTime: '10 min', description: 'The employment contract that no longer holds. Understanding what we are leaving behind.', published: true, type: 'prose' },
      { slug: 'chapter-03-the-leverage-shift', title: 'The Leverage Shift', number: 3, readingTime: '10 min', description: 'How technology shifted leverage from institutions to individuals.', published: true, type: 'prose' },
      { slug: 'chapter-04-the-builders-already-building', title: 'The Builders Already Building', number: 4, readingTime: '10 min', description: 'Profiles of those who made the transition. What they learned, what they built.', published: true, type: 'prose' },
      { slug: 'chapter-05-what-you-own', title: 'What You Own', number: 5, readingTime: '10 min', description: 'Taking inventory of your assets, skills, and creative capital.', published: true, type: 'prose' },
      { slug: 'chapter-06-the-niche-imperative', title: 'The Niche Imperative', number: 6, readingTime: '10 min', description: 'Why niching down is the most important strategic decision you will make.', published: true, type: 'prose' },
      { slug: 'chapter-07-building-in-public', title: 'Building in Public', number: 7, readingTime: '10 min', description: 'The strategy of transparency. How sharing your journey accelerates your growth.', published: true, type: 'prose' },
      { slug: 'chapter-08-the-first-90-days', title: 'The First 90 Days', number: 8, readingTime: '10 min', description: 'Your actionable roadmap for the first three months of building.', published: true, type: 'prose' },
    ],
  },

  // ─── 16. Fire Horse Poems ──────────────────────────────────────
  {
    slug: 'fire-horse-poems',
    title: 'Fire Horse Poems',
    subtitle: 'Verses from the Year of the Fire Horse',
    author: 'Frank Riemer',
    publishDate: '2026',
    description:
      'Poetry born from fire — the energy of the Fire Horse year channeled into verse. For builders, dreamers, and those who run toward the flame.',
    keywords: ['poetry', 'fire horse', 'Chinese zodiac', 'original poetry', 'creative writing'],
    coverImage: '/images/books/fire-horse-poems-cover.png',
    theme: {
      id: 'fire-horse-poems',
      name: 'Fire Horse Poems',
      primary: 'red',
      accent: 'amber',
      bgDark: '#0f0505',
      headingFont: 'serif',
      bodyFont: 'serif',
    },
    status: 'published',
    categories: ['Poetry', 'Creative Writing'],
    contentDir: 'content/books/fire-horse-poems',
    chapters: [
      { slug: 'chapter-01-the-fire-horse', title: 'The Fire Horse', number: 1, readingTime: '10 min', description: 'The opening blaze. The spirit of the Fire Horse unleashed.', published: true, type: 'poetry' },
      { slug: 'chapter-02-to-the-builders', title: 'To the Builders', number: 2, readingTime: '10 min', description: 'Verses for those who build with their hands and their minds.', published: true, type: 'poetry' },
      { slug: 'chapter-03-sixty-year-flame', title: 'Sixty-Year Flame', number: 3, readingTime: '10 min', description: 'The sixty-year cycle of the Fire Horse — rare, fierce, untameable.', published: true, type: 'poetry' },
      { slug: 'chapter-04-ring-of-fire', title: 'Ring of Fire', number: 4, readingTime: '10 min', description: 'Walking through fire and coming out forged. The ring that transforms.', published: true, type: 'poetry' },
      { slug: 'chapter-05-the-table-the-horse-the-morning', title: 'The Table, the Horse, the Morning', number: 5, readingTime: '10 min', description: 'Still life in motion. The quiet power of morning ritual.', published: true, type: 'poetry' },
    ],
  },

  // ─── 17. Hoffnung (German) ─────────────────────────────────────
  {
    slug: 'hoffnung-de',
    title: 'Hoffnung',
    subtitle: 'Gedichte und Texte der Zuversicht',
    author: 'Frank Riemer',
    publishDate: '2026',
    description:
      'Ein Buch der Hoffnung — Gedichte, heilige Texte und Briefe an die Lebenden. Für alle, die Licht suchen in dunklen Zeiten.',
    keywords: ['Hoffnung', 'Gedichte', 'Zuversicht', 'deutsche Poesie', 'Trost'],
    coverImage: '/images/books/hoffnung-cover.png',
    theme: {
      id: 'hoffnung-de',
      name: 'Hoffnung',
      primary: 'amber',
      accent: 'sky',
      bgDark: '#0F172A',
      headingFont: 'serif',
      bodyFont: 'serif',
    },
    status: 'published',
    categories: ['Poetry', 'German', 'Hope'],
    contentDir: 'content/books/hoffnung-de',
    language: 'de',
    variantGroup: 'hoffnung',
    alternateSlug: 'hoffnung',
    chapters: [
      { slug: 'chapter-01-the-first-light', title: 'Das erste Licht', number: 1, readingTime: '10 min', description: 'Das erste Licht bricht durch. Der Beginn der Hoffnung.', published: true, type: 'poetry' },
      { slug: 'chapter-02-dichter-der-hoffnung', title: 'Dichter der Hoffnung', number: 2, readingTime: '10 min', description: 'Die Dichter, die uns Hoffnung schenkten — von Rilke bis Hesse.', published: true, type: 'poetry' },
      { slug: 'chapter-03-sacred-texts', title: 'Heilige Texte', number: 3, readingTime: '10 min', description: 'Heilige Worte aus allen Traditionen — Trost, der die Jahrhunderte überdauert.', published: true, type: 'quotes' },
      { slug: 'chapter-04-the-music-of-healing', title: 'Die Musik der Heilung', number: 4, readingTime: '10 min', description: 'Wenn Worte nicht reichen, spricht die Musik.', published: true, type: 'prose' },
      { slug: 'chapter-05-letters-to-the-living', title: 'Briefe an die Lebenden', number: 5, readingTime: '10 min', description: 'Briefe an alle, die noch da sind. Worte der Zuversicht.', published: true, type: 'prose' },
      { slug: 'chapter-06-for-the-one-who-is-leaving', title: 'Für den, der geht', number: 6, readingTime: '10 min', description: 'Für alle, die Abschied nehmen müssen. Begleitung auf dem letzten Weg.', published: true, type: 'poetry' },
      { slug: 'chapter-07-kleine-lichter', title: 'Kleine Lichter', number: 7, readingTime: '10 min', description: 'Die kleinen Lichter, die den Weg weisen, wenn alles dunkel ist.', published: true, type: 'poetry' },
      { slug: 'chapter-08-dawn', title: 'Morgenrot', number: 8, readingTime: '10 min', description: 'Das Morgenrot. Ein neuer Tag beginnt. Hoffnung triumphiert.', published: true, type: 'poetry' },
    ],
  },

  // ─── 18. Hoffnung (English) ────────────────────────────────────
  {
    slug: 'hoffnung',
    title: 'Hope',
    subtitle: 'Poems and Texts of Courage',
    author: 'Frank Riemer',
    publishDate: '2026',
    description:
      'A book of hope — poems, sacred texts, and letters to the living. For all who seek light in dark times.',
    keywords: ['hope', 'poetry', 'courage', 'healing poetry', 'comfort'],
    coverImage: '/images/books/hoffnung-cover.png',
    theme: {
      id: 'hoffnung',
      name: 'Hope',
      primary: 'amber',
      accent: 'sky',
      bgDark: '#0F172A',
      headingFont: 'serif',
      bodyFont: 'serif',
    },
    status: 'published',
    categories: ['Poetry', 'Hope', 'Healing'],
    contentDir: 'content/books/hoffnung',
    language: 'en',
    variantGroup: 'hoffnung',
    alternateSlug: 'hoffnung-de',
    chapters: [],
  },

  // ─── 19. Arcanea Chronicles ─────────────────────────────────────
  {
    slug: 'arcanea-chronicles',
    title: 'Arcanea Chronicles',
    subtitle: 'Tales of the Ten Guardians',
    author: 'Frank Riemer',
    publishDate: '2026',
    description:
      'The personal chronicles of Arcanea\'s ten guardian archetypes — their trials, doubts, and transcendence. Each chapter follows a different guardian through their defining moment.',
    keywords: ['Arcanea', 'fantasy', 'chronicles', 'guardians', 'worldbuilding'],
    coverImage: '/images/books/arcanea-chronicles-cover.png',
    theme: {
      id: 'arcanea-chronicles',
      name: 'Arcanea Chronicles',
      primary: 'amber',
      accent: 'gold',
      bgDark: '#0f0a05',
      headingFont: 'serif',
      bodyFont: 'serif',
    },
    status: 'published',
    categories: ['Fantasy', 'Worldbuilding', 'Arcanea'],
    contentDir: 'content/books/arcanea-chronicles',
    chapters: [
      { slug: 'chapter-01-lyssandrias-trembling', title: 'Lyssandria\'s Trembling', number: 1, readingTime: '10 min', description: 'Chronicle I — The first guardian faces the trembling of creation.', published: true, type: 'prose' },
      { slug: 'chapter-02-leylas-freezing', title: 'Leyla\'s Freezing', number: 2, readingTime: '10 min', description: 'Chronicle II — Leyla confronts the paralysis of indecision.', published: true, type: 'prose' },
      { slug: 'chapter-03-draconias-doubt', title: 'Draconia\'s Doubt', number: 3, readingTime: '10 min', description: 'Chronicle III — The dragon guardian wrestles with doubt.', published: true, type: 'prose' },
      { slug: 'chapter-04-maylinns-hardening', title: 'Maylinn\'s Hardening', number: 4, readingTime: '10 min', description: 'Chronicle IV — Maylinn\'s resolve hardens into purpose.', published: true, type: 'prose' },
      { slug: 'chapter-05-aleras-silence', title: 'Alera\'s Silence', number: 5, readingTime: '10 min', description: 'Chronicle V — Alera discovers power in silence.', published: true, type: 'prose' },
      { slug: 'chapter-06-lyrias-overwhelm', title: 'Lyria\'s Overwhelm', number: 6, readingTime: '10 min', description: 'Chronicle VI — Lyria navigates the overwhelm of infinite possibility.', published: true, type: 'prose' },
      { slug: 'chapter-07-aiyamis-pride', title: 'Aiyami\'s Pride', number: 7, readingTime: '10 min', description: 'Chronicle VII — Aiyami confronts the cost of pride.', published: true, type: 'prose' },
      { slug: 'chapter-08-elaras-instability', title: 'Elara\'s Instability', number: 8, readingTime: '10 min', description: 'Chronicle VIII — Elara balances on the edge of instability.', published: true, type: 'prose' },
      { slug: 'chapter-09-ino-and-kyuros-division', title: 'Ino and Kyuro\'s Division', number: 9, readingTime: '10 min', description: 'Chronicle IX — Two guardians divided must find unity.', published: true, type: 'prose' },
      { slug: 'chapter-10-shinkamis-waiting', title: 'Shinkami\'s Waiting', number: 10, readingTime: '10 min', description: 'Chronicle X — The final guardian learns the art of patient waiting.', published: true, type: 'prose' },
    ],
  },

  // ─── 20. Arcanea Legends ────────────────────────────────────────
  {
    slug: 'arcanea-legends',
    title: 'Arcanea Legends',
    subtitle: 'Myths of the First Dawn',
    author: 'Frank Riemer',
    publishDate: '2026',
    description:
      'The founding myths of Arcanea — from the First Dawn to the Ultraworld. The legends that shaped a civilization and its ten guardians.',
    keywords: ['Arcanea', 'legends', 'mythology', 'fantasy worldbuilding', 'guardians'],
    coverImage: '/images/books/arcanea-legends-cover.png',
    theme: {
      id: 'arcanea-legends',
      name: 'Arcanea Legends',
      primary: 'amber',
      accent: 'gold',
      bgDark: '#0f0a05',
      headingFont: 'serif',
      bodyFont: 'serif',
    },
    status: 'published',
    categories: ['Fantasy', 'Mythology', 'Arcanea'],
    contentDir: 'content/books/arcanea-legends',
    chapters: [
      { slug: 'chapter-01-the-first-dawn', title: 'The First Dawn', number: 1, readingTime: '10 min', description: 'The beginning of all things. When light first touched Arcanea.', published: true, type: 'prose' },
      { slug: 'chapter-02-the-ten-guardians', title: 'The Ten Guardians', number: 2, readingTime: '10 min', description: 'The ten archetypes who guard the fabric of creation.', published: true, type: 'prose' },
      { slug: 'chapter-03-the-great-darkness', title: 'The Great Darkness', number: 3, readingTime: '10 min', description: 'When shadow consumed the world and the guardians were tested.', published: true, type: 'prose' },
      { slug: 'chapter-04-the-lost-academy', title: 'The Lost Academy', number: 4, readingTime: '10 min', description: 'The forgotten school where creators once learned to shape reality.', published: true, type: 'prose' },
      { slug: 'chapter-05-tales-of-the-guardians', title: 'Tales of the Ten Guardians', number: 5, readingTime: '10 min', description: 'Individual tales of each guardian — their gifts, their burdens, their legacy.', published: true, type: 'prose' },
      { slug: 'chapter-06-the-weavers-knot', title: 'The Weaver\'s Knot', number: 6, readingTime: '10 min', description: 'The intricate pattern that binds all creation together.', published: true, type: 'prose' },
      { slug: 'chapter-07-the-ultraworld', title: 'The Ultraworld', number: 7, readingTime: '10 min', description: 'Beyond the known — the realm where imagination becomes substance.', published: true, type: 'prose' },
    ],
  },

  // ─── 21. Arcanea Bestiary ───────────────────────────────────────
  {
    slug: 'arcanea-bestiary',
    title: 'Arcanea Bestiary',
    subtitle: 'Creatures of Creation',
    author: 'Frank Riemer',
    publishDate: '2026',
    description:
      'A field guide to the creatures of Arcanea — from the gentle beings of beginning to the terrible creatures of darkness and the luminous beings of light.',
    keywords: ['Arcanea', 'bestiary', 'creatures', 'fantasy', 'field guide'],
    coverImage: '/images/books/arcanea-bestiary-cover.png',
    theme: {
      id: 'arcanea-bestiary',
      name: 'Arcanea Bestiary',
      primary: 'amber',
      accent: 'gold',
      bgDark: '#0f0a05',
      headingFont: 'serif',
      bodyFont: 'serif',
    },
    status: 'published',
    categories: ['Fantasy', 'Worldbuilding', 'Arcanea'],
    contentDir: 'content/books/arcanea-bestiary',
    chapters: [
      { slug: 'chapter-01-creatures-of-beginning', title: 'Creatures of Beginning', number: 1, readingTime: '10 min', description: 'The first beings — gentle, curious, born from the raw energy of creation.', published: true, type: 'prose' },
      { slug: 'chapter-02-creatures-of-the-middle', title: 'Creatures of the Middle', number: 2, readingTime: '10 min', description: 'The balanced beings who inhabit the space between light and dark.', published: true, type: 'prose' },
      { slug: 'chapter-03-creatures-of-crisis', title: 'Creatures of Crisis', number: 3, readingTime: '10 min', description: 'Born from tension and transformation — the creatures that emerge in times of crisis.', published: true, type: 'prose' },
      { slug: 'chapter-04-creatures-of-the-dark', title: 'Creatures of the Dark', number: 4, readingTime: '10 min', description: 'The shadow beings — terrible, necessary, guardians of the deep.', published: true, type: 'prose' },
      { slug: 'chapter-05-creatures-of-light', title: 'Creatures of Light', number: 5, readingTime: '10 min', description: 'The luminous beings — radiant, transcendent, keepers of the dawn.', published: true, type: 'prose' },
    ],
  },

  // ─── 22. Arcanea Wisdom Scrolls ─────────────────────────────────
  {
    slug: 'arcanea-wisdom-scrolls',
    title: 'Arcanea Wisdom Scrolls',
    subtitle: 'Meditations and Teachings',
    author: 'Frank Riemer',
    publishDate: '2026',
    description:
      'Morning meditations, evening reflections, aphorisms of the masters, and letters to the seeker — the collected wisdom of Arcanea\'s sages.',
    keywords: ['Arcanea', 'wisdom', 'meditations', 'aphorisms', 'philosophy'],
    coverImage: '/images/books/arcanea-wisdom-scrolls-cover.png',
    theme: {
      id: 'arcanea-wisdom-scrolls',
      name: 'Arcanea Wisdom Scrolls',
      primary: 'amber',
      accent: 'gold',
      bgDark: '#0f0a05',
      headingFont: 'serif',
      bodyFont: 'serif',
    },
    status: 'published',
    categories: ['Philosophy', 'Wisdom', 'Arcanea'],
    contentDir: 'content/books/arcanea-wisdom-scrolls',
    chapters: [
      { slug: 'chapter-01-morning-meditations', title: 'Morning Meditations', number: 1, readingTime: '10 min', description: 'Begin each day with the wisdom of Arcanea\'s sages.', published: true, type: 'quotes' },
      { slug: 'chapter-02-evening-reflections', title: 'Evening Reflections', number: 2, readingTime: '10 min', description: 'Close each day with reflection and gratitude.', published: true, type: 'quotes' },
      { slug: 'chapter-03-aphorisms-of-the-masters', title: 'Aphorisms of the Masters', number: 3, readingTime: '10 min', description: 'Concentrated wisdom from the masters of Arcanea.', published: true, type: 'quotes' },
      { slug: 'chapter-04-letters-to-the-seeker', title: 'Letters to the Seeker', number: 4, readingTime: '10 min', description: 'Personal letters of guidance for those on the path.', published: true, type: 'prose' },
    ],
  },

  // ─── 23. Arcanea Creator Principles ─────────────────────────────
  {
    slug: 'arcanea-creator-principles',
    title: 'Arcanea Creator Principles',
    subtitle: 'The Partnership Between Human and AI',
    author: 'Frank Riemer',
    publishDate: '2026',
    description:
      'The seven principles of human-AI creative partnership — drawn from the Arcanean tradition. Trust calibration, complementary strengths, and the generator-editor dance.',
    keywords: ['Arcanea', 'creator principles', 'human-AI partnership', 'creative collaboration'],
    coverImage: '/images/books/arcanea-creator-principles-cover.png',
    theme: {
      id: 'arcanea-creator-principles',
      name: 'Arcanea Creator Principles',
      primary: 'amber',
      accent: 'gold',
      bgDark: '#0f0a05',
      headingFont: 'serif',
      bodyFont: 'sans',
    },
    status: 'published',
    categories: ['AI', 'Creativity', 'Arcanea'],
    contentDir: 'content/books/arcanea-creator-principles',
    chapters: [
      { slug: 'chapter-01-the-seven-principles', title: 'The Seven Principles', number: 1, readingTime: '10 min', description: 'The foundational principles of Arcanean creative partnership.', published: true, type: 'prose' },
      { slug: 'chapter-02-the-partnership-principle', title: 'The Partnership Principle', number: 2, readingTime: '10 min', description: 'Scroll I — How partnership transforms both creator and creation.', published: true, type: 'prose' },
      { slug: 'chapter-03-complementary-strengths', title: 'Complementary Strengths', number: 3, readingTime: '10 min', description: 'Scroll II — Leveraging what each partner does uniquely well.', published: true, type: 'prose' },
      { slug: 'chapter-04-collaboration-modes', title: 'Collaboration Modes', number: 4, readingTime: '10 min', description: 'Scroll III — The different modes of human-AI creative collaboration.', published: true, type: 'prose' },
      { slug: 'chapter-05-trust-calibration', title: 'Trust Calibration', number: 5, readingTime: '10 min', description: 'Scroll IV — Calibrating trust between human intuition and AI capability.', published: true, type: 'prose' },
      { slug: 'chapter-06-the-generator-editor-dance', title: 'The Generator-Editor Dance', number: 6, readingTime: '10 min', description: 'Scroll V — The rhythmic alternation between generation and refinement.', published: true, type: 'prose' },
      { slug: 'chapter-07-advanced-partnership', title: 'Advanced Partnership', number: 7, readingTime: '10 min', description: 'Scroll VI — Mastering the highest levels of human-AI creative symbiosis.', published: true, type: 'prose' },
    ],
  },
];

// ─── Helper Functions ───────────────────────────────────────────

export function getBookBySlug(slug: string): BookConfig | undefined {
  return booksRegistry.find((b) => b.slug === slug);
}

export function getPublishedBooks(): BookConfig[] {
  return booksRegistry.filter((b) => b.status !== 'draft');
}

export function getAllBookSlugs(): string[] {
  return booksRegistry.map((b) => b.slug);
}
