/**
 * v0-generated variant: ACOS Product
 * Generated: 2026-02-08 via v0-1.5-lg with extended thinking
 * Chat: f6ToNz0ER5c
 * Demo: https://demo-kzmpc9qb5oxmrzbm1yz0.vusercontent.net
 * 
 * This is a reference design generated by v0. Review and adopt
 * the best patterns into the production codebase.
 * DO NOT deploy directly — adapt to existing component patterns.
 */

'use client'

import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { 
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"
import { motion } from "framer-motion"
import { ArrowRight, Check, Zap, Brain, Network, Sparkles, Shield, Star } from "lucide-react"

export default function ACOSLandingPage() {
  return (
    <div className="min-h-screen bg-background text-foreground overflow-x-hidden">
      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 z-50 border-b border-border/50 backdrop-blur-xl bg-background/80">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-[#AB47C7] to-[#43BFE3] flex items-center justify-center">
                <span className="text-white font-bold text-sm">Fx</span>
              </div>
              <span className="font-semibold text-lg">frankx.ai</span>
            </div>
            <div className="hidden md:flex items-center gap-8">
              <a href="#features" className="text-sm text-muted-foreground hover:text-foreground transition-colors">Features</a>
              <a href="#pricing" className="text-sm text-muted-foreground hover:text-foreground transition-colors">Pricing</a>
              <a href="#faq" className="text-sm text-muted-foreground hover:text-foreground transition-colors">FAQ</a>
              <Button size="sm" className="bg-[#AB47C7] hover:bg-[#9537B0] text-white">
                Get Started
              </Button>
            </div>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="relative pt-32 pb-20 px-4 sm:px-6 lg:px-8 overflow-hidden">
        {/* Animated Background */}
        <div className="absolute inset-0 overflow-hidden">
          <motion.div
            className="absolute top-1/4 left-1/4 w-[500px] h-[500px] rounded-full bg-[#AB47C7]/20 blur-[120px]"
            animate={{
              scale: [1, 1.2, 1],
              opacity: [0.3, 0.5, 0.3],
            }}
            transition={{
              duration: 8,
              repeat: Infinity,
              ease: "easeInOut"
            }}
          />
          <motion.div
            className="absolute bottom-1/4 right-1/4 w-[400px] h-[400px] rounded-full bg-[#43BFE3]/20 blur-[100px]"
            animate={{
              scale: [1.2, 1, 1.2],
              opacity: [0.5, 0.3, 0.5],
            }}
            transition={{
              duration: 10,
              repeat: Infinity,
              ease: "easeInOut"
            }}
          />
        </div>

        <div className="max-w-7xl mx-auto relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="text-center"
          >
            <Badge className="mb-6 bg-card border border-border text-foreground px-4 py-2">
              <Sparkles className="w-3 h-3 mr-2 inline" />
              630+ Skills • 40+ Agents • 7 Events • 20+ Hooks
            </Badge>
            
            <h1 className="text-6xl sm:text-7xl lg:text-8xl font-bold mb-6 text-balance">
              <span className="bg-gradient-to-r from-[#AB47C7] via-[#43BFE3] to-[#F59E0B] bg-clip-text text-transparent">
                ACOS
              </span>
            </h1>
            
            <p className="text-2xl sm:text-3xl lg:text-4xl font-semibold mb-4 text-balance">
              The Operating System for AI Creators
            </p>
            
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto mb-10 leading-relaxed text-pretty">
              {'Stop juggling scattered tools. ACOS orchestrates 630+ AI skills and 40+ specialized agents with intelligent auto-routing. Built for creators who demand more.'}
            </p>

            <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-12">
              <Button 
                size="lg" 
                className="bg-gradient-to-r from-[#AB47C7] to-[#9537B0] hover:from-[#9537B0] hover:to-[#7E2A98] text-white shadow-2xl shadow-[#AB47C7]/50 text-lg px-8 py-6 h-auto group"
              >
                Get ACOS — $997
                <ArrowRight className="ml-2 w-5 h-5 group-hover:translate-x-1 transition-transform" />
              </Button>
              <Button 
                size="lg" 
                variant="outline" 
                className="border-border hover:bg-card text-lg px-8 py-6 h-auto bg-transparent"
              >
                See it in action
              </Button>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Problem/Solution Section */}
      <section className="py-20 px-4 sm:px-6 lg:px-8 relative">
        <div className="max-w-7xl mx-auto">
          <div className="grid md:grid-cols-2 gap-8 items-center">
            {/* Before ACOS */}
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
            >
              <Card className="p-8 bg-card border-border backdrop-blur-sm">
                <div className="flex items-center gap-3 mb-6">
                  <div className="w-10 h-10 rounded-lg bg-destructive/10 flex items-center justify-center">
                    <span className="text-2xl">😓</span>
                  </div>
                  <h3 className="text-2xl font-bold text-foreground">Before ACOS</h3>
                </div>
                <ul className="space-y-4">
                  {[
                    'Switching between 10+ AI tools daily',
                    'Manually routing tasks to the right AI',
                    'Lost context across different systems',
                    'Repetitive prompt engineering',
                    'No intelligence layer or memory'
                  ].map((item, idx) => (
                    <li key={idx} className="flex items-start gap-3 text-muted-foreground">
                      <span className="text-destructive mt-1">✗</span>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </Card>
            </motion.div>

            {/* With ACOS */}
            <motion.div
              initial={{ opacity: 0, x: 20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.2 }}
            >
              <Card className="p-8 bg-gradient-to-br from-[#AB47C7]/10 to-[#43BFE3]/10 border-[#AB47C7]/30 backdrop-blur-sm relative overflow-hidden">
                <div className="absolute top-0 right-0 w-32 h-32 bg-[#AB47C7]/20 rounded-full blur-3xl" />
                <div className="relative">
                  <div className="flex items-center gap-3 mb-6">
                    <div className="w-10 h-10 rounded-lg bg-[#AB47C7] flex items-center justify-center">
                      <Sparkles className="w-5 h-5 text-white" />
                    </div>
                    <h3 className="text-2xl font-bold text-foreground">With ACOS</h3>
                  </div>
                  <ul className="space-y-4">
                    {[
                      'One unified system for all AI tasks',
                      'Automatic smart routing to specialists',
                      'Persistent context and memory',
                      'Self-learning and improving',
                      'Multi-agent swarm coordination'
                    ].map((item, idx) => (
                      <li key={idx} className="flex items-start gap-3 text-foreground">
                        <Check className="text-[#10B981] mt-1 flex-shrink-0 w-5 h-5" />
                        <span className="font-medium">{item}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </Card>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Features Deep-Dive */}
      <section id="features" className="py-20 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl sm:text-5xl font-bold mb-4 text-balance">
              {'AI That Actually Thinks'}
            </h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto text-pretty">
              {'Not another wrapper. ACOS is a complete intelligence layer that knows how to orchestrate AI agents like a conductor leads an orchestra.'}
            </p>
          </motion.div>

          <div className="space-y-20">
            {/* Feature 1 - Smart Agent Routing */}
            <div className="grid md:grid-cols-2 gap-12 items-center">
              <motion.div
                initial={{ opacity: 0, x: -20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
              >
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-[#AB47C7] to-[#9537B0] flex items-center justify-center">
                    <Zap className="w-6 h-6 text-white" />
                  </div>
                  <Badge className="bg-[#AB47C7]/20 text-[#AB47C7] border-[#AB47C7]/30">Smart Routing</Badge>
                </div>
                <h3 className="text-3xl font-bold mb-4 text-foreground">Auto-Detects Task Type</h3>
                <p className="text-muted-foreground leading-relaxed mb-6 text-pretty">
                  {'ACOS analyzes your request in milliseconds and routes it to the perfect specialist agent. Writing code? It goes to the Code Architect. Building a brand? Marketing Agent takes over. No manual selection needed.'}
                </p>
                <ul className="space-y-3">
                  {['Instant task classification', 'Context-aware routing', 'Fallback strategies'].map((item, idx) => (
                    <li key={idx} className="flex items-center gap-2 text-foreground">
                      <Check className="w-4 h-4 text-[#10B981]" />
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </motion.div>

              <motion.div
                initial={{ opacity: 0, x: 20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
              >
                <Card className="p-8 bg-card border-border backdrop-blur-sm">
                  <div className="space-y-4">
                    <div className="flex items-center justify-between p-4 bg-muted/50 rounded-lg border border-border">
                      <span className="text-sm font-mono text-muted-foreground">User Input</span>
                      <ArrowRight className="w-4 h-4 text-muted-foreground" />
                    </div>
                    <div className="grid grid-cols-2 gap-3">
                      {['Code Agent', 'Design Agent', 'SEO Agent', 'Data Agent'].map((agent, idx) => (
                        <div key={idx} className="p-3 bg-gradient-to-br from-[#AB47C7]/10 to-[#43BFE3]/10 border border-[#AB47C7]/30 rounded-lg text-center text-sm font-medium">
                          {agent}
                        </div>
                      ))}
                    </div>
                    <div className="flex items-center justify-center">
                      <ArrowRight className="w-4 h-4 text-muted-foreground rotate-90" />
                    </div>
                    <div className="p-4 bg-[#10B981]/10 border border-[#10B981]/30 rounded-lg text-center">
                      <span className="text-sm font-medium text-[#10B981]">Optimal Result</span>
                    </div>
                  </div>
                </Card>
              </motion.div>
            </div>

            {/* Feature 2 - 630+ Skills Library */}
            <div className="grid md:grid-cols-2 gap-12 items-center">
              <motion.div
                initial={{ opacity: 0, x: -20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                className="md:order-2"
              >
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-[#F59E0B] to-[#D97706] flex items-center justify-center">
                    <Brain className="w-6 h-6 text-white" />
                  </div>
                  <Badge className="bg-[#F59E0B]/20 text-[#F59E0B] border-[#F59E0B]/30">630+ Skills</Badge>
                </div>
                <h3 className="text-3xl font-bold mb-4 text-foreground">Every Domain Covered</h3>
                <p className="text-muted-foreground leading-relaxed mb-6 text-pretty">
                  {'From technical architecture to creative writing, SEO to system design—ACOS has a skill for it. Each skill is battle-tested and optimized for specific outcomes.'}
                </p>
                <div className="grid grid-cols-2 gap-2">
                  {['Architecture', 'Frontend', 'Backend', 'Database', 'DevOps', 'Testing', 'SEO', 'Content'].map((skill, idx) => (
                    <div key={idx} className="px-3 py-2 bg-muted/50 rounded-lg text-sm border border-border">
                      {skill}
                    </div>
                  ))}
                </div>
              </motion.div>

              <motion.div
                initial={{ opacity: 0, x: 20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                className="md:order-1"
              >
                <Card className="p-8 bg-card border-border backdrop-blur-sm">
                  <div className="space-y-3">
                    {[
                      { name: 'Technical Skills', count: '220+', color: '#AB47C7' },
                      { name: 'Creative Skills', count: '180+', color: '#43BFE3' },
                      { name: 'Business Skills', count: '130+', color: '#F59E0B' },
                      { name: 'Specialized', count: '100+', color: '#10B981' }
                    ].map((category, idx) => (
                      <div key={idx} className="flex items-center justify-between p-4 bg-muted/30 rounded-lg border border-border">
                        <span className="font-medium">{category.name}</span>
                        <Badge style={{ backgroundColor: `${category.color}20`, color: category.color, borderColor: `${category.color}30` }}>
                          {category.count}
                        </Badge>
                      </div>
                    ))}
                  </div>
                </Card>
              </motion.div>
            </div>

            {/* Feature 3 - Multi-Agent Swarms */}
            <div className="grid md:grid-cols-2 gap-12 items-center">
              <motion.div
                initial={{ opacity: 0, x: -20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
              >
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-[#43BFE3] to-[#2BA5C9] flex items-center justify-center">
                    <Network className="w-6 h-6 text-white" />
                  </div>
                  <Badge className="bg-[#43BFE3]/20 text-[#43BFE3] border-[#43BFE3]/30">Swarm Intelligence</Badge>
                </div>
                <h3 className="text-3xl font-bold mb-4 text-foreground">Coordinate Complex Tasks</h3>
                <p className="text-muted-foreground leading-relaxed mb-6 text-pretty">
                  {'For complex projects, ACOS deploys multiple agents that work together seamlessly. They communicate, share context, and coordinate their outputs like a high-performing team.'}
                </p>
                <ul className="space-y-3">
                  {['Parallel task execution', 'Shared memory context', 'Conflict resolution', 'Coordinated outputs'].map((item, idx) => (
                    <li key={idx} className="flex items-center gap-2 text-foreground">
                      <Check className="w-4 h-4 text-[#10B981]" />
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </motion.div>

              <motion.div
                initial={{ opacity: 0, x: 20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
              >
                <Card className="p-8 bg-card border-border backdrop-blur-sm relative overflow-hidden">
                  <div className="absolute inset-0 bg-gradient-to-br from-[#43BFE3]/5 to-transparent" />
                  <div className="relative">
                    <div className="text-center mb-6">
                      <div className="inline-block p-4 bg-[#43BFE3]/10 rounded-lg border border-[#43BFE3]/30 mb-4">
                        <Brain className="w-8 h-8 text-[#43BFE3]" />
                      </div>
                      <p className="text-sm font-medium text-muted-foreground">Orchestrator</p>
                    </div>
                    <div className="grid grid-cols-3 gap-3">
                      {['Agent 1', 'Agent 2', 'Agent 3'].map((agent, idx) => (
                        <div key={idx} className="aspect-square bg-muted/50 rounded-lg border border-border flex items-center justify-center text-xs font-medium">
                          {agent}
                        </div>
                      ))}
                    </div>
                    <div className="mt-6 p-3 bg-[#10B981]/10 rounded-lg border border-[#10B981]/30 text-center">
                      <span className="text-xs font-medium text-[#10B981]">Unified Output</span>
                    </div>
                  </div>
                </Card>
              </motion.div>
            </div>

            {/* Feature 4 - Self-Learning System */}
            <div className="grid md:grid-cols-2 gap-12 items-center">
              <motion.div
                initial={{ opacity: 0, x: -20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                className="md:order-2"
              >
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-[#10B981] to-[#059669] flex items-center justify-center">
                    <Sparkles className="w-6 h-6 text-white" />
                  </div>
                  <Badge className="bg-[#10B981]/20 text-[#10B981] border-[#10B981]/30">Adaptive AI</Badge>
                </div>
                <h3 className="text-3xl font-bold mb-4 text-foreground">Gets Smarter Over Time</h3>
                <p className="text-muted-foreground leading-relaxed mb-6 text-pretty">
                  {'ACOS learns from every interaction. It remembers your preferences, adapts to your workflow, and improves its recommendations based on what works best for you.'}
                </p>
                <ul className="space-y-3">
                  {['Pattern recognition', 'Preference learning', 'Performance optimization', 'Continuous improvement'].map((item, idx) => (
                    <li key={idx} className="flex items-center gap-2 text-foreground">
                      <Check className="w-4 h-4 text-[#10B981]" />
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </motion.div>

              <motion.div
                initial={{ opacity: 0, x: 20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                className="md:order-1"
              >
                <Card className="p-8 bg-card border-border backdrop-blur-sm">
                  <div className="space-y-4">
                    {[
                      { week: 'Week 1', accuracy: '85%', color: 'bg-[#10B981]/30' },
                      { week: 'Week 2', accuracy: '90%', color: 'bg-[#10B981]/50' },
                      { week: 'Week 3', accuracy: '94%', color: 'bg-[#10B981]/70' },
                      { week: 'Week 4', accuracy: '98%', color: 'bg-[#10B981]' }
                    ].map((data, idx) => (
                      <div key={idx} className="space-y-2">
                        <div className="flex items-center justify-between text-sm">
                          <span className="text-muted-foreground">{data.week}</span>
                          <span className="font-medium text-foreground">{data.accuracy}</span>
                        </div>
                        <div className="h-2 bg-muted rounded-full overflow-hidden">
                          <motion.div
                            className={`h-full ${data.color}`}
                            initial={{ width: 0 }}
                            whileInView={{ width: data.accuracy }}
                            viewport={{ once: true }}
                            transition={{ duration: 1, delay: idx * 0.1 }}
                          />
                        </div>
                      </div>
                    ))}
                  </div>
                </Card>
              </motion.div>
            </div>
          </div>
        </div>
      </section>

      {/* Architecture Diagram */}
      <section className="py-20 px-4 sm:px-6 lg:px-8 bg-muted/20">
        <div className="max-w-5xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-12"
          >
            <h2 className="text-4xl font-bold mb-4">System Architecture</h2>
            <p className="text-muted-foreground">{'See how ACOS orchestrates AI at every layer'}</p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            className="space-y-6"
          >
            {[
              { label: 'Your AI IDE', sublabel: 'Claude Code, Cursor, Windsurf, etc.', color: '#F59E0B' },
              { label: 'Starlight Intelligence Layer', sublabel: 'Context, memory, learning', color: '#43BFE3' },
              { label: 'Agent Orchestrator', sublabel: '40+ specialized agents with auto-routing', color: '#AB47C7' },
              { label: 'Skills Library', sublabel: '630+ battle-tested skills', color: '#10B981' },
            ].map((layer, idx) => (
              <motion.div
                key={idx}
                initial={{ opacity: 0, x: -20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ delay: idx * 0.1 }}
              >
                <Card className="p-6 bg-card border-border backdrop-blur-sm relative overflow-hidden group hover:border-[#AB47C7]/50 transition-colors">
                  <div className="absolute left-0 top-0 bottom-0 w-1" style={{ backgroundColor: layer.color }} />
                  <div className="pl-4">
                    <h3 className="text-lg font-semibold mb-1 text-foreground">{layer.label}</h3>
                    <p className="text-sm text-muted-foreground">{layer.sublabel}</p>
                  </div>
                  {idx < 3 && (
                    <div className="absolute -bottom-3 left-1/2 transform -translate-x-1/2">
                      <ArrowRight className="w-5 h-5 text-muted-foreground rotate-90" />
                    </div>
                  )}
                </Card>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* Included Systems */}
      <section className="py-20 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl font-bold mb-4">{'Four Systems. One Platform.'}</h2>
            <p className="text-muted-foreground">{'ACOS includes everything you need to build at AI speed'}</p>
          </motion.div>

          <div className="grid md:grid-cols-2 gap-6">
            {[
              {
                name: 'Vibe OS',
                description: 'Core operating system for AI-native workflows',
                icon: '🎨',
                color: '#43BFE3',
                features: ['Smart templates', 'Workflow automation', 'Context management']
              },
              {
                name: 'GenCreator OS',
                description: 'Complete content creation and generation system',
                icon: '✨',
                color: '#F59E0B',
                features: ['Multi-format generation', 'Brand consistency', 'Asset management']
              },
              {
                name: 'Arcanea Framework',
                description: 'Advanced AI orchestration and reasoning engine',
                icon: '🧠',
                color: '#AB47C7',
                features: ['Multi-agent coordination', 'Advanced reasoning', 'Memory systems']
              },
              {
                name: 'Starlight Layer',
                description: 'Intelligence layer for context and learning',
                icon: '⭐',
                color: '#10B981',
                features: ['Contextual awareness', 'Pattern learning', 'Adaptive responses']
              }
            ].map((system, idx) => (
              <motion.div
                key={idx}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: idx * 0.1 }}
              >
                <Card className="p-8 bg-card border-border backdrop-blur-sm h-full hover:border-opacity-50 transition-all group" style={{ borderColor: `${system.color}30` }}>
                  <div className="flex items-start gap-4 mb-4">
                    <div className="w-12 h-12 rounded-xl flex items-center justify-center text-2xl" style={{ backgroundColor: `${system.color}20` }}>
                      {system.icon}
                    </div>
                    <div>
                      <h3 className="text-xl font-bold mb-1 text-foreground">{system.name}</h3>
                      <p className="text-sm text-muted-foreground">{system.description}</p>
                    </div>
                  </div>
                  <ul className="space-y-2 mt-6">
                    {system.features.map((feature, fidx) => (
                      <li key={fidx} className="flex items-center gap-2 text-sm text-muted-foreground">
                        <Check className="w-4 h-4 flex-shrink-0" style={{ color: system.color }} />
                        <span>{feature}</span>
                      </li>
                    ))}
                  </ul>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-20 px-4 sm:px-6 lg:px-8 bg-muted/20">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl font-bold mb-4">Trusted by AI Creators</h2>
            <p className="text-muted-foreground">{'See what creators are building with ACOS'}</p>
          </motion.div>

          <div className="grid md:grid-cols-3 gap-6">
            {[
              {
                quote: "ACOS replaced my entire AI toolkit. The auto-routing is genuinely magical—it just knows which agent I need.",
                author: "Sarah Chen",
                role: "Founder, TechVision AI",
                rating: 5
              },
              {
                quote: "I've tried every AI orchestration tool out there. ACOS is the only one that actually delivers on the promise of intelligent automation.",
                author: "Marcus Rodriguez",
                role: "Independent Creator",
                rating: 5
              },
              {
                quote: "The multi-agent swarms feature alone is worth the price. It's like having a full AI team at your fingertips.",
                author: "Emily Zhang",
                role: "Product Designer",
                rating: 5
              }
            ].map((testimonial, idx) => (
              <motion.div
                key={idx}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: idx * 0.1 }}
              >
                <Card className="p-6 bg-card border-border backdrop-blur-sm h-full">
                  <div className="flex gap-1 mb-4">
                    {[...Array(testimonial.rating)].map((_, i) => (
                      <Star key={i} className="w-4 h-4 fill-[#F59E0B] text-[#F59E0B]" />
                    ))}
                  </div>
                  <p className="text-foreground mb-6 leading-relaxed text-pretty">"{testimonial.quote}"</p>
                  <div>
                    <p className="font-semibold text-foreground">{testimonial.author}</p>
                    <p className="text-sm text-muted-foreground">{testimonial.role}</p>
                  </div>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing CTA */}
      <section id="pricing" className="py-20 px-4 sm:px-6 lg:px-8 relative overflow-hidden">
        <div className="absolute inset-0">
          <motion.div
            className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] rounded-full bg-[#AB47C7]/10 blur-[120px]"
            animate={{
              scale: [1, 1.1, 1],
              opacity: [0.3, 0.4, 0.3],
            }}
            transition={{
              duration: 8,
              repeat: Infinity,
              ease: "easeInOut"
            }}
          />
        </div>

        <div className="max-w-4xl mx-auto relative z-10">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
          >
            <Card className="p-12 bg-gradient-to-br from-card to-card/50 border-[#AB47C7]/30 backdrop-blur-sm text-center relative overflow-hidden">
              <div className="absolute top-0 right-0 w-64 h-64 bg-[#AB47C7]/10 rounded-full blur-3xl" />
              <div className="absolute bottom-0 left-0 w-64 h-64 bg-[#43BFE3]/10 rounded-full blur-3xl" />
              
              <div className="relative">
                <Badge className="mb-6 bg-[#AB47C7]/20 text-[#AB47C7] border-[#AB47C7]/30 px-4 py-2">
                  <Shield className="w-3 h-3 mr-2 inline" />
                  30-Day Money-Back Guarantee
                </Badge>

                <h2 className="text-5xl font-bold mb-4 text-foreground">Get ACOS Today</h2>
                
                <div className="mb-6">
                  <div className="text-6xl font-bold bg-gradient-to-r from-[#AB47C7] to-[#43BFE3] bg-clip-text text-transparent">
                    $997
                  </div>
                  <p className="text-muted-foreground mt-2">One-time payment. Lifetime access.</p>
                </div>

                <div className="max-w-md mx-auto mb-8 space-y-3">
                  {[
                    '630+ AI Skills',
                    '40+ Specialized Agents',
                    'Smart Auto-Routing',
                    'Multi-Agent Swarms',
                    'All 4 Systems Included',
                    'Lifetime Updates',
                    'Priority Support'
                  ].map((feature, idx) => (
                    <div key={idx} className="flex items-center gap-3 text-left">
                      <div className="w-5 h-5 rounded-full bg-[#10B981]/20 flex items-center justify-center flex-shrink-0">
                        <Check className="w-3 h-3 text-[#10B981]" />
                      </div>
                      <span className="text-foreground">{feature}</span>
                    </div>
                  ))}
                </div>

                <Button 
                  size="lg" 
                  className="bg-gradient-to-r from-[#AB47C7] to-[#9537B0] hover:from-[#9537B0] hover:to-[#7E2A98] text-white shadow-2xl shadow-[#AB47C7]/50 text-lg px-12 py-7 h-auto group mb-4"
                >
                  Get Instant Access — $997
                  <ArrowRight className="ml-2 w-5 h-5 group-hover:translate-x-1 transition-transform" />
                </Button>

                <p className="text-sm text-muted-foreground">
                  {'Works with Claude Code, Cursor, Windsurf, and any AI IDE'}
                </p>
              </div>
            </Card>
          </motion.div>
        </div>
      </section>

      {/* FAQ */}
      <section id="faq" className="py-20 px-4 sm:px-6 lg:px-8">
        <div className="max-w-3xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-12"
          >
            <h2 className="text-4xl font-bold mb-4">Frequently Asked Questions</h2>
            <p className="text-muted-foreground">{'Everything you need to know about ACOS'}</p>
          </motion.div>

          <Accordion type="single" collapsible className="space-y-4">
            {[
              {
                question: "What AI IDEs does ACOS work with?",
                answer: "ACOS works seamlessly with Claude Code, Cursor, Windsurf, and any AI IDE that supports custom instructions and configurations. It's designed to be IDE-agnostic."
              },
              {
                question: "How is ACOS different from ChatGPT or Claude?",
                answer: "ACOS is an orchestration layer, not a language model. It intelligently routes tasks to the right specialized agents, maintains context across sessions, and coordinates multi-agent workflows. Think of it as the conductor, not the instrument."
              },
              {
                question: "Do I need technical knowledge to use ACOS?",
                answer: "No. ACOS is designed for creators of all skill levels. The smart routing handles the complexity for you. However, technical users can dive deeper into customization if they want."
              },
              {
                question: "Is there a monthly subscription?",
                answer: "No. ACOS is a one-time payment of $997 with lifetime access and updates. No recurring fees, ever."
              },
              {
                question: "What's included in the lifetime updates?",
                answer: "You get all future skills, agents, features, and system improvements at no additional cost. As AI evolves, ACOS evolves with it—and you're always on the latest version."
              },
              {
                question: "Can I get a refund if it's not for me?",
                answer: "Absolutely. We offer a 30-day money-back guarantee, no questions asked. If ACOS doesn't transform your AI workflow, just let us know."
              }
            ].map((faq, idx) => (
              <motion.div
                key={idx}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: idx * 0.05 }}
              >
                <AccordionItem value={`item-${idx}`} className="bg-card border border-border rounded-lg px-6 backdrop-blur-sm">
                  <AccordionTrigger className="text-left text-foreground hover:text-[#AB47C7] transition-colors">
                    {faq.question}
                  </AccordionTrigger>
                  <AccordionContent className="text-muted-foreground leading-relaxed text-pretty">
                    {faq.answer}
                  </AccordionContent>
                </AccordionItem>
              </motion.div>
            ))}
          </Accordion>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border py-12 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-[#AB47C7] to-[#43BFE3] flex items-center justify-center">
                <span className="text-white font-bold text-sm">Fx</span>
              </div>
              <span className="font-semibold">frankx.ai</span>
            </div>
            <div className="flex items-center gap-6 text-sm text-muted-foreground">
              <a href="#" className="hover:text-foreground transition-colors">Terms</a>
              <a href="#" className="hover:text-foreground transition-colors">Privacy</a>
              <a href="#" className="hover:text-foreground transition-colors">Contact</a>
            </div>
            <p className="text-sm text-muted-foreground">
              © 2024 frankx.ai. All rights reserved.
            </p>
          </div>
        </div>
      </footer>
    </div>
  )
}
