/**
 * v0-generated variant: Inner Circle
 * Generated: 2026-02-08 via v0-1.5-lg with extended thinking
 * Chat: uaPnlaw4BIK
 * Demo: https://demo-kzmqkdpccsp0s5d342f9.vusercontent.net
 * 
 * This is a reference design generated by v0. Review and adopt
 * the best patterns into the production codebase.
 * DO NOT deploy directly — adapt to existing component patterns.
 */

'use client'

import { motion } from 'framer-motion'
import { Check, Sparkles, Users, Zap, BookOpen, Calendar, MessageSquare } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Progress } from '@/components/ui/progress'
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion'

export default function InnerCirclePage() {
  const features = [
    {
      icon: Calendar,
      title: 'Weekly Live Sessions',
      description: "Direct access to Frank's AI architecture thinking",
    },
    {
      icon: Users,
      title: 'Private Community',
      description: 'Connect with elite builders and creators',
    },
    {
      icon: Zap,
      title: 'Early Access',
      description: 'First to test new products, tools, and frameworks',
    },
    {
      icon: BookOpen,
      title: 'Monthly Masterclass',
      description: 'Deep-dive workshops on advanced AI patterns',
    },
    {
      icon: Sparkles,
      title: 'Template Library',
      description: 'Production-ready code, prompts, and workflows',
    },
    {
      icon: MessageSquare,
      title: '1-on-1 Office Hours',
      description: 'Monthly private strategy session',
    },
  ]

  const testimonials = [
    {
      name: 'Sarah Chen',
      role: 'AI Engineer @ Stripe',
      content: "The Inner Circle transformed how I think about AI architecture. Frank's insights are worth 10x the price.",
      avatar: 'SC',
    },
    {
      name: 'Marcus Rodriguez',
      role: 'Founder @ Neural Labs',
      content: 'Being part of this community gave me the confidence to launch my AI startup. The network alone is invaluable.',
      avatar: 'MR',
    },
    {
      name: 'Emily Watson',
      role: 'Product Lead @ OpenAI',
      content: 'The monthly masterclasses are phenomenal. I implement something new from each session immediately.',
      avatar: 'EW',
    },
  ]

  const pricingFeatures = [
    'Weekly live sessions with Frank',
    'Access to private Discord community',
    'Monthly 1-on-1 office hours',
    'Early access to all new products',
    'Complete template library',
    'Monthly deep-dive masterclasses',
    'Direct message access to Frank',
    'Exclusive member-only events',
  ]

  const faqs = [
    {
      question: 'What exactly do I get as a member?',
      answer: 'Full access to weekly live sessions, monthly 1-on-1 office hours, our private Discord community, complete template library, monthly masterclasses, and early access to all Frank X products and tools.',
    },
    {
      question: 'How much time do I need to commit?',
      answer: 'The weekly sessions are 60 minutes, and you can attend live or watch the replay. Everything else is async and on-demand, so you can engage as much or as little as your schedule allows.',
    },
    {
      question: 'Is there a refund policy?',
      answer: 'Yes! If you\'re not satisfied within the first 14 days, we\'ll refund your membership in full. We want members who are excited to be here.',
    },
    {
      question: 'Why is it limited to 100 members?',
      answer: 'To maintain quality and intimacy. Frank personally reviews every application and wants to ensure everyone gets direct attention during office hours and sessions.',
    },
    {
      question: 'Can I cancel anytime?',
      answer: 'Yes, you can cancel your monthly membership anytime. Annual memberships are non-refundable after 14 days, but you keep access for the full year.',
    },
  ]

  return (
    <div className="min-h-screen bg-background">
      {/* Animated Background Orbs */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <motion.div
          className="absolute top-1/4 -left-48 w-96 h-96 rounded-full opacity-20"
          style={{
            background: 'radial-gradient(circle, #AB47C7 0%, transparent 70%)',
            filter: 'blur(60px)',
          }}
          animate={{
            scale: [1, 1.2, 1],
            x: [0, 50, 0],
            y: [0, 30, 0],
          }}
          transition={{
            duration: 8,
            repeat: Number.POSITIVE_INFINITY,
            ease: 'easeInOut',
          }}
        />
        <motion.div
          className="absolute top-1/3 -right-48 w-96 h-96 rounded-full opacity-20"
          style={{
            background: 'radial-gradient(circle, #43BFE3 0%, transparent 70%)',
            filter: 'blur(60px)',
          }}
          animate={{
            scale: [1.2, 1, 1.2],
            x: [0, -50, 0],
            y: [0, -30, 0],
          }}
          transition={{
            duration: 10,
            repeat: Number.POSITIVE_INFINITY,
            ease: 'easeInOut',
          }}
        />
      </div>

      {/* Hero Section */}
      <section className="relative pt-32 pb-20 px-4 overflow-hidden">
        <div className="max-w-4xl mx-auto text-center">
          {/* Limited Scarcity Badge */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="inline-flex items-center gap-2 px-4 py-2 rounded-full border border-accent/20 bg-accent/10 text-accent text-sm font-medium mb-8"
          >
            <Sparkles className="w-4 h-4" />
            <span>Limited to 100 members</span>
          </motion.div>

          {/* Main Title */}
          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
            className="text-6xl md:text-7xl font-bold mb-6 text-balance"
            style={{
              background: 'linear-gradient(135deg, #AB47C7 0%, #43BFE3 100%)',
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent',
              backgroundClip: 'text',
            }}
          >
            The Inner Circle
          </motion.h1>

          {/* Subtitle */}
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
            className="text-xl md:text-2xl text-muted-foreground mb-12 text-balance"
          >
            Where serious AI builders come to level up.
          </motion.p>

          {/* Member Count Progress */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.3 }}
            className="max-w-md mx-auto"
          >
            <div className="flex items-center justify-between text-sm mb-2">
              <span className="text-muted-foreground">Member spots filled</span>
              <span className="text-accent font-semibold">47/100</span>
            </div>
            <Progress value={47} className="h-2" />
          </motion.div>
        </div>
      </section>

      {/* What You Get Section */}
      <section className="py-20 px-4">
        <div className="max-w-6xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl md:text-5xl font-bold mb-4">What You Get</h2>
            <p className="text-lg text-muted-foreground">
              Everything you need to become an elite AI builder
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((feature, index) => (
              <motion.div
                key={feature.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
              >
                <Card className="p-6 bg-card border-border hover:border-primary/50 transition-all duration-300 group h-full">
                  <div className="flex flex-col h-full">
                    <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center mb-4 group-hover:bg-primary/20 transition-colors">
                      <feature.icon className="w-6 h-6 text-primary" />
                    </div>
                    <h3 className="text-xl font-semibold mb-2">{feature.title}</h3>
                    <p className="text-muted-foreground leading-relaxed">
                      {feature.description}
                    </p>
                  </div>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Social Proof Section */}
      <section className="py-20 px-4 bg-muted/30">
        <div className="max-w-6xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl md:text-5xl font-bold mb-4">Trusted by Elite Builders</h2>
            <p className="text-lg text-muted-foreground">
              See what our members are saying
            </p>
          </motion.div>

          <div className="grid md:grid-cols-3 gap-6">
            {testimonials.map((testimonial, index) => (
              <motion.div
                key={testimonial.name}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
              >
                <Card className="p-6 bg-card border-border h-full flex flex-col">
                  <p className="text-foreground mb-6 leading-relaxed flex-grow">
                    "{testimonial.content}"
                  </p>
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-full bg-gradient-to-br from-primary to-secondary flex items-center justify-center text-sm font-semibold">
                      {testimonial.avatar}
                    </div>
                    <div>
                      <div className="font-semibold text-sm">{testimonial.name}</div>
                      <div className="text-xs text-muted-foreground">{testimonial.role}</div>
                    </div>
                  </div>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing Section */}
      <section className="py-20 px-4">
        <div className="max-w-4xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl md:text-5xl font-bold mb-4">Join the Inner Circle</h2>
            <p className="text-lg text-muted-foreground">
              Invest in your AI mastery today
            </p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5, delay: 0.2 }}
          >
            <Card className="relative overflow-hidden bg-card border-2 border-accent/30">
              {/* Gold accent glow */}
              <div 
                className="absolute inset-0 opacity-5 pointer-events-none"
                style={{
                  background: 'radial-gradient(circle at 50% 0%, #F59E0B 0%, transparent 50%)',
                }}
              />
              
              <div className="relative p-8 md:p-12">
                <div className="text-center mb-8">
                  <div className="inline-block px-3 py-1 rounded-full bg-accent/20 text-accent text-sm font-medium mb-4">
                    Premium Membership
                  </div>
                  <div className="flex items-baseline justify-center gap-2 mb-2">
                    <span className="text-5xl md:text-6xl font-bold">$97</span>
                    <span className="text-2xl text-muted-foreground">/month</span>
                  </div>
                  <p className="text-muted-foreground">
                    or $997/year <span className="text-emerald-500 font-semibold">(save 2 months)</span>
                  </p>
                </div>

                <div className="space-y-4 mb-8">
                  {pricingFeatures.map((feature, index) => (
                    <motion.div
                      key={feature}
                      initial={{ opacity: 0, x: -20 }}
                      whileInView={{ opacity: 1, x: 0 }}
                      viewport={{ once: true }}
                      transition={{ duration: 0.3, delay: index * 0.05 }}
                      className="flex items-start gap-3"
                    >
                      <div className="w-5 h-5 rounded-full bg-emerald-500/20 flex items-center justify-center flex-shrink-0 mt-0.5">
                        <Check className="w-3 h-3 text-emerald-500" />
                      </div>
                      <span className="text-foreground leading-relaxed">{feature}</span>
                    </motion.div>
                  ))}
                </div>

                <div className="flex flex-col sm:flex-row gap-4">
                  <Button
                    size="lg"
                    className="flex-1 text-lg h-14 font-semibold relative overflow-hidden group"
                    style={{
                      background: 'linear-gradient(135deg, #AB47C7 0%, #43BFE3 100%)',
                    }}
                  >
                    <motion.div
                      className="absolute inset-0 bg-white/20"
                      initial={{ x: '-100%' }}
                      whileHover={{ x: '100%' }}
                      transition={{ duration: 0.5 }}
                    />
                    <span className="relative">Join the Inner Circle</span>
                  </Button>
                  <Button
                    size="lg"
                    variant="outline"
                    className="flex-1 text-lg h-14 font-semibold border-accent text-accent hover:bg-accent/10 bg-transparent"
                  >
                    Annual Plan
                  </Button>
                </div>

                <p className="text-center text-sm text-muted-foreground mt-6">
                  14-day money-back guarantee • Cancel anytime
                </p>
              </div>
            </Card>
          </motion.div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="py-20 px-4 bg-muted/30">
        <div className="max-w-3xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl md:text-5xl font-bold mb-4">Frequently Asked Questions</h2>
            <p className="text-lg text-muted-foreground">
              Everything you need to know
            </p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5, delay: 0.2 }}
          >
            <Accordion type="single" collapsible className="space-y-4">
              {faqs.map((faq, index) => (
                <AccordionItem 
                  key={index} 
                  value={`item-${index}`}
                  className="bg-card border border-border rounded-lg px-6 data-[state=open]:border-primary/50 transition-colors"
                >
                  <AccordionTrigger className="text-left hover:no-underline py-5">
                    <span className="font-semibold text-foreground pr-4">
                      {faq.question}
                    </span>
                  </AccordionTrigger>
                  <AccordionContent className="text-muted-foreground leading-relaxed pb-5">
                    {faq.answer}
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </motion.div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-20 px-4">
        <div className="max-w-3xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
          >
            <h2 className="text-4xl md:text-5xl font-bold mb-6 text-balance">
              Ready to Level Up Your AI Game?
            </h2>
            <p className="text-xl text-muted-foreground mb-8 text-balance">
              Join 47 elite builders already inside. Only 53 spots remaining.
            </p>
            <Button
              size="lg"
              className="text-lg h-14 px-12 font-semibold"
              style={{
                background: 'linear-gradient(135deg, #AB47C7 0%, #43BFE3 100%)',
              }}
            >
              Claim Your Spot Now
            </Button>
          </motion.div>
        </div>
      </section>
    </div>
  )
}
