/**
 * v0-generated variant: Music Lab
 * Generated: 2026-02-08 via v0-1.5-lg with extended thinking
 * Chat: r9XYZI8P0Mv
 * Demo: https://demo-kzmnibzj21qauou5xlcm.vusercontent.net
 * 
 * This is a reference design generated by v0. Review and adopt
 * the best patterns into the production codebase.
 * DO NOT deploy directly — adapt to existing component patterns.
 */

'use client'

import { motion } from 'framer-motion'
import { Play, ArrowRight, Sparkles } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { useEffect, useState } from 'react'

const featuredTracks = [
  {
    id: 1,
    name: 'Neon Dreams',
    genre: 'Electronic',
    duration: '3:42',
    color: 'from-cyan-500 to-blue-500',
  },
  {
    id: 2,
    name: 'Midnight Echoes',
    genre: 'Ambient',
    duration: '4:18',
    color: 'from-purple-500 to-pink-500',
  },
  {
    id: 3,
    name: 'Urban Pulse',
    genre: 'Hip-Hop',
    duration: '2:56',
    color: 'from-amber-500 to-orange-500',
  },
  {
    id: 4,
    name: 'Starlight Jazz',
    genre: 'Jazz',
    duration: '5:23',
    color: 'from-emerald-500 to-teal-500',
  },
  {
    id: 5,
    name: 'Digital Symphony',
    genre: 'Orchestral',
    duration: '6:12',
    color: 'from-violet-500 to-purple-500',
  },
]

const genres = [
  {
    name: 'Electronic',
    tracks: 127,
    color: 'from-cyan-500/20 to-blue-500/20',
    accent: 'text-cyan-400',
    borderColor: 'border-cyan-500/30',
  },
  {
    name: 'Ambient',
    tracks: 89,
    color: 'from-purple-500/20 to-pink-500/20',
    accent: 'text-purple-400',
    borderColor: 'border-purple-500/30',
  },
  {
    name: 'Hip-Hop',
    tracks: 64,
    color: 'from-amber-500/20 to-orange-500/20',
    accent: 'text-amber-400',
    borderColor: 'border-amber-500/30',
  },
  {
    name: 'Jazz',
    tracks: 52,
    color: 'from-emerald-500/20 to-teal-500/20',
    accent: 'text-emerald-400',
    borderColor: 'border-emerald-500/30',
  },
  {
    name: 'Orchestral',
    tracks: 43,
    color: 'from-violet-500/20 to-purple-500/20',
    accent: 'text-violet-400',
    borderColor: 'border-violet-500/30',
  },
  {
    name: 'Experimental',
    tracks: 125,
    color: 'from-rose-500/20 to-pink-500/20',
    accent: 'text-rose-400',
    borderColor: 'border-rose-500/30',
  },
]

const latestReleases = [
  { name: 'Cosmic Journey', genre: 'Electronic', duration: '3:24' },
  { name: 'Silent Waves', genre: 'Ambient', duration: '4:56' },
  { name: 'Street Rhythm', genre: 'Hip-Hop', duration: '2:48' },
  { name: 'Blue Note', genre: 'Jazz', duration: '5:12' },
  { name: 'Epic Quest', genre: 'Orchestral', duration: '7:32' },
  { name: 'Glitch Garden', genre: 'Experimental', duration: '3:18' },
  { name: 'Lo-Fi Dreams', genre: 'Electronic', duration: '3:45' },
  { name: 'Morning Mist', genre: 'Ambient', duration: '4:20' },
]

function AnimatedCounter({ value, suffix = '' }: { value: number; suffix?: string }) {
  const [count, setCount] = useState(0)

  useEffect(() => {
    const duration = 2000
    const steps = 60
    const increment = value / steps
    let current = 0

    const timer = setInterval(() => {
      current += increment
      if (current >= value) {
        setCount(value)
        clearInterval(timer)
      } else {
        setCount(Math.floor(current))
      }
    }, duration / steps)

    return () => clearInterval(timer)
  }, [value])

  return (
    <span className="tabular-nums">
      {count}
      {suffix}
    </span>
  )
}

function Waveform({ className = '' }: { className?: string }) {
  return (
    <div className={`flex items-end gap-0.5 ${className}`}>
      {[...Array(40)].map((_, i) => (
        <motion.div
          key={i}
          className="w-0.5 bg-gradient-to-t from-amber-500 to-amber-300 rounded-full"
          animate={{
            height: [
              `${20 + Math.random() * 60}%`,
              `${20 + Math.random() * 60}%`,
              `${20 + Math.random() * 60}%`,
            ],
          }}
          transition={{
            duration: 1 + Math.random(),
            repeat: Number.POSITIVE_INFINITY,
            ease: 'easeInOut',
          }}
        />
      ))}
    </div>
  )
}

function EqualizerBars() {
  return (
    <div className="absolute inset-0 overflow-hidden opacity-5">
      <div className="absolute inset-0 flex items-end justify-around">
        {[...Array(50)].map((_, i) => (
          <motion.div
            key={i}
            className="w-2 bg-gradient-to-t from-amber-500 to-amber-300 rounded-t-full"
            animate={{
              height: [`${10 + Math.random() * 40}%`, `${10 + Math.random() * 40}%`],
            }}
            transition={{
              duration: 0.8 + Math.random() * 0.7,
              repeat: Number.POSITIVE_INFINITY,
              ease: 'easeInOut',
            }}
          />
        ))}
      </div>
    </div>
  )
}

export default function MusicLabPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* Hero Section */}
      <section className="relative min-h-[90vh] flex items-center justify-center overflow-hidden">
        <EqualizerBars />

        <div className="container mx-auto px-4 relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="text-center max-w-4xl mx-auto"
          >
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              transition={{ duration: 0.5 }}
              className="inline-block mb-6"
            >
              <Badge className="bg-amber-500/10 text-amber-400 border-amber-500/30 px-4 py-2 text-sm">
                <Sparkles className="w-4 h-4 mr-2 inline" />
                Powered by Suno AI
              </Badge>
            </motion.div>

            <h1 className="text-6xl md:text-8xl font-bold mb-6">
              <span className="bg-gradient-to-r from-amber-400 via-amber-300 to-amber-500 bg-clip-text text-transparent">
                Music Lab
              </span>
            </h1>

            <Waveform className="h-16 max-w-3xl mx-auto mb-8" />

            <p className="text-xl md:text-2xl text-muted-foreground mb-12 leading-relaxed">
              {'500+ AI-generated tracks. Exploring what\'s possible.'}
            </p>

            <Button
              size="lg"
              className="bg-amber-500 hover:bg-amber-600 text-slate-900 font-semibold px-8 py-6 text-lg"
            >
              Explore Tracks
              <ArrowRight className="ml-2 w-5 h-5" />
            </Button>
          </motion.div>
        </div>

        {/* Gradient Orbs */}
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-amber-500/10 rounded-full blur-3xl" />
        <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-purple-500/10 rounded-full blur-3xl" />
      </section>

      {/* Featured Tracks Section */}
      <section className="py-24 relative">
        <div className="container mx-auto px-4">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mb-12"
          >
            <h2 className="text-4xl md:text-5xl font-bold mb-4 text-balance">Featured Tracks</h2>
            <p className="text-muted-foreground text-lg">
              Hand-picked selections from the collection
            </p>
          </motion.div>

          <div className="relative">
            <div className="flex gap-6 overflow-x-auto pb-8 snap-x snap-mandatory scrollbar-hide">
              {featuredTracks.map((track, index) => (
                <motion.div
                  key={track.id}
                  initial={{ opacity: 0, x: 50 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: index * 0.1 }}
                  className="snap-start shrink-0"
                >
                  <Card className="w-80 bg-white/[0.03] backdrop-blur-xl border-white/10 hover:bg-white/[0.05] transition-all duration-300 hover:scale-105 hover:shadow-2xl hover:shadow-amber-500/20 group">
                    <div className="p-6">
                      {/* Gradient Background */}
                      <div
                        className={`h-48 rounded-lg bg-gradient-to-br ${track.color} mb-6 relative overflow-hidden`}
                      >
                        <div className="absolute inset-0 bg-black/20" />
                        <div className="absolute inset-0 flex items-center justify-center">
                          <Button
                            size="lg"
                            className="rounded-full w-16 h-16 bg-amber-500 hover:bg-amber-600 text-slate-900 shadow-2xl"
                          >
                            <Play className="w-6 h-6 ml-1" fill="currentColor" />
                          </Button>
                        </div>
                        {/* Mini Waveform */}
                        <div className="absolute bottom-4 left-4 right-4 opacity-60">
                          <Waveform className="h-8" />
                        </div>
                      </div>

                      <div className="space-y-3">
                        <h3 className="text-xl font-semibold">{track.name}</h3>
                        <div className="flex items-center justify-between">
                          <Badge
                            variant="outline"
                            className="border-amber-500/30 text-amber-400 bg-amber-500/5"
                          >
                            {track.genre}
                          </Badge>
                          <span className="text-sm text-muted-foreground">{track.duration}</span>
                        </div>
                      </div>
                    </div>
                  </Card>
                </motion.div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Genre Explorer Section */}
      <section className="py-24 relative">
        <div className="container mx-auto px-4">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mb-12 text-center"
          >
            <h2 className="text-4xl md:text-5xl font-bold mb-4 text-balance">Genre Explorer</h2>
            <p className="text-muted-foreground text-lg">Discover music across diverse styles</p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-6xl mx-auto">
            {genres.map((genre, index) => (
              <motion.div
                key={genre.name}
                initial={{ opacity: 0, scale: 0.9 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 }}
                whileHover={{ scale: 1.05 }}
              >
                <Card
                  className={`bg-white/[0.03] backdrop-blur-xl border ${genre.borderColor} hover:bg-white/[0.05] transition-all duration-300 hover:shadow-2xl group cursor-pointer overflow-hidden`}
                >
                  <div className={`absolute inset-0 bg-gradient-to-br ${genre.color} opacity-0 group-hover:opacity-100 transition-opacity duration-300`} />
                  <div className="p-8 relative z-10">
                    <h3 className={`text-3xl font-bold mb-2 ${genre.accent}`}>{genre.name}</h3>
                    <p className="text-4xl font-bold text-white/90">{genre.tracks}</p>
                    <p className="text-sm text-muted-foreground mt-1">tracks</p>
                  </div>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Production Stats Section */}
      <section className="py-24 relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-b from-amber-500/5 to-transparent" />

        <div className="container mx-auto px-4 relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center max-w-4xl mx-auto"
          >
            <h2 className="text-4xl md:text-5xl font-bold mb-16 text-balance">
              Production Stats
            </h2>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-16">
              <div className="text-center">
                <div className="text-6xl md:text-7xl font-bold text-amber-400 mb-2">
                  <AnimatedCounter value={500} suffix="+" />
                </div>
                <p className="text-lg text-muted-foreground">Tracks Created</p>
              </div>
              <div className="text-center">
                <div className="text-6xl md:text-7xl font-bold text-purple-400 mb-2">
                  <AnimatedCounter value={20} suffix="+" />
                </div>
                <p className="text-lg text-muted-foreground">Genres Explored</p>
              </div>
              <div className="text-center">
                <div className="text-6xl md:text-7xl font-bold text-cyan-400 mb-2">
                  <AnimatedCounter value={1000} suffix="+" />
                </div>
                <p className="text-lg text-muted-foreground">Prompts Tested</p>
              </div>
            </div>

            {/* Timeline */}
            <motion.div
              initial={{ opacity: 0, scale: 0.9 }}
              whileInView={{ opacity: 1, scale: 1 }}
              viewport={{ once: true }}
              className="mt-12"
            >
              <Card className="bg-white/[0.03] backdrop-blur-xl border-white/10 p-8">
                <h3 className="text-2xl font-semibold mb-6 text-amber-400">
                  Journey Timeline
                </h3>
                <div className="flex items-center justify-between gap-4">
                  <div className="text-center flex-1">
                    <div className="w-16 h-16 rounded-full bg-amber-500/20 border-2 border-amber-500 flex items-center justify-center mx-auto mb-2">
                      <span className="text-2xl font-bold text-amber-400">1</span>
                    </div>
                    <p className="text-sm text-muted-foreground">First Track</p>
                  </div>
                  <div className="flex-1 h-0.5 bg-gradient-to-r from-amber-500 to-purple-500" />
                  <div className="text-center flex-1">
                    <div className="w-16 h-16 rounded-full bg-purple-500/20 border-2 border-purple-500 flex items-center justify-center mx-auto mb-2">
                      <span className="text-2xl font-bold text-purple-400">250</span>
                    </div>
                    <p className="text-sm text-muted-foreground">Milestone</p>
                  </div>
                  <div className="flex-1 h-0.5 bg-gradient-to-r from-purple-500 to-cyan-500" />
                  <div className="text-center flex-1">
                    <div className="w-16 h-16 rounded-full bg-cyan-500/20 border-2 border-cyan-500 flex items-center justify-center mx-auto mb-2">
                      <span className="text-2xl font-bold text-cyan-400">500</span>
                    </div>
                    <p className="text-sm text-muted-foreground">Current</p>
                  </div>
                </div>
              </Card>
            </motion.div>
          </motion.div>
        </div>
      </section>

      {/* The Process Section */}
      <section className="py-24 relative">
        <div className="container mx-auto px-4">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mb-12 text-center"
          >
            <h2 className="text-4xl md:text-5xl font-bold mb-4 text-balance">The Process</h2>
            <p className="text-muted-foreground text-lg">
              From concept to completed composition
            </p>
          </motion.div>

          <div className="max-w-5xl mx-auto">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {[
                {
                  step: '01',
                  title: 'Prompt Design',
                  description:
                    'Crafting detailed prompts with genre, mood, instruments, and creative direction',
                  color: 'amber',
                },
                {
                  step: '02',
                  title: 'Generation',
                  description:
                    'Suno AI transforms prompts into full-length tracks with vocals and instrumentation',
                  color: 'purple',
                },
                {
                  step: '03',
                  title: 'Curation',
                  description:
                    'Selecting the best outputs and organizing them into a cohesive library',
                  color: 'cyan',
                },
              ].map((item, index) => (
                <motion.div
                  key={item.step}
                  initial={{ opacity: 0, y: 30 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: index * 0.2 }}
                  className="relative"
                >
                  <Card className="bg-white/[0.03] backdrop-blur-xl border-white/10 hover:bg-white/[0.05] transition-all duration-300 hover:scale-105 h-full">
                    <div className="p-8">
                      <div
                        className={`text-6xl font-bold mb-4 bg-gradient-to-br from-${item.color}-400 to-${item.color}-600 bg-clip-text text-transparent`}
                      >
                        {item.step}
                      </div>
                      <h3 className="text-2xl font-semibold mb-3">{item.title}</h3>
                      <p className="text-muted-foreground leading-relaxed">{item.description}</p>
                    </div>
                  </Card>
                  {index < 2 && (
                    <div className="hidden md:block absolute top-1/2 -right-3 z-20">
                      <ArrowRight className="w-6 h-6 text-muted-foreground" />
                    </div>
                  )}
                </motion.div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Prompt Library CTA Section */}
      <section className="py-24 relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-b from-transparent via-amber-500/5 to-transparent" />

        <div className="container mx-auto px-4 relative z-10">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            className="max-w-4xl mx-auto"
          >
            <Card className="bg-gradient-to-br from-amber-500/10 to-amber-600/5 backdrop-blur-xl border-amber-500/30 hover:border-amber-500/50 transition-all duration-300 overflow-hidden relative group">
              <div className="absolute inset-0 bg-gradient-to-br from-amber-500/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300" />

              <div className="p-12 relative z-10">
                <div className="flex items-start justify-between gap-8 flex-col md:flex-row">
                  <div className="flex-1">
                    <Badge className="bg-amber-500 text-slate-900 mb-4 px-3 py-1">
                      Premium Product
                    </Badge>
                    <h2 className="text-4xl md:text-5xl font-bold mb-4 text-balance">
                      <span className="bg-gradient-to-r from-amber-400 to-amber-600 bg-clip-text text-transparent">
                        Suno Prompt Library
                      </span>
                    </h2>
                    <p className="text-xl text-muted-foreground mb-6 leading-relaxed">
                      200+ production-grade prompts for AI music generation
                    </p>

                    <ul className="space-y-3 mb-8">
                      {[
                        'Genre-specific templates',
                        'Mood and atmosphere guides',
                        'Instrument combinations',
                        'Advanced prompt engineering',
                      ].map((feature) => (
                        <li key={feature} className="flex items-center gap-3">
                          <div className="w-6 h-6 rounded-full bg-amber-500/20 border border-amber-500/50 flex items-center justify-center shrink-0">
                            <div className="w-2 h-2 rounded-full bg-amber-400" />
                          </div>
                          <span className="text-foreground">{feature}</span>
                        </li>
                      ))}
                    </ul>

                    <div className="flex items-baseline gap-4 mb-6">
                      <div className="text-6xl font-bold text-amber-400">$47</div>
                      <div className="text-muted-foreground">one-time payment</div>
                    </div>

                    <Button
                      size="lg"
                      className="bg-amber-500 hover:bg-amber-600 text-slate-900 font-semibold px-8 py-6 text-lg shadow-2xl shadow-amber-500/20"
                    >
                      Get Instant Access
                      <ArrowRight className="ml-2 w-5 h-5" />
                    </Button>
                  </div>

                  <div className="hidden lg:block">
                    <div className="w-64 h-64 rounded-2xl bg-gradient-to-br from-amber-500 to-amber-600 p-1">
                      <div className="w-full h-full rounded-2xl bg-slate-900 flex items-center justify-center">
                        <Sparkles className="w-32 h-32 text-amber-400" />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </Card>
          </motion.div>
        </div>
      </section>

      {/* Latest Releases Section */}
      <section className="py-24 relative">
        <div className="container mx-auto px-4">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mb-12"
          >
            <h2 className="text-4xl md:text-5xl font-bold mb-4 text-balance">Latest Releases</h2>
            <p className="text-muted-foreground text-lg">Fresh from the studio</p>
          </motion.div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {latestReleases.map((track, index) => (
              <motion.div
                key={track.name}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.05 }}
              >
                <Card className="bg-white/[0.03] backdrop-blur-xl border-white/10 hover:bg-white/[0.05] transition-all duration-300 hover:scale-105 group cursor-pointer">
                  <div className="p-6">
                    {/* Album Art */}
                    <div className="aspect-square rounded-lg bg-gradient-to-br from-amber-500/20 to-purple-500/20 mb-4 relative overflow-hidden group-hover:from-amber-500/30 group-hover:to-purple-500/30 transition-all duration-300">
                      <div className="absolute inset-0 flex items-center justify-center">
                        <Button
                          size="sm"
                          className="rounded-full w-12 h-12 bg-amber-500 hover:bg-amber-600 text-slate-900 opacity-0 group-hover:opacity-100 transition-opacity duration-300 shadow-xl"
                        >
                          <Play className="w-4 h-4 ml-0.5" fill="currentColor" />
                        </Button>
                      </div>
                    </div>

                    <h3 className="font-semibold mb-2 truncate">{track.name}</h3>
                    <div className="flex items-center justify-between">
                      <span className="text-sm text-muted-foreground">{track.genre}</span>
                      <span className="text-xs text-muted-foreground">{track.duration}</span>
                    </div>
                  </div>
                </Card>
              </motion.div>
            ))}
          </div>

          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            className="text-center mt-12"
          >
            <Button
              variant="outline"
              size="lg"
              className="border-amber-500/30 text-amber-400 hover:bg-amber-500/10 bg-transparent"
            >
              View All Tracks
              <ArrowRight className="ml-2 w-4 h-4" />
            </Button>
          </motion.div>
        </div>
      </section>

      {/* Footer CTA */}
      <section className="py-24 relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-t from-amber-500/10 to-transparent" />

        <div className="container mx-auto px-4 relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center max-w-3xl mx-auto"
          >
            <h2 className="text-4xl md:text-6xl font-bold mb-6 text-balance">
              <span className="bg-gradient-to-r from-amber-400 via-purple-400 to-cyan-400 bg-clip-text text-transparent">
                The future of music creation is here
              </span>
            </h2>
            <p className="text-xl text-muted-foreground mb-8 leading-relaxed">
              Join me in exploring the boundaries of AI-powered music production
            </p>
            <Button
              size="lg"
              className="bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-600 hover:to-amber-700 text-slate-900 font-semibold px-8 py-6 text-lg shadow-2xl shadow-amber-500/20"
            >
              Start Your Journey
              <ArrowRight className="ml-2 w-5 h-5" />
            </Button>
          </motion.div>
        </div>
      </section>
    </div>
  )
}
