import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')

const banned = [
  ['app/links/page.tsx', ['10K+ Creators', '500+ AI Songs', '50+ proven templates', 'exclusive creator community']],
  ['app/showcase/page.tsx', ['500+ Suno', '500+ creators', 'Proven Results', 'WCAG 2.2 AAA', 'Sarah Chen']],
  ['app/linktree/page.tsx', ['12K+', '75+', '90+']],
  ['app/linktree/layout.tsx', ['12K+']],
  ['app/linktree/linktree-data.ts', ['75+', '65+', '50+ proven', '38 agents', '35+ commands']],
  ['app/about/layout.tsx', ['12K+', '12,000+']],
  ['app/about/page.tsx', ['12K+', '12,000+', '500+ tracks']],
  ['app/downloads/preview/vibe-os/page.tsx', ['12K+', '500+']],
  ['app/for/creators/layout.tsx', ['12K+', '50+ battle-tested']],
  ['app/for/creators/page.tsx', ['12K+', '70+ tutorials', '70+ Tutorials', '75+ AI Skills']],
  ['app/frankx/page.tsx', ['12K+', '12,000+']],
  ['app/lab/page.tsx', ['12K+', '12,000+', '8+ genres']],
  ['app/vibe/VibeOSContent.tsx', ['12K+', 'Suno sessions']],
  ['components/connect/ConnectHero.tsx', ['12K+']],
  ['components/MobileNavOverlay.tsx', ['12K+', '12,000+']],
  ['components/NavigationMega.tsx', ['12K+', '12,000+']],
  ['app/coaching/faqs.ts', ['12,000+']],
  ['app/coaching/page.tsx', ['12,000+']],
  ['app/creators/page.tsx', ['12,000+', '500+ AI Songs', 'AI Songs Created']],
  ['components/creators/CreatorsShell.tsx', ['12,000+', '500+ AI Songs', 'AI Songs Created']],
  ['app/developers/page.tsx', ['500+', 'AI-Generated Songs']],
  ['components/developers/DevelopersShell.tsx', ['500+', 'AI-Generated Songs']],
  ['app/music/create/layout.tsx', ['500+ tracks']],
  ['app/music/create/page.tsx', ['500+ tracks', '500+ generations']],
  ['app/music/layout.tsx', ['500+']],
  ['app/music/learn/orchestration/page.tsx', ['500+ tracks']],
  ['app/music/learn/production/page.tsx', ['12,000+']],
  ['app/music/learn/theory/page.tsx', ['12,000+']],
  ['app/music/page.tsx', ['published tracks on Suno', 'Public Tracks', 'totalTracks}+']],
  ['components/music/MusicShell.tsx', ['published tracks on Suno', 'Public Tracks', 'totalTracks}+']],
  ['app/music-os/page.tsx', ['indexed tracks', 'totalTracks']],
  ['app/magic/page.tsx', ['12,000 songs', 'over 12,000 songs']],
  ['components/magic/MagicShell.tsx', ['12,000 songs', 'over 12,000 songs']],
  ['app/products/vibe-os/components/VibeOSFinalCTA.tsx', ['12,000+']],
  ['app/products/vibe-os/components/VibeOSHero.tsx', ['500+ Sessions']],
  ['app/products/vibe-os/components/VibeOSSocialProof.tsx', ['500+ Sessions']],
  ['app/soul-frequency-assessment/page.tsx', ['500+ Suno']],
  ['app/team/page.tsx', ['12,000+', '50+ genres']],
  ['app/vibe/producer/page.tsx', ['500+', '12,000+']],
  ['app/year-of-the-fire-horse/vision/page.tsx', ['500+ AI-produced']],
  ['app/design-lab/frontend-design/page.tsx', ['12K+', '12,000+']],
  ['app/design-lab/nature/variants/homepage/page.tsx', ['12K+', '12,000+']],
  ['app/design-lab/strategy/page.tsx', ['12,000+']],
  ['app/bio/layout.tsx', ['12,000+', '12K+']],
  ['app/bio/page.tsx', ['12,000+', '12K+', '12,000 Songs']],
  ['app/achievements/page.tsx', ['12,000+', '12K+', '13K hooks']],
  ['app/api/send-pdf/route.ts', ['12,000+', '12K+']],
  ['app/llms.txt/route.ts', ['12,000+', '12K+']],
  ['app/llms-full.txt/route.ts', ['12,000+', '12K+']],
  ['app/media-kit/page.tsx', ['12,000+', '12K+']],
  ['app/frank-riemer/page.tsx', ['12,000+', '12K+']],
  ['app/(landing)/connect/page.tsx', ['12,000+', '12K+']],
  ['app/downloads/preview/soulbook/page.tsx', ['12,000+', '12K+']],
  ['app/free-playbook/layout.tsx', ['12,000+', '12K+']],
  ['app/free-playbook/page.tsx', ['12,000+', '12K+']],
  ['app/goals/page.tsx', ['12,000+', '12K+']],
  ['app/intelligence-map/page.tsx', ['12,000+', '12K+']],
  ['app/links/metadata.ts', ['12,000+', '12K+']],
  ['app/map/v3/page.tsx', ['12,000+', '12K+']],
  ['app/newsletter/thank-you/ThankYouContent.tsx', ['12,000+', '12K+']],
  ['app/path/aesthete/page.tsx', ['12,000+', '12K+']],
  ['app/rituals/layout.tsx', ['12,000+', '12K+']],
  ['app/rituals/page.tsx', ['12,000+', '12K+']],
  ['app/students/ai-briefing/page.tsx', ['12,000+', '12K+']],
  ['app/vision/VisionContent.tsx', ['12,000+', '12K+']],
  ['app/youtube/page.tsx', ['12,000+', '12K+']],
  ['components/about/AboutShell.tsx', ['12,000+', '12K+']],
  ['components/design-lab/CosmicForgeHero.tsx', ['12,000+', '12K+']],
  ['components/design-lab/GlassCathedralHero.tsx', ['12,000+', '12K+']],
  ['components/design-lab/NeonGridHero.tsx', ['12,000+', '12K+']],
  ['components/home/SignalRouteSelector.tsx', ['12,000+', '12K+']],
  ['components/intelligence-map/IntelligenceMapShell.tsx', ['12,000+', '12K+']],
  ['components/rituals/RitualsShell.tsx', ['12,000+', '12K+']],
  ['components/rituals/rituals-data.ts', ['12,000+', '12K+']],
  ['components/start/StartShell.tsx', ['12K+', '12,000+']],
  ['components/v0-variants/AIAcademyV0.tsx', ['12K+', '12,000+']],
  ['components/v0-variants/HomepageHeroV0.tsx', ['500+', '12,000+', '12K+']],
  ['components/v0-variants/MusicLabV0.tsx', ['500+']],
  ['components/youtube/YouTubeHubShell.tsx', ['12,000+', '12K+']],
  ['components/v0-variants/AboutPageV0.tsx', ['AI Songs']],
  ['components/golden-age/GoldenAgeShell.tsx', ['500+', 'AI Songs Created']],
  ['app/golden-age/page.tsx', ['500+', 'AI Songs Created']],
  ['lib/email-templates-premium.ts', ['12,000+', '12K+', '500+ AI Songs']],
  ['lib/email-templates-welcome.ts', ['12,000+', '12K+', '500+ AI']],
  ['lib/email-templates.ts', ['12,000+', '12K+']],
  ['lib/hub.ts', ['12,000+', '12K+']],
  ['lib/intake/personas.ts', ['12,000+', '12K+', '12k music catalog']],
  ['lib/visual-intelligence/platform-personas.ts', ['12,000+', '12K+', '12k music catalog']],
  ['lib/visual-intelligence/visual-stack.ts', ['12k catalog']],
  ['lib/gen/backends.ts', ['12k catalog']],
  ['lib/workshop-citations.ts', ['12,000+', '12K+']],
  ['lib/voice/frankx-voice.ts', ['12,000+', '12K+', '12,000+ AI songs', '12,000+ songs']],
  ['lib/plan/initiatives.ts', ['500+ AI songs', 'AI Songs Created']],
  ['lib/qualities.ts', ['12,000 Songs']],
  ['content/blog/suno-ai-12000-songs-production-lessons.mdx', ['12,000', '12K+', '65 tracks', '61 self-hosted', '61 catalog-quality', '61 tracks currently', '60+ tracks', 'six genre families', '12 cataloged', '12 neoclassical']],
]

for (const [file, phrases] of banned) {
  test(file + ' does not publish an unsupported headcount', () => {
    const text = fs.readFileSync(path.join(root, file), 'utf8').toLowerCase()
    for (const phrase of phrases) {
      assert.equal(text.includes(phrase.toLowerCase()), false, phrase)
    }
  })
}
