import type { BookMetadata, Chapter, Essay } from './types';

export const bookMetadata: BookMetadata = {
  title: 'The Golden Age of Creators',
  subtitle: 'The Democratization of Creative Capability and Distribution',
  author: 'Frank',
  publishDate: '2026',
  description: 'A transformative exploration of how the creator economy crossed $250 billion, how 45 million people now create professionally, and how the barriers to creative expression have evaporated like morning fog.',
  keywords: [
    'creator economy',
    'AI and creativity',
    'golden age of intelligence',
    'independent creators',
    'creative entrepreneurship',
    'agentic AI',
    'content creation',
    'digital transformation',
  ],
};

export const chapters: Chapter[] = [
  {
    slug: 'chapter-01-when-creation-calls',
    title: 'When Creation Calls',
    number: 1,
    readingTime: '18 min',
    description: 'The question beneath all questions: What am I here to create?',
    published: true,
  },
  {
    slug: 'chapter-02-the-orchestration-age',
    title: 'The Orchestration Age',
    number: 2,
    readingTime: '15 min',
    description: 'From using AI to conducting AI agents like an orchestra.',
    published: true,
  },
  {
    slug: 'chapter-03-the-first-gesture',
    title: 'The First Gesture',
    number: 3,
    readingTime: '14 min',
    description: 'Moving from theory to practice—the moment that transforms everything.',
    published: true,
  },
  {
    slug: 'chapter-04-the-architecture-of-flow',
    title: 'The Architecture of Flow',
    number: 4,
    readingTime: '16 min',
    description: 'Designing systems that support sustained creative output.',
    published: false,
  },
  {
    slug: 'chapter-05-the-voice-only-you-can-speak',
    title: 'The Voice Only You Can Speak',
    number: 5,
    readingTime: '17 min',
    description: 'Developing authentic creative voice in an age of AI generation.',
    published: false,
  },
  {
    slug: 'chapter-06-building-in-public',
    title: 'Building in Public',
    number: 6,
    readingTime: '15 min',
    description: 'Transparency, audience building, and iterative creation.',
    published: false,
  },
  {
    slug: 'chapter-07-the-economics-of-independence',
    title: 'The Economics of Independence',
    number: 7,
    readingTime: '18 min',
    description: 'Monetization, sustainability, and financial freedom through creation.',
    published: false,
  },
  {
    slug: 'chapter-08-the-compound-effect',
    title: 'The Compound Effect',
    number: 8,
    readingTime: '14 min',
    description: 'How consistent creation builds exponential results over time.',
    published: false,
  },
  {
    slug: 'chapter-09-leading-the-orchestra',
    title: 'Leading the Orchestra',
    number: 9,
    readingTime: '16 min',
    description: 'Advanced orchestration, team building, and scaling creative output.',
    published: false,
  },
  {
    slug: 'chapter-10-the-legacy-you-leave',
    title: 'The Legacy You Leave',
    number: 10,
    readingTime: '15 min',
    description: 'Creating work that endures and contributes to the larger creative conversation.',
    published: false,
  },
];

export const essays: Essay[] = [
  {
    slug: '08-golden-age-of-intelligence',
    title: 'The Golden Age of Intelligence',
    subtitle: 'Flagship Atlas for Agentic Marketing Teams',
    readingTime: '52 min',
    category: 'Flagship',
    description: 'A 15,000-word masterwork fusing SEO strategy, agentic operations, and automation.',
  },
  {
    slug: 'golden-age-field-guide',
    title: 'Golden Age Field Guide',
    subtitle: 'Principles and Rituals',
    readingTime: '5 min',
    category: 'Quick Reference',
    description: 'Navigate the Golden Age with clarity, momentum, and soul.',
  },
  {
    slug: 'reader-first-golden-age',
    title: 'Reader-First Growth Playbook',
    subtitle: 'Practical Implementation',
    readingTime: '14 min',
    category: 'Strategy',
    description: 'Translate the Golden Age narrative into content and distribution moves.',
  },
];
