// Generated by scripts/generate-frank-intelligence-corpus.mjs. Do not edit.
export const frankIntelligenceCorpusMeta = {"version":1,"fingerprint":"3c2cd8dcb30c2ec8","publishedPostCount":212,"publicRouteCount":640,"recordCount":3377} as const
