// Channel metadata - manually maintained (used by learning-paths.ts)
export const youtubeChannels = {
  anthropic: {
    name: 'Anthropic',
    url: 'https://www.youtube.com/@anthropic-ai',
  },
  netNinja: {
    name: 'Net Ninja',
    url: 'https://www.youtube.com/@NetNinja',
  },
  kevinStratvert: {
    name: 'Kevin Stratvert',
    url: 'https://www.youtube.com/@KevinStratvert',
  },
  lexFridman: {
    name: 'Lex Fridman',
    url: 'https://www.youtube.com/@lexfridman',
  },
  googleDeepMind: {
    name: 'Google DeepMind',
    url: 'https://www.youtube.com/@Google_DeepMind',
  },
  googleDevelopers: {
    name: 'Google for Developers',
    url: 'https://www.youtube.com/@GoogleDevelopers',
  },
  jeffSu: {
    name: 'Jeff Su',
    url: 'https://www.youtube.com/@JeffSu',
  },
  mattWolfe: {
    name: 'Matt Wolfe',
    url: 'https://www.youtube.com/@mreflow',
  },
  aiExplained: {
    name: 'AI Explained',
    url: 'https://www.youtube.com/@aiexplained-official',
  },
  theNeuron: {
    name: 'The Neuron',
    url: 'https://www.youtube.com/@TheNeuronDaily',
  },
} as const

// Auto-generated by scripts/generate-youtube-index.mjs
// Last updated: 2026-05-04T23:51:41.685Z

export interface YoutubeIndexEntry {
  slug: string
  title: string
  videoIds: string[]
  category: string
}

export const youtubeIndex: YoutubeIndexEntry[] = [
  {
    "slug": "ai-engineering-without-hype-willison",
    "title": "AI Engineering Without the Hype: Simon Willison's Practical Protocol",
    "videoIds": [
      "uRuLgar5XZw"
    ],
    "category": "Curated"
  },
  {
    "slug": "claude-code-mastery-top-resources",
    "title": "Claude Code Mastery: The Top 5 Resources of 2026",
    "videoIds": [
      "eTTMUWP5B0s"
    ],
    "category": "Curated"
  },
  {
    "slug": "karpathys-ai-vision-deep-dive",
    "title": "Karpathy's AI Vision: A Deep Dive",
    "videoIds": [
      "VMj-3S1tku0"
    ],
    "category": "Curated"
  },
  {
    "slug": "nvidia-gtc-2026-ai-architect-breakdown",
    "title": "NVIDIA GTC 2026: An AI Architect's Breakdown of Vera Rubin, Groq LPUs, and the Agentic Infrastructure Shift",
    "videoIds": [
      "jw_o0xr8MWU"
    ],
    "category": "Intelligence Dispatches"
  }
];
