// Channel metadata - manually maintained (used by learning-paths.ts)
export const youtubeChannels = {
  anthropic: {
    name: 'Anthropic',
    url: 'https://www.youtube.com/@anthropic-ai',
  },
  netNinja: {
    name: 'Net Ninja',
    url: 'https://www.youtube.com/@NetNinja',
  },
  kevinStratvert: {
    name: 'Kevin Stratvert',
    url: 'https://www.youtube.com/@KevinStratvert',
  },
  lexFridman: {
    name: 'Lex Fridman',
    url: 'https://www.youtube.com/@lexfridman',
  },
} as const

// Auto-generated by scripts/generate-youtube-index.mjs
// Last updated: 2026-02-19T17:03:34.403Z

export interface YoutubeIndexEntry {
  slug: string
  title: string
  videoIds: string[]
  category: string
}

export const youtubeIndex: YoutubeIndexEntry[] = [
  {
    "slug": "ai-engineering-without-hype-willison",
    "title": "AI Engineering Without the Hype: Simon Willison's Practical Protocol",
    "videoIds": [
      "uRuLgar5XZw"
    ],
    "category": "AI Architecture"
  },
  {
    "slug": "claude-code-mastery-top-resources",
    "title": "Claude Code Mastery: The Top 5 Resources of 2026",
    "videoIds": [
      "pOLR5jE5Vjw"
    ],
    "category": "AI Engineering"
  },
  {
    "slug": "karpathys-ai-vision-deep-dive",
    "title": "Karpathy's AI Vision: A Deep Dive",
    "videoIds": [
      "VMj-3S1tku0"
    ],
    "category": "AI Architecture"
  }
];

// YouTube channel references for learning paths
export const youtubeChannels = {
  anthropic: {
    name: 'Anthropic',
    url: 'https://www.youtube.com/@AnthropicAI'
  },
  netNinja: {
    name: 'Net Ninja',
    url: 'https://www.youtube.com/@NetNinja'
  },
  kevinStratvert: {
    name: 'Kevin Stratvert',
    url: 'https://www.youtube.com/@KevinStratvert'
  },
  lexFridman: {
    name: 'Lex Fridman',
    url: 'https://www.youtube.com/@LexFridman'
  }
};