// Channel metadata - manually maintained (used by learning-paths.ts)
export const youtubeChannels = {
  anthropic: {
    name: 'Anthropic',
    url: 'https://www.youtube.com/@anthropic-ai',
  },
  openai: {
    name: 'OpenAI',
    url: 'https://www.youtube.com/@OpenAI',
  },
  deepLearningAI: {
    name: 'DeepLearning.AI',
    url: 'https://www.youtube.com/@Deeplearningai',
  },
  freeCodeCamp: {
    name: 'freeCodeCamp.org',
    url: 'https://www.youtube.com/@freecodecamp',
  },
  examPro: {
    name: 'ExamPro',
    url: 'https://www.youtube.com/@ExamProChannel',
  },
  netNinja: {
    name: 'Net Ninja',
    url: 'https://www.youtube.com/@NetNinja',
  },
  kevinStratvert: {
    name: 'Kevin Stratvert',
    url: 'https://www.youtube.com/@KevinStratvert',
  },
  lexFridman: {
    name: 'Lex Fridman',
    url: 'https://www.youtube.com/@lexfridman',
  },
  googleDeepMind: {
    name: 'Google DeepMind',
    url: 'https://www.youtube.com/@Google_DeepMind',
  },
  googleDevelopers: {
    name: 'Google for Developers',
    url: 'https://www.youtube.com/@GoogleDevelopers',
  },
  aiExplained: {
    name: 'AI Explained',
    url: 'https://www.youtube.com/@aiexplained-official',
  },
  jeffSu: {
    name: 'Jeff Su',
    url: 'https://www.youtube.com/@JeffSu',
  },
  mattWolfe: {
    name: 'Matt Wolfe',
    url: 'https://www.youtube.com/@mreflow',
  },
  theNeuron: {
    name: 'The Neuron',
    url: 'https://www.youtube.com/@theneurondaily',
  },
  figma: {
    name: 'Figma',
    url: 'https://www.youtube.com/@Figma',
  },
  peterYang: {
    name: 'Peter Yang',
    url: 'https://www.youtube.com/@peteryangyt',
  },
  aiEngineer: {
    name: 'AI Engineer',
    url: 'https://www.youtube.com/@AIEngineer',
  },
  sequoia: {
    name: 'Sequoia Capital',
    url: 'https://www.youtube.com/@SequoiaCapital',
  },
  acquired: {
    name: 'Acquired',
    url: 'https://www.youtube.com/@AcquiredFM',
  },
} as const

// Auto-generated by scripts/generate-youtube-index.mjs
// Last updated: 2026-06-25T12:58:49.720Z

export interface YoutubeIndexEntry {
  slug: string
  title: string
  videoIds: string[]
  category: string
}

export const youtubeIndex: YoutubeIndexEntry[] = [
  {
    "slug": "ai-engineering-without-hype-willison",
    "title": "AI Engineering Without the Hype: Simon Willison's Practical Protocol",
    "videoIds": [
      "uRuLgar5XZw"
    ],
    "category": "Intelligence Dispatches"
  },
  {
    "slug": "claude-code-mastery-top-resources",
    "title": "Claude Code Mastery: The Top 5 Resources of 2026",
    "videoIds": [
      "eTTMUWP5B0s"
    ],
    "category": "Intelligence Dispatches"
  },
  {
    "slug": "karpathys-ai-vision-deep-dive",
    "title": "Karpathy's AI Vision: A Deep Dive",
    "videoIds": [
      "VMj-3S1tku0"
    ],
    "category": "Intelligence Dispatches"
  },
  {
    "slug": "nvidia-gtc-2026-ai-architect-breakdown",
    "title": "NVIDIA GTC 2026: An AI Architect's Breakdown of Vera Rubin, Groq LPUs, and the Agentic Infrastructure Shift",
    "videoIds": [
      "jw_o0xr8MWU"
    ],
    "category": "Intelligence Dispatches"
  }
];
