/**
 * Research Hub Source Registry
 *
 * Every research domain's claims are backed by verifiable sources.
 * Sources are keyed by domain slug for simple per-page rendering.
 *
 * @see lib/research/domains.ts for domain definitions
 */

export type SourceType =
  | 'industry-report'
  | 'journal'
  | 'blog'
  | 'official'
  | 'news'
  | 'benchmark'
  | 'preprint'

export interface ResearchSource {
  name: string
  title: string
  url: string
  date?: string
  type: SourceType
}

export const sourceTypeLabels: Record<SourceType, string> = {
  'industry-report': 'Industry Report',
  journal: 'Peer-Reviewed',
  blog: 'Blog / Analysis',
  official: 'Official Docs',
  news: 'News',
  benchmark: 'Benchmark',
  preprint: 'Preprint',
}

/**
 * Domain-keyed source registry.
 * Each domain slug maps to an array of validated sources.
 */
export const domainSources: Record<string, ResearchSource[]> = {
  'manifestation-law-of-attraction-ai-systems': [
    { name: 'Pascual-Leone et al.', title: 'Modulation of muscle responses evoked by TMS during mental practice (motor imagery)', url: 'https://pubmed.ncbi.nlm.nih.gov/7500130/', date: '1995', type: 'journal' },
    { name: 'Ranganathan et al.', title: 'From mental power to muscle power — gaining strength by using the mind', url: 'https://pubmed.ncbi.nlm.nih.gov/14998709/', date: '2004', type: 'journal' },
    { name: 'Corbetta & Shulman', title: 'Control of goal-directed and stimulus-driven attention in the brain', url: 'https://pubmed.ncbi.nlm.nih.gov/11994752/', date: '2002', type: 'journal' },
    { name: 'Russell', title: 'A circumplex model of affect (valence × arousal)', url: 'https://psycnet.apa.org/record/1981-25062-001', date: '1980', type: 'journal' },
    { name: 'Oettingen & Mayer', title: 'The motivating function of thinking about the future: positive fantasies vs. expectations', url: 'https://pubmed.ncbi.nlm.nih.gov/12416921/', date: '2002', type: 'journal' },
    { name: 'Locke & Latham', title: 'Building a practically useful theory of goal setting and task motivation', url: 'https://psycnet.apa.org/record/2002-15790-003', date: '2002', type: 'journal' },
    { name: 'Juslin & Västfjäll', title: 'Emotional responses to music: the need to consider underlying mechanisms', url: 'https://pubmed.ncbi.nlm.nih.gov/18926045/', date: '2008', type: 'journal' },
    { name: 'Karageorghis & Priest', title: 'Music in the exercise domain: a review and synthesis', url: 'https://pubmed.ncbi.nlm.nih.gov/23667771/', date: '2012', type: 'journal' },
    { name: 'Vibe OS', title: 'The Science of State Change — music psychology + frequency methodology', url: 'https://github.com/frankxai/vibe-os', type: 'official' },
  ],

  'agent-skills-operating-knowledge': [
    { name: 'Anthropic', title: 'Equipping agents for the real world with Agent Skills', url: 'https://www.anthropic.com/engineering/equipping-agents-for-the-real-world-with-agent-skills', date: '2025-10-16', type: 'official' },
    { name: 'Anthropic', title: 'Skills public repository', url: 'https://github.com/anthropics/skills', type: 'official' },
    { name: 'Claude Docs', title: 'Agent Skills overview', url: 'https://platform.claude.com/docs/en/agents-and-tools/agent-skills/overview', type: 'official' },
    { name: 'Claude Docs', title: 'Skill authoring best practices', url: 'https://platform.claude.com/docs/en/agents-and-tools/agent-skills/best-practices', type: 'official' },
    { name: 'Claude Docs', title: 'Skills for enterprise', url: 'https://platform.claude.com/docs/en/agents-and-tools/agent-skills/enterprise', type: 'official' },
    { name: 'Microsoft Learn', title: 'Establish an AI Center of Excellence', url: 'https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ai/center-of-excellence', date: '2026-04-10', type: 'official' },
    { name: 'AWS Prescriptive Guidance', title: 'Best practices for enterprise generative AI adoption and scaling', url: 'https://docs.aws.amazon.com/prescriptive-guidance/latest/strategy-enterprise-ready-gen-ai-platform/best-practices.html', type: 'official' },
    { name: 'IBM Think', title: 'What is an AI center of excellence?', url: 'https://www.ibm.com/think/topics/ai-center-of-excellence', date: '2026-06-05', type: 'official' },
  ],

  'enterprise-ai': [
    { name: 'MarketsAndMarkets', title: 'AI Agents Market Size — $7.84B to $52.62B by 2030', url: 'https://www.marketsandmarkets.com/Market-Reports/ai-agents-market-56997845.html', type: 'industry-report' },
    { name: 'Gartner', title: 'Predicts 40% of Enterprise Apps Will Feature AI Agents by 2026', url: 'https://www.gartner.com/en/newsroom/press-releases/2024-10-21-gartner-says-by-2028-33-percent-of-enterprise-software-applications-will-include-agentic-ai', type: 'industry-report' },
    { name: 'G2', title: 'Multi-Agent AI Adoption in Enterprise — 72% Report', url: 'https://www.g2.com/articles/ai-agents', type: 'industry-report' },
    { name: 'TechRepublic', title: 'AI Adoption Trends Enterprise 2026', url: 'https://www.techrepublic.com/article/ai-adoption-trends-enterprise/', type: 'news' },
    { name: 'Deloitte', title: 'AI Adoption Challenges and Trends', url: 'https://www.deloitte.com/us/en/what-we-do/capabilities/applied-artificial-intelligence/blogs/pulse-check-series-latest-ai-developments/ai-adoption-challenges-ai-trends.html', type: 'industry-report' },
    { name: 'Lucidworks', title: 'Enterprise AI Adoption in 2026: Trends, Gaps, and Strategic Insights', url: 'https://lucidworks.com/blog/enterprise-ai-adoption-in-2026-trends-gaps-and-strategic-insights', type: 'blog' },
    { name: 'CIO', title: '4 Critical Misconceptions Derailing Enterprise AI Adoption', url: 'https://www.cio.com/article/4116299/beyond-the-hype-4-critical-misconceptions-derailing-enterprise-ai-adoption.html', type: 'news' },
    { name: 'Redolent', title: 'Top 5 Enterprise AI Adoption Pitfalls in 2026', url: 'https://redolentech.com/top-5-enterprise-ai-adoption-pitfalls-in-2026/', type: 'blog' },
  ],

  'multi-agent-systems': [
    { name: 'LangChain', title: 'LangGraph Documentation — Multi-Agent Orchestration', url: 'https://python.langchain.com/docs/langgraph', type: 'official' },
    { name: 'CrewAI', title: 'CrewAI Documentation — Role-Based Agent Teams', url: 'https://docs.crewai.com', type: 'official' },
    { name: 'Microsoft', title: 'AutoGen / AG2 — Multi-Agent Framework', url: 'https://microsoft.github.io/autogen', type: 'official' },
    { name: 'G2', title: 'Multi-Agent AI Adoption Report — 72% Enterprise Adoption', url: 'https://www.g2.com/articles/ai-agents', type: 'industry-report' },
    { name: 'OpenAI', title: 'Agents SDK — Native GPT Agent Framework', url: 'https://openai.com/index/new-tools-for-building-agents/', type: 'official' },
    { name: 'IBM', title: 'What Is Agent2Agent (A2A) Protocol?', url: 'https://www.ibm.com/think/topics/agent2agent-protocol', type: 'official' },
    { name: 'Google Developers', title: 'Announcing the Agent2Agent Protocol (A2A) — A New Era of Agent Interoperability', url: 'https://developers.googleblog.com/en/a2a-a-new-era-of-agent-interoperability/', type: 'official' },
    { name: 'Deloitte', title: 'Unlocking Exponential Value with AI Agent Orchestration', url: 'https://www.deloitte.com/us/en/insights/industry/technology/technology-media-and-telecom-predictions/2026/ai-agent-orchestration.html', type: 'industry-report' },
    { name: 'arXiv', title: 'MAESTRO: Multi-Agent Evaluation Suite for Testing, Reliability, and Observability', url: 'https://arxiv.org/html/2601.00481v1', type: 'preprint' },
    { name: 'arXiv', title: 'Multi-Agent Risks from Advanced AI', url: 'https://arxiv.org/abs/2502.14143', type: 'preprint' },
    { name: 'World Economic Forum', title: 'Using AI Agents in Organizations Today and in the Future', url: 'https://www.weforum.org/stories/2025/12/ai-agents-onboarding-governance/', type: 'industry-report' },
  ],

  'production-patterns': [
    { name: 'Oracle', title: 'OCI Generative AI Capabilities', url: 'https://www.oracle.com/artificial-intelligence/generative-ai/', type: 'official' },
    { name: 'Oracle', title: 'OCI AI Agent Platform', url: 'https://www.oracle.com/artificial-intelligence/generative-ai/agents/', type: 'official' },
    { name: 'Oracle', title: 'GA of OCI Gen AI Agent Platform', url: 'https://blogs.oracle.com/ai-and-datascience/ga-of-oci-gen-ai-agent-platform', type: 'official' },
    { name: 'Oracle', title: 'OCI GenAI Agents Documentation', url: 'https://docs.oracle.com/en-us/iaas/Content/generative-ai-agents/overview.htm', type: 'official' },
    { name: 'Oracle', title: 'First Principles: OCI AI Agent Platform', url: 'https://blogs.oracle.com/cloud-infrastructure/first-principles-oci-ai-agent-platform', type: 'blog' },
    { name: 'AIMultiple', title: 'Oracle AI Agents Analysis', url: 'https://research.aimultiple.com/oracle-ai-agents/', type: 'blog' },
  ],

  'mcp-ecosystem': [
    { name: 'Anthropic', title: 'Claude 4 Introduction', url: 'https://www.anthropic.com/news/claude-4', type: 'official' },
    { name: 'Anthropic', title: 'Claude Opus 4.5 Announcement', url: 'https://www.anthropic.com/news/claude-opus-4-5', type: 'official' },
    { name: 'Claude', title: 'Claude Release Notes', url: 'https://support.claude.com/en/articles/12138966-release-notes', type: 'official' },
    { name: 'VentureBeat', title: 'Anthropic Launches Enterprise Agent Skills and Opens the Standard', url: 'https://venturebeat.com/technology/anthropic-launches-enterprise-agent-skills-and-opens-the-standard/', type: 'news' },
    { name: 'Fortune', title: 'Claude Code Viral Moment — Non-Coders Building Software', url: 'https://fortune.com/2026/01/24/anthropic-boris-cherny-claude-code-non-coders-software-engineers/', type: 'news' },
    { name: 'Anthropic', title: 'Agent Capabilities API', url: 'https://www.anthropic.com/news/agent-capabilities-api', type: 'official' },
    { name: 'Anthropic', title: 'MCP Connectors and Partners', url: 'https://www.anthropic.com/partners/mcp', type: 'official' },
    { name: 'Claude Code', title: 'Claude Code CHANGELOG', url: 'https://github.com/anthropics/claude-code/blob/main/CHANGELOG.md', type: 'official' },
    { name: 'Claude Code', title: 'Hooks Reference — Claude Code Docs', url: 'https://code.claude.com/docs/en/hooks', type: 'official' },
    { name: 'Claude Code', title: 'Skills Documentation — Claude Code Docs', url: 'https://code.claude.com/docs/en/skills', type: 'official' },
    { name: 'Anthropic', title: 'Advanced Tool Use Engineering', url: 'https://www.anthropic.com/engineering/advanced-tool-use', type: 'official' },
    { name: 'VentureBeat', title: 'Claude Code MCP Tool Search Feature', url: 'https://venturebeat.com/orchestration/claude-code-just-got-updated-with-one-of-the-most-requested-user-features', type: 'news' },
    { name: 'Zapier', title: 'MCP with Anthropic API Integration', url: 'https://zapier.com/blog/zapier-mcp-anthropic-api/', type: 'blog' },
  ],

  'ai-ops': [
    { name: 'Oracle', title: 'OCI Generative AI Capabilities', url: 'https://www.oracle.com/artificial-intelligence/generative-ai/', type: 'official' },
    { name: 'Oracle', title: 'OCI AI Agent Platform', url: 'https://www.oracle.com/artificial-intelligence/generative-ai/agents/', type: 'official' },
    { name: 'Oracle', title: 'OCI GenAI Agents Documentation', url: 'https://docs.oracle.com/en-us/iaas/Content/generative-ai-agents/overview.htm', type: 'official' },
    { name: 'AIMultiple', title: 'Oracle AI Agents Analysis', url: 'https://research.aimultiple.com/oracle-ai-agents/', type: 'blog' },
    { name: 'Databricks', title: 'LLMOps: Operationalizing Large Language Models', url: 'https://www.databricks.com/glossary/llmops', type: 'official' },
    { name: 'IBM', title: 'Observability Trends 2026', url: 'https://www.ibm.com/think/insights/observability-trends', type: 'industry-report' },
    { name: 'Grafana Labs', title: '2026 Observability Trends and Predictions', url: 'https://grafana.com/blog/2026-observability-trends-predictions-from-grafana-labs-unified-intelligent-and-open/', type: 'official' },
    { name: 'Braintrust', title: 'AI Observability Tools: Monitoring AI Agents in Production (2026)', url: 'https://www.braintrust.dev/articles/best-ai-observability-tools-2026', type: 'blog' },
    { name: 'Deloitte', title: 'The AI Infrastructure Reckoning: Optimizing Compute Strategy in the Age of Inference', url: 'https://www.deloitte.com/us/en/insights/topics/technology-management/tech-trends/2026/ai-infrastructure-compute-strategy.html', type: 'industry-report' },
    { name: 'Wiz', title: 'AI Compliance in 2026: Definition, Standards, and Frameworks', url: 'https://www.wiz.io/academy/ai-security/ai-compliance', type: 'official' },
    { name: 'DataCamp', title: 'Top 15 LLMOps Tools for Building AI Applications in 2026', url: 'https://www.datacamp.com/blog/llmops-tools', type: 'blog' },
  ],

  'ai-neuroscience': [
    { name: 'STAT News', title: 'BCI Technology Trends 2026', url: 'https://www.statnews.com/2025/12/26/brain-computer-interface-technology-trends-2026/', type: 'news' },
    { name: 'OpenAI', title: 'Investing in Merge Labs', url: 'https://openai.com/index/investing-in-merge-labs/', type: 'official' },
    { name: 'Neuralink', title: 'Neuralink Updates — PRIME Trial', url: 'https://neuralink.com/updates/', type: 'official' },
    { name: 'Financial Content', title: 'Neuromorphic Computing Goes Mainstream in 2026', url: 'https://www.financialcontent.com/article/tokenring-2026-1-21-the-brain-inspired-revolution-neuromorphic-computing-goes-mainstream-in-2026', type: 'news' },
    { name: 'Nature Neuroscience', title: 'Adaptive Intelligence', url: 'https://www.nature.com/articles/s41593-025-02169-w', type: 'journal' },
    { name: 'Nature', title: 'Mind-Captioning AI', url: 'https://www.nature.com/articles/d41586-025-03624-1', type: 'journal' },
    { name: 'UT Austin', title: 'Brain Activity Decoder Reveals Stories in People\'s Minds', url: 'https://news.utexas.edu/2023/05/01/brain-activity-decoder-can-reveal-stories-in-peoples-minds/', type: 'journal' },
    { name: 'Inside Precision Medicine', title: 'Decoding Inner Speech in Real-Time with AI and BCIs', url: 'https://www.insideprecisionmedicine.com/topics/informatics/decoding-inner-speech-in-real-time-with-ai-and-brain-computer-interfaces/', type: 'journal' },
    { name: 'Frontiers in Science', title: 'Organoid Intelligence', url: 'https://www.frontiersin.org/journals/science/articles/10.3389/fsci.2023.1017235/full', type: 'journal' },
    { name: 'RealClearScience', title: 'Growing Computers from Human Brain Cells', url: 'https://www.realclearscience.com/articles/2026/01/12/how_scientists_are_growing_computers_from_human_brain_cells_1158120.html', type: 'news' },
    { name: 'APA', title: 'Trends in Personalized Mental Health Care', url: 'https://www.apa.org/monitor/2026/01-02/trends-personalized-mental-health-care', type: 'journal' },
    { name: 'Science', title: 'Transforming Mental Health with AI', url: 'https://www.science.org/doi/10.1126/science.adz9193', type: 'journal' },
    { name: 'AI Frontiers', title: 'The Evidence for AI Consciousness Today', url: 'https://ai-frontiers.org/articles/the-evidence-for-ai-consciousness-today', type: 'blog' },
    { name: 'Frontiers in Science', title: 'Consciousness Science 2025', url: 'https://www.frontiersin.org/journals/science/articles/10.3389/fsci.2025.1546279/full', type: 'journal' },
    { name: 'Trends in Cognitive Sciences', title: 'Indicators of Consciousness in AI', url: 'https://www.cell.com/trends/cognitive-sciences/fulltext/S1364-6613(25)00286-4', type: 'journal' },
  ],

  'vector-databases': [
    { name: 'Ryz Labs', title: 'Pinecone vs Weaviate vs Qdrant — Best Vector Database for RAG 2026', url: 'https://learn.ryzlabs.com/rag-vector-search/pinecone-vs-weaviate-vs-qdrant-the-best-vector-database-for-rag-in-2026', type: 'blog' },
    { name: 'LiquidMetal AI', title: 'Vector Database Comparison', url: 'https://liquidmetal.ai/casesAndBlogs/vector-comparison/', type: 'blog' },
    { name: 'Xenoss', title: 'Vector Database Comparison: Pinecone, Qdrant, Weaviate', url: 'https://xenoss.io/blog/vector-database-comparison-pinecone-qdrant-weaviate', type: 'blog' },
    { name: 'DataCamp', title: 'Best Vector Databases 2026', url: 'https://www.datacamp.com/blog/the-top-5-vector-databases', type: 'blog' },
    { name: 'AIMultiple', title: 'Vector Database for RAG', url: 'https://research.aimultiple.com/vector-database-for-rag/', type: 'blog' },
  ],

  'ai-security': [
    { name: 'Microsoft Security', title: 'Four Priorities for AI-Powered Identity and Network Access Security in 2026', url: 'https://www.microsoft.com/en-us/security/blog/2026/01/20/four-priorities-for-ai-powered-identity-and-network-access-security-in-2026/', type: 'official' },
    { name: 'CyberArk', title: 'AI Agents and Identity Risks — How Security Will Shift in 2026', url: 'https://www.cyberark.com/resources/blog/ai-agents-and-identity-risks-how-security-will-shift-in-2026', type: 'blog' },
    { name: 'HelpNetSecurity', title: 'F5 AI Guardrails Red Team', url: 'https://www.helpnetsecurity.com/2026/01/15/f5-ai-guardrails-red-team/', type: 'news' },
    { name: 'StateTech', title: 'AI Guardrails Will Stop Being Optional in 2026', url: 'https://statetechmagazine.com/article/2026/01/ai-guardrails-will-stop-being-optional-2026', type: 'news' },
    { name: 'Guardrails AI', title: 'Guardrails AI — Open-Source AI Safety Platform', url: 'https://www.guardrailsai.com/', type: 'official' },
    { name: 'Dark Reading', title: 'Coders Adopt AI Agents, Security Pitfalls Lurk in 2026', url: 'https://www.darkreading.com/application-security/coders-adopt-ai-agents-security-pitfalls-lurk-2026', type: 'news' },
  ],

  'coding-assistants': [
    { name: 'Nucamp', title: 'Top 10 Vibe Coding Tools in 2026', url: 'https://www.nucamp.co/blog/top-10-vibe-coding-tools-in-2026-cursor-copilot-claude-code-more', type: 'blog' },
    { name: 'Seedium', title: 'AI Coding Assistants Comparison', url: 'https://seedium.io/blog/comparison-of-best-ai-coding-assistants/', type: 'blog' },
    { name: 'Faros AI', title: 'Best AI Coding Agents 2026', url: 'https://www.faros.ai/blog/best-ai-coding-agents-2026', type: 'blog' },
    { name: 'PlayCode', title: 'Best AI Coding Assistants 2026', url: 'https://playcode.io/blog/best-ai-coding-assistants-2026', type: 'blog' },
    { name: 'Pragmatic Coders', title: 'AI Developer Tools', url: 'https://www.pragmaticcoders.com/resources/ai-developer-tools', type: 'blog' },
  ],

  'ai-adoption': [
    { name: 'TechRepublic', title: 'AI Adoption Trends Enterprise 2026', url: 'https://www.techrepublic.com/article/ai-adoption-trends-enterprise/', type: 'news' },
    { name: 'Deloitte', title: 'AI Adoption Challenges and Trends', url: 'https://www.deloitte.com/us/en/what-we-do/capabilities/applied-artificial-intelligence/blogs/pulse-check-series-latest-ai-developments/ai-adoption-challenges-ai-trends.html', type: 'industry-report' },
    { name: 'Lucidworks', title: 'Enterprise AI Adoption in 2026: Trends, Gaps, Strategic Insights', url: 'https://lucidworks.com/blog/enterprise-ai-adoption-in-2026-trends-gaps-and-strategic-insights', type: 'blog' },
    { name: 'CIO', title: '4 Critical Misconceptions Derailing Enterprise AI', url: 'https://www.cio.com/article/4116299/beyond-the-hype-4-critical-misconceptions-derailing-enterprise-ai-adoption.html', type: 'news' },
    { name: 'Redolent', title: 'Top 5 Enterprise AI Adoption Pitfalls in 2026', url: 'https://redolentech.com/top-5-enterprise-ai-adoption-pitfalls-in-2026/', type: 'blog' },
  ],

  'agent-benchmarks': [
    { name: 'AI Native Dev', title: '8 Benchmarks Shaping the Next Generation of AI Agents', url: 'https://ainativedev.io/news/8-benchmarks-shaping-the-next-generation-of-ai-agents', type: 'blog' },
    { name: 'Epoch AI', title: 'SWE-bench Verified Leaderboard', url: 'https://epoch.ai/benchmarks/swe-bench-verified', type: 'benchmark' },
    { name: 'Sierra', title: 'τ-Bench — Benchmarking AI Agents', url: 'https://sierra.ai/blog/benchmarking-ai-agents', type: 'benchmark' },
    { name: 'Evidently AI', title: 'AI Agent Benchmarks Overview', url: 'https://www.evidentlyai.com/blog/ai-agent-benchmarks', type: 'blog' },
    { name: 'Scale AI', title: 'SWE-bench Pro Public Leaderboard', url: 'https://scale.com/leaderboard/swe_bench_pro_public', type: 'benchmark' },
    { name: 'OpenAI', title: 'Introducing SWE-bench Verified', url: 'https://openai.com/index/introducing-swe-bench-verified/', type: 'official' },
  ],

  'ai-mental-health': [
    { name: 'APA', title: 'Trends in Personalized Mental Health Care', url: 'https://www.apa.org/monitor/2026/01-02/trends-personalized-mental-health-care', type: 'journal' },
    { name: 'Science', title: 'Transforming Mental Health with AI', url: 'https://www.science.org/doi/10.1126/science.adz9193', type: 'journal' },
    { name: 'JMIR Publications', title: 'AI-Driven Chatbots for Mental Health Support: Mixed Methods Study', url: 'https://www.jmir.org/2025/1/e67114', type: 'journal' },
    { name: 'Nature Communications Medicine', title: 'Increasing Engagement with CBT Using Generative AI: Randomized Controlled Trial', url: 'https://www.nature.com/articles/s43856-025-01321-8', type: 'journal' },
    { name: 'PMC', title: 'AI-Powered CBT Chatbots: A Systematic Review', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11904749/', type: 'journal' },
    { name: 'Brown University', title: 'AI Chatbots Systematically Violate Mental Health Ethics Standards', url: 'https://www.brown.edu/news/2025-10-21/ai-mental-health-ethics', type: 'news' },
    { name: 'Stanford HAI', title: 'Exploring the Dangers of AI in Mental Health Care', url: 'https://hai.stanford.edu/news/exploring-the-dangers-of-ai-in-mental-health-care', type: 'blog' },
    { name: 'UK Parliament POST', title: 'AI and Mental Healthcare — Ethical and Regulatory Considerations', url: 'https://post.parliament.uk/research-briefings/post-pn-0738/', type: 'official' },
    { name: 'Toward Healthcare', title: 'U.S. Digital Mental Health Market to Grow at 20.25% CAGR till 2035', url: 'https://www.towardshealthcare.com/insights/us-digital-mental-health-market-sizing', type: 'industry-report' },
    { name: 'American Hospital Association', title: '3 Ways AI Could Aid Behavioral Health Screenings', url: 'https://www.aha.org/2025-04-15-3-ways-ai-could-aid-behavioral-health-screenings', type: 'industry-report' },
  ],

  'generative-ai': [
    { name: 'Anthropic', title: 'Claude 4 Introduction', url: 'https://www.anthropic.com/news/claude-4', type: 'official' },
    { name: 'Anthropic', title: 'Claude Opus 4.5 Announcement', url: 'https://www.anthropic.com/news/claude-opus-4-5', type: 'official' },
    { name: 'Claude', title: 'Claude Release Notes', url: 'https://support.claude.com/en/articles/12138966-release-notes', type: 'official' },
    { name: 'GlobalGPT', title: 'Claude AI Plans 2026', url: 'https://www.glbgpt.com/hub/claude-ai-plans-2026/', type: 'blog' },
    { name: 'LM Council', title: 'AI Model Benchmarks Feb 2026 — GPT-5, Claude 4.5, Gemini 2.5, Grok 4', url: 'https://lmcouncil.ai/benchmarks', type: 'benchmark' },
    { name: 'Vellum AI', title: 'Flagship Model Report: GPT-5.1 vs Gemini 3 Pro vs Claude Opus 4.5', url: 'https://www.vellum.ai/blog/flagship-model-report', type: 'industry-report' },
    { name: 'Stanford HAI', title: 'Technical Performance — The 2025 AI Index Report', url: 'https://hai.stanford.edu/ai-index/2025-ai-index-report/technical-performance', type: 'industry-report' },
    { name: 'Hugging Face', title: 'Best Open-Source LLMs 2025: Llama 4, Qwen 3, DeepSeek R1', url: 'https://huggingface.co/blog/daya-shankar/open-source-llms', type: 'official' },
    { name: 'Red Hat', title: 'The State of Open Source AI Models in 2025', url: 'https://developers.redhat.com/articles/2026/01/07/state-open-source-ai-models-2025', type: 'industry-report' },
    { name: 'Epoch AI', title: 'Can AI Scaling Continue Through 2030?', url: 'https://epoch.ai/blog/can-ai-scaling-continue-through-2030', type: 'industry-report' },
  ],

  'ai-agent-config': [
    { name: 'Claude Code', title: 'CLAUDE.md Configuration — Claude Code Docs', url: 'https://code.claude.com/docs/en/claude-md', type: 'official' },
    { name: 'Claude Code', title: 'Skills Documentation', url: 'https://code.claude.com/docs/en/skills', type: 'official' },
    { name: 'Claude Code', title: 'Hooks Reference', url: 'https://code.claude.com/docs/en/hooks', type: 'official' },
    { name: 'FrankX', title: 'ACOS — Agentic Creator Operating System', url: 'https://frankx.ai/products/agentic-creator-os', type: 'official' },
    { name: 'Builder.io', title: 'The Complete Guide to CLAUDE.md', url: 'https://www.builder.io/blog/claude-md-guide', type: 'blog' },
    { name: 'HumanLayer', title: 'Writing a Good CLAUDE.md', url: 'https://www.humanlayer.dev/blog/writing-a-good-claude-md', type: 'blog' },
    { name: 'Anthropic', title: 'Model Context Protocol Specification', url: 'https://modelcontextprotocol.io/specification/2025-11-25', type: 'official' },
    { name: 'GitHub', title: 'Model Context Protocol Servers', url: 'https://github.com/modelcontextprotocol/servers', type: 'official' },
    { name: 'Composio', title: 'Tool Calling Explained: The Core of AI Agents (2026 Guide)', url: 'https://composio.dev/blog/ai-agent-tool-calling-guide', type: 'blog' },
    { name: 'OpenAI', title: 'Function Calling — OpenAI API', url: 'https://platform.openai.com/docs/guides/function-calling', type: 'official' },
  ],

  'prompt-engineering': [
    { name: 'Anthropic', title: 'Prompt Caching — Up to 90% Cost Reduction', url: 'https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching', type: 'official' },
    { name: 'Anthropic', title: 'Extended Thinking and Adaptive Reasoning', url: 'https://docs.anthropic.com/en/docs/build-with-claude/extended-thinking', type: 'official' },
    { name: 'Anthropic', title: 'Claude API Pricing', url: 'https://www.anthropic.com/pricing', type: 'official' },
    { name: 'Anthropic', title: 'Prompt Engineering Overview — Claude API Docs', url: 'https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview', type: 'official' },
    { name: 'OpenAI', title: 'Prompt Engineering Guide', url: 'https://platform.openai.com/docs/guides/prompt-engineering', type: 'official' },
    { name: 'DAIR.AI', title: 'Prompt Engineering Guide', url: 'https://www.promptingguide.ai/', type: 'blog' },
    { name: 'arXiv', title: 'The Prompt Report: A Systematic Survey of Prompt Engineering Techniques', url: 'https://arxiv.org/abs/2406.06608', type: 'preprint' },
    { name: 'OWASP', title: 'LLM Prompt Injection Prevention Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/LLM_Prompt_Injection_Prevention_Cheat_Sheet.html', type: 'official' },
    { name: 'IBM', title: 'The 2026 Guide to Prompt Engineering', url: 'https://www.ibm.com/think/prompt-engineering', type: 'industry-report' },
    { name: 'Microsoft', title: 'How Microsoft Defends Against Indirect Prompt Injection Attacks', url: 'https://www.microsoft.com/en-us/msrc/blog/2025/07/how-microsoft-defends-against-indirect-prompt-injection-attacks', type: 'blog' },
  ],

  'context-engineering': [
    { name: 'Andrej Karpathy', title: 'Context Engineering — original framing on X', url: 'https://x.com/karpathy/status/1937902205765607626', date: '2025-06-25', type: 'blog' },
    { name: 'Anthropic', title: 'Effective Context Engineering for AI Agents', url: 'https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents', date: '2025-09-29', type: 'official' },
    { name: 'Anthropic', title: 'Claude Code Skills — Progressive Disclosure of Capabilities', url: 'https://docs.claude.com/en/docs/claude-code/skills', date: '2025-10-15', type: 'official' },
    { name: 'Anthropic', title: 'Model Context Protocol — Open Standard for AI Tool Integration', url: 'https://modelcontextprotocol.io/introduction', date: '2025-11-25', type: 'official' },
    { name: 'arXiv / TACL', title: 'Lost in the Middle: How Language Models Use Long Contexts (Liu et al.)', url: 'https://arxiv.org/abs/2307.03172', date: '2024-07', type: 'journal' },
    { name: 'arXiv', title: 'RULER: What\'s the Real Context Size of Your Long-Context Language Models? (Hsieh et al.)', url: 'https://arxiv.org/abs/2404.06654', date: '2024-08', type: 'benchmark' },
    { name: 'Bojie Li (AWS re:Invent 2025 synthesis)', title: 'Claude\'s Context Engineering Secrets — Best Practices Learned from Anthropic', url: 'https://01.me/en/2025/12/context-engineering-from-claude/', date: '2025-12-20', type: 'blog' },
    { name: 'InfoQ', title: 'Anthropic Introduces Managed Agents to Simplify AI Agent Deployment (Kumili)', url: 'https://www.infoq.com/news/2026/04/anthropic-managed-agents/', date: '2026-04-21', type: 'news' },
    { name: 'arXiv / ICLR 2026', title: 'Agentic Context Engineering: Evolving Contexts for Self-Improving Language Models (Zhang et al.)', url: 'https://arxiv.org/abs/2510.04618', date: '2026-03-29', type: 'preprint' },
    { name: 'arXiv', title: 'Structured Context Engineering for File-Native Agentic Systems (McMillan)', url: 'https://arxiv.org/abs/2602.05447', date: '2026-02-12', type: 'preprint' },
  ],

  'agent-evaluation': [
    { name: 'arXiv', title: 'AppWorld: A Controllable World of Apps and People for Benchmarking Interactive Coding Agents (Trivedi et al.)', url: 'https://arxiv.org/abs/2407.18901', date: '2024-07', type: 'preprint' },
    { name: 'arXiv / ICLR 2024', title: 'SWE-bench: Can Language Models Resolve Real-World GitHub Issues? (Jimenez et al.)', url: 'https://arxiv.org/abs/2310.06770', date: '2024-01', type: 'benchmark' },
    { name: 'arXiv', title: 'AMA-Bench: Evaluating Long-Horizon Memory for Agentic Applications (Zhao et al.)', url: 'https://arxiv.org/abs/2602.22769', date: '2026-03-04', type: 'preprint' },
    { name: 'arXiv', title: 'RULER: What\'s the Real Context Size of Your Long-Context Language Models? (Hsieh et al.)', url: 'https://arxiv.org/abs/2404.06654', date: '2024-08', type: 'benchmark' },
    { name: 'Anthropic', title: 'Effective Context Engineering for AI Agents — failures are test cases you haven\'t written yet', url: 'https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents', date: '2025-09-29', type: 'official' },
    { name: 'arXiv / ICLR 2026', title: 'Agentic Context Engineering: Evolving Contexts for Self-Improving Language Models (Zhang et al.)', url: 'https://arxiv.org/abs/2510.04618', date: '2026-03-29', type: 'preprint' },
    { name: 'Anthropic Engineering', title: 'Managed Agents — sessions and trace capture as first-class primitives (Martin/Cemaj/Cohen)', url: 'https://www.anthropic.com/engineering/managed-agents', date: '2026-04-08', type: 'official' },
    { name: 'Langfuse', title: 'LLM Observability for Agent Trajectories — Traces, Scores, and Evaluations', url: 'https://langfuse.com/docs/tracing', date: '2026-01', type: 'official' },
  ],

  'ai-education': [
    { name: 'UNESCO', title: 'Two-Thirds of Higher Education Institutions Developing AI Guidance', url: 'https://www.unesco.org/en/articles/unesco-survey-two-thirds-higher-education-institutions-have-or-are-developing-guidance-ai-use', type: 'official' },
    { name: 'Inside Higher Ed', title: '5 Predictions on How AI Will Shape Higher Ed in 2026', url: 'https://www.insidehighered.com/news/tech-innovation/artificial-intelligence/2026/01/05/5-predictions-how-ai-will-shape-higher-ed', type: 'news' },
    { name: 'Programs.com', title: 'New Data: 92% of Students Use AI', url: 'https://programs.com/resources/students-using-ai/', type: 'industry-report' },
    { name: 'Springer Nature', title: 'AI-Based Personalised Learning in Education: Systematic Literature Review', url: 'https://link.springer.com/article/10.1007/s44163-025-00598-x', type: 'journal' },
    { name: 'Brookings Institution', title: 'What the Research Shows About Generative AI in Tutoring', url: 'https://www.brookings.edu/articles/what-the-research-shows-about-generative-ai-in-tutoring/', type: 'industry-report' },
    { name: 'OECD', title: 'OECD Digital Education Outlook 2026', url: 'https://www.oecd.org/en/publications/oecd-digital-education-outlook-2026_062a7394-en.html', type: 'official' },
    { name: 'New America', title: 'Digital Literacy in the Age of AI: Voices from the Field', url: 'https://www.newamerica.org/education-policy/briefs/foundational-skills-digital-literacy-in-the-age-of-ai-analysis-and-voices-from-the-field/', type: 'industry-report' },
    { name: 'Precedence Research', title: 'AI in Education Market Size to Surge USD 112.30 Bn by 2034', url: 'https://www.precedenceresearch.com/ai-in-education-market', type: 'industry-report' },
    { name: 'MarketsAndMarkets', title: 'AI in Education Market Size — Global Industry Forecast', url: 'https://www.marketsandmarkets.com/Market-Reports/ai-in-education-market-200371366.html', type: 'industry-report' },
    { name: 'Faculty Focus', title: 'Designing the 2026 Classroom: Emerging Learning Trends in AI-Powered Education', url: 'https://www.facultyfocus.com/articles/teaching-with-technology-articles/designing-the-2026-classroom-emerging-learning-trends-in-an-ai-powered-education-system/', type: 'blog' },
  ],
  'ai-creative-tools': [
    { name: 'Adobe', title: 'Innovation and Authenticity — Adobe 2026 Creative Trends Forecast', url: 'https://business.adobe.com/resources/creative-trends-report.html', type: 'industry-report' },
    { name: 'Envato', title: 'Beyond Adoption: The State of AI in Creative Work 2026', url: 'https://elements.envato.com/learn/ai-trend-report', type: 'industry-report' },
    { name: 'Grand View Research', title: 'Generative AI in Content Creation Market Size Report, 2030', url: 'https://www.grandviewresearch.com/industry-analysis/generative-ai-content-creation-market-report', type: 'industry-report' },
    { name: 'Market.us', title: 'AI in Art and Creativity Market Size — CAGR of 25.8%', url: 'https://market.us/report/ai-in-art-and-creativity-market/', type: 'industry-report' },
    { name: 'Soundverse', title: 'How Suno AI Compares to Other Music Generation Tools in 2026', url: 'https://www.soundverse.ai/blog/article/how-sunos-ai-compares-to-other-music-generation-tools-1323', type: 'blog' },
    { name: 'Superprompt', title: 'Best AI Music Generators in 2026: Suno vs Udio vs AIVA Compared', url: 'https://superprompt.com/blog/best-ai-music-generators', type: 'blog' },
    { name: 'InVideo', title: 'Kling vs Sora vs Veo vs Runway: The AI Video Reality Check', url: 'https://invideo.io/blog/kling-vs-sora-vs-veo-vs-runway/', type: 'blog' },
    { name: 'Zapier', title: 'The 6 Best AI Writing Generators in 2026', url: 'https://zapier.com/blog/best-ai-writing-generator/', type: 'blog' },
    { name: 'Gradually.ai', title: 'The 9 Best AI Image Generation Models in 2026', url: 'https://www.gradually.ai/en/ai-image-models/', type: 'blog' },
  ],
  'ai-personal-productivity': [
    { name: 'McKinsey', title: 'Superagency in the Workplace: Empowering People to Unlock AI\'s Full Potential', url: 'https://www.mckinsey.com/capabilities/tech-and-ai/our-insights/superagency-in-the-workplace-empowering-people-to-unlock-ais-full-potential-at-work', type: 'industry-report' },
    { name: 'Deloitte', title: 'The State of AI in the Enterprise — 2026 AI Report', url: 'https://www.deloitte.com/us/en/what-we-do/capabilities/applied-artificial-intelligence/content/state-of-ai-in-the-enterprise.html', type: 'industry-report' },
    { name: 'Andreessen Horowitz', title: 'State of Consumer AI 2025: Product Hits, Misses, and What\'s Next', url: 'https://a16z.com/state-of-consumer-ai-2025-product-hits-misses-and-whats-next/', type: 'industry-report' },
    { name: 'Stack Overflow', title: 'AI — 2025 Stack Overflow Developer Survey', url: 'https://survey.stackoverflow.co/2025/ai', type: 'benchmark' },
    { name: 'Lenny\'s Newsletter', title: 'AI Tools Are Overdelivering: Results from Our Large-Scale AI Productivity Survey', url: 'https://www.lennysnewsletter.com/p/ai-tools-are-overdelivering-results', type: 'blog' },
    { name: 'First Page Sage', title: 'ChatGPT Usage Statistics: February 2026', url: 'https://firstpagesage.com/seo-blog/chatgpt-usage-statistics/', type: 'blog' },
    { name: 'GPTrends', title: 'AI Chatbot Usage Statistics mid-2025: ChatGPT, Gemini, Claude, Perplexity & DeepSeek', url: 'https://gptrends.io/blog/mid-2025-ai-chatbot-scorecard/', type: 'blog' },
    { name: 'Master of Code', title: 'AI Workflow Automation: Boost Productivity by 4.8x — 2026 Guide', url: 'https://masterofcode.com/blog/ai-workflow-automation', type: 'blog' },
    { name: 'Index.dev', title: 'Top 100 Developer Productivity Statistics with AI Tools 2026', url: 'https://www.index.dev/blog/developer-productivity-statistics-with-ai-tools', type: 'blog' },
  ],
  'ai-healthcare': [
    { name: 'MDPI Applied Sciences', title: 'Artificial Intelligence in Medical Diagnostics: Foundations, Clinical Applications, and Future Directions', url: 'https://www.mdpi.com/2076-3417/16/2/728', type: 'journal' },
    { name: 'Ardigen', title: 'AI in Biotech: Lessons from 2025 and Trends Shaping Drug Discovery in 2026', url: 'https://ardigen.com/ai-in-biotech-lessons-from-2025-and-the-trends-shaping-drug-discovery-in-2026/', type: 'industry-report' },
    { name: 'ScienceDirect', title: 'Leading AI-Driven Drug Discovery Platforms: 2025 Landscape and Global Outlook', url: 'https://www.sciencedirect.com/science/article/abs/pii/S0031699725075118', type: 'journal' },
    { name: 'Applied Clinical Trials', title: 'Clinical Trials in 2026: Platformization, AI Fluency, and the Value Chain', url: 'https://www.appliedclinicaltrialsonline.com/view/clinical-trials-2026-platformization-ai-fluency-value-chain', type: 'industry-report' },
    { name: 'American Hospital Association', title: 'How AI Is Transforming Clinical Trials', url: 'https://www.aha.org/aha-center-health-innovation-market-scan/2025-10-21-how-ai-transforming-clinical-trials', type: 'industry-report' },
    { name: 'MarketsAndMarkets', title: 'AI in Healthcare Market Worth $110.61 Billion by 2030', url: 'https://www.marketsandmarkets.com/PressReleases/artificial-intelligence-healthcare.asp', type: 'industry-report' },
    { name: 'Fortune Business Insights', title: 'AI in Healthcare Market Size and Growth Report [2026-2034]', url: 'https://www.fortunebusinessinsights.com/industry-reports/artificial-intelligence-in-healthcare-market-100534', type: 'industry-report' },
    { name: 'PMC', title: 'Smart Healthcare at Home: AI-Enabled Wearables and Diagnostics Review', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC12526596/', type: 'journal' },
    { name: 'STAT News', title: 'FDA Announces Sweeping Changes to Oversight of Wearables, AI-Enabled Devices', url: 'https://www.statnews.com/2026/01/06/fda-pulls-back-oversight-ai-enabled-devices-wearables/', type: 'news' },
    { name: 'European Commission', title: 'Artificial Intelligence in Healthcare — Public Health', url: 'https://health.ec.europa.eu/ehealth-digital-health-and-care/artificial-intelligence-healthcare_en', type: 'official' },
    { name: 'ScienceDirect', title: 'The EU Artificial Intelligence Act (2024): Implications for Healthcare', url: 'https://www.sciencedirect.com/science/article/pii/S0168851024001623', type: 'journal' },
  ],
  'creator-economy-ai': [
    { name: 'GlobeNewswire', title: 'AI in Creator Economy Global Market Report 2025-2029 and 2034', url: 'https://www.globenewswire.com/news-release/2026/01/07/3214698/28124/en/Artificial-Intelligence-in-Creator-Economy-Global-Market-Report-2025-2029-and-2034-Opportunities-in-Influencer-Collaborations-Audience-Engagement-Analytics-Generative-AI-Content-Pr.html', type: 'industry-report' },
    { name: 'GlobeNewswire', title: 'Creator Monetization Optimization AI Research Report — $5.46B Market', url: 'https://www.globenewswire.com/news-release/2026/01/29/3228461/28124/en/Creator-Monetization-Optimization-Artificial-Intelligence-AI-Research-Report-2025-5-46-Bn-Market-Opportunities-Trends-Competitive-Analysis-Strategies-and-Forecasts-2019-2024-2024-2.html', type: 'industry-report' },
    { name: 'Precedence Research', title: 'Creator Economy Market Size to Hit USD 2084.57 Billion by 2035', url: 'https://www.precedenceresearch.com/creator-economy-market', type: 'industry-report' },
    { name: 'eMarketer', title: 'FAQ on the Creator Economy: How Marketers Can Stand Out in 2026', url: 'https://www.emarketer.com/content/faq-on-creator-economy--how-marketers-stand-2026-', type: 'industry-report' },
    { name: 'The Wrap', title: 'More Than 1 Million YouTube Channels Used AI Tools in December', url: 'https://www.thewrap.com/industry-news/tech/youtube-2026-goals-ai-monetization-neal-mohan-letter/', type: 'news' },
    { name: 'TechCrunch', title: 'YouTube Will Soon Let Creators Make Shorts with Their Own AI Likeness', url: 'https://techcrunch.com/2026/01/21/youtube-will-soon-let-creators-make-shorts-with-their-own-ai-likeness/', type: 'news' },
    { name: 'PrometAI', title: 'The Rise of the Solopreneur Tech Stack in 2026', url: 'https://prometai.app/blog/solopreneur-tech-stack-2026', type: 'blog' },
    { name: 'Silicon India', title: 'How AI Tools Are Letting Solo Founders Build Empires in 2026', url: 'https://www.siliconindia.com/news/startups/how-ai-tools-are-letting-solo-founders-build-empires-in-2026-nid-238909-cid-19.html', type: 'news' },
    { name: 'Google', title: 'How Google and the C2PA Are Increasing Transparency for Gen AI Content', url: 'https://blog.google/innovation-and-ai/products/google-gen-ai-content-transparency-c2pa/', type: 'official' },
    { name: 'AIM Research', title: 'Content Authenticity: Tools and Use Cases in 2026', url: 'https://research.aimultiple.com/content-authenticity/', type: 'blog' },
  ],
  'investment-intelligence': [
    { name: 'Thomson Reuters', title: 'AI in Due Diligence — Reducing Document Review Time', url: 'https://www.thomsonreuters.com/en/artificial-intelligence.html', type: 'industry-report' },
    { name: 'Anthropic', title: 'Financial Services Case Study — AI Productivity Gains', url: 'https://www.anthropic.com/customers', type: 'industry-report' },
    { name: 'PitchBook', title: 'n8n Valuation and Series C Funding Data', url: 'https://pitchbook.com/profiles/n8n-io-b3e7a6b5-7f48-4d6d-bd22-7097dd67b59d', type: 'industry-report' },
    { name: 'Bain & Company', title: 'M&A Professionals Using Generative AI in Transactions', url: 'https://www.bain.com/insights/m-and-a-report/', type: 'industry-report' },
    { name: 'Morgan Stanley', title: 'AI-Native Software Development Economics', url: 'https://www.morganstanley.com/ideas/ai-software-development', type: 'industry-report' },
    { name: 'Anthropic', title: 'MCP Connectors — Financial Data Platform Integrations', url: 'https://www.anthropic.com/partners/mcp', type: 'official' },
    { name: 'n8n', title: 'n8n Workflow Automation Platform', url: 'https://n8n.io', type: 'official' },
    { name: 'LSEG', title: 'Data & Analytics Solutions for Financial Professionals', url: 'https://www.lseg.com/en/data-analytics', type: 'official' },
  ],
  'agentic-game-development': [
    { name: 'Jenova AI', title: 'AI Game Generator Market Size — $1.94B to $32.48B by 2035', url: 'https://www.jenovaai.com/blog/ai-game-generator-market', type: 'industry-report' },
    { name: 'Google', title: 'Games Developer Report — AI Agent Adoption', url: 'https://developers.google.com/games', type: 'industry-report' },
    { name: 'ByteIota', title: 'WebGPU vs WebGL Performance Benchmarks', url: 'https://byteiota.com/webgpu-vs-webgl/', type: 'benchmark' },
    { name: 'Elsner Technologies', title: 'AI in Game Development — 70% Faster Development', url: 'https://www.elsner.com/blog/ai-in-game-development/', type: 'blog' },
    { name: 'Phaser', title: 'Official Next.js Integration Template', url: 'https://phaser.io/news/2024/02/phaser-nextjs-template', type: 'official' },
    { name: 'Scenario', title: 'AI Game Asset Generation Platform', url: 'https://www.scenario.com', type: 'official' },
    { name: 'Inworld AI', title: 'AI NPC Character Engine', url: 'https://inworld.ai', type: 'official' },
    { name: 'AIVA', title: 'AI Music Composition for Games', url: 'https://www.aiva.ai', type: 'official' },
  ],
  'voice-tech-2026': [
    // Microsoft VibeVoice
    { name: 'arXiv', title: 'VibeVoice Technical Report (Peng et al., arXiv:2508.19205)', url: 'https://arxiv.org/abs/2508.19205', date: '2025-08-26', type: 'preprint' },
    { name: 'Microsoft / GitHub', title: 'VibeVoice — Open-Source Frontier Voice AI', url: 'https://github.com/microsoft/VibeVoice', type: 'official' },
    { name: 'Microsoft Research', title: 'VibeVoice Project Page', url: 'https://microsoft.github.io/VibeVoice/', type: 'official' },
    { name: 'Hugging Face', title: 'microsoft/VibeVoice-1.5B Model Card', url: 'https://huggingface.co/microsoft/VibeVoice-1.5B', type: 'official' },
    { name: 'Hugging Face', title: 'microsoft/VibeVoice-Realtime-0.5B Model Card', url: 'https://huggingface.co/microsoft/VibeVoice-Realtime-0.5B', type: 'official' },
    // NVIDIA Riva + Parakeet
    { name: 'Hugging Face / NVIDIA', title: 'Parakeet RNNT 1.1B Model Card — 1.6% WER LibriSpeech-clean', url: 'https://huggingface.co/nvidia/parakeet-rnnt-1.1b', type: 'official' },
    { name: 'Hugging Face / NVIDIA', title: 'Parakeet TDT 0.6B v3 Model Card', url: 'https://huggingface.co/nvidia/parakeet-tdt-0.6b-v3', type: 'official' },
    { name: 'NVIDIA', title: 'Riva — Real-Time Speech AI Developer Page', url: 'https://developer.nvidia.com/riva', type: 'official' },
    { name: 'Hugging Face', title: 'Open ASR Leaderboard — Multilingual + Long-Form Speech Recognition', url: 'https://huggingface.co/spaces/hf-audio/open_asr_leaderboard', type: 'benchmark' },
    { name: 'arXiv', title: 'Open ASR Leaderboard: Towards Reproducible and Transparent Speech Recognition Evaluation', url: 'https://arxiv.org/html/2510.06961v1', type: 'preprint' },
    // ElevenLabs
    { name: 'ElevenLabs', title: 'Eleven v3 — Most Expressive AI Voice Model', url: 'https://elevenlabs.io/v3', type: 'official' },
    { name: 'ElevenLabs (X)', title: 'Eleven v3 (alpha) Launch Announcement', url: 'https://x.com/elevenlabsio/status/1930689774278570003', date: '2025-06-05', type: 'news' },
    { name: 'Audio Generation Plugin', title: 'ElevenLabs Eleven v3 Alpha — Complete Guide to Audio Tags', url: 'https://audio-generation-plugin.com/elevenlabs-v3/', type: 'blog' },
    { name: 'ElevenLabs', title: 'Text-to-Speech API Reference (Turbo v2.5 + Multilingual)', url: 'https://elevenlabs.io/docs/api-reference/text-to-speech', type: 'official' },
    { name: 'ElevenLabs', title: 'Safety, Consent, and Watermarking Policy', url: 'https://elevenlabs.io/safety', type: 'official' },
    // OpenAI Realtime
    { name: 'OpenAI', title: 'Realtime API Guide — Speech-to-Speech with Function Calling', url: 'https://platform.openai.com/docs/guides/realtime', type: 'official' },
    { name: 'OpenAI', title: 'Introducing gpt-realtime and Realtime API Updates for Production Voice Agents', url: 'https://openai.com/index/introducing-gpt-realtime/', type: 'official' },
    { name: 'OpenAI', title: 'API Pricing — Realtime Audio Tokens ($32/$64 per 1M)', url: 'https://openai.com/api/pricing/', type: 'official' },
    // Cartesia
    { name: 'Cartesia', title: 'Sonic — Sub-100ms Streaming TTS Product Page', url: 'https://cartesia.ai/sonic', type: 'official' },
    { name: 'Cartesia', title: 'Cartesia API Documentation — Streaming + Voice Cloning', url: 'https://docs.cartesia.ai/', type: 'official' },
    { name: 'Cartesia', title: 'Older TTS Models — Sonic-2 and Predecessors', url: 'https://docs.cartesia.ai/build-with-cartesia/tts-models/older-models', type: 'official' },
    // Deepgram
    { name: 'BusinessWire / Deepgram', title: 'Deepgram Unveils Aura-2 — Enterprise-Grade Text-to-Speech', url: 'https://www.businesswire.com/news/home/20250415446781/en/Deepgram-Unveils-Aura-2-The-Worlds-Most-Professional-Cost-Effective-and-Enterprise-Grade-Text-to-Speech-Model', date: '2025-04-15', type: 'news' },
    { name: 'Deepgram', title: 'Deepgram Pricing — Aura-2 ($0.030/1k chars) + Nova-3 ($0.0077/min)', url: 'https://deepgram.com/pricing', type: 'official' },
    { name: 'PricingSaaS', title: 'Deepgram Launches Voice Agent API and Doubles Aura-2 Capacity', url: 'https://pricingsaas.com/news/deepgram/20251118/', type: 'news' },
    { name: 'Deepgram', title: 'Aura-2 TTS Models Documentation', url: 'https://developers.deepgram.com/docs/tts-models', type: 'official' },
    { name: 'Deepgram', title: 'Nova-3 ASR Models + Languages Overview', url: 'https://developers.deepgram.com/docs/models-languages-overview', type: 'official' },
    // Independent benchmarks
    { name: 'Async', title: 'Streaming TTS Latency vs Quality Benchmark — Async vs ElevenLabs vs Cartesia', url: 'https://async.com/blog/tts-latency-vs-quality-benchmark/', type: 'benchmark' },
    { name: 'Smallest.ai', title: 'TTS Benchmark 2025 — Smallest.ai vs Cartesia (Real-World TTFB 156-163ms)', url: 'https://smallest.ai/blog/tts-benchmark-2025-smallestai-vs-cartesia-report', type: 'benchmark' },
    { name: 'CloudX (DEV)', title: 'Cracking the Sub-1-Second Voice Loop — 30+ Stack Benchmarks', url: 'https://dev.to/cloudx/cracking-the-1-second-voice-loop-what-we-learned-after-30-stack-benchmarks-427', type: 'benchmark' },
    { name: 'Hugging Face', title: 'TTS Arena — Community-Voted Naturalness Rankings', url: 'https://huggingface.co/spaces/TTS-AGI/TTS-Arena', type: 'benchmark' },
    { name: 'PodcastVideos', title: 'Streaming TTS Latency-Quality Comparison 2025', url: 'https://www.podcastvideos.com/articles/streaming-tts-benchmark-latency-quality-comparison/', type: 'benchmark' },
    // Regulation / context
    { name: 'EU AI Act', title: 'Artificial Intelligence Act — Voice Cloning + Provenance Provisions', url: 'https://artificialintelligenceact.eu/', type: 'official' },
  ],

  'sovereign-ai-compute': [
    { name: 'OpenAI', title: 'Introducing Stargate UAE', url: 'https://openai.com/index/introducing-stargate-uae/', date: '2025-05-22', type: 'official' },
    { name: 'G42', title: 'Global Tech Alliance Launches Stargate UAE', url: 'https://www.g42.ai/resources/news/global-tech-alliance-launches-stargate-uae', date: '2025-05-22', type: 'official' },
    { name: 'PR Newswire / G42', title: 'G42 Provides Update on Construction of Stargate UAE AI Infrastructure Cluster', url: 'https://www.prnewswire.com/news-releases/g42-provides-update-on-construction-of-stargate-uae-ai-infrastructure-cluster-302586430.html', date: '2026-Q1', type: 'official' },
    { name: 'OpenAI', title: 'Announcing The Stargate Project', url: 'https://openai.com/index/announcing-the-stargate-project/', date: '2025-01-21', type: 'official' },
    { name: 'OpenAI', title: 'OpenAI, Oracle, and SoftBank expand Stargate with five new AI data center sites', url: 'https://openai.com/index/five-new-stargate-sites/', date: '2025-09-24', type: 'official' },
    { name: 'NVIDIA Newsroom', title: 'HUMAIN and NVIDIA Announce Strategic Partnership to Build AI Factories of the Future in Saudi Arabia', url: 'https://nvidianews.nvidia.com/news/humain-and-nvidia-announce-strategic-partnership-to-build-ai-factories-of-the-future-in-saudi-arabia', date: '2025-05-13', type: 'official' },
    { name: 'DCD', title: 'Saudi Arabian AI venture Humain buys 18,000 Nvidia GB300 chips, several hundred thousand more on the way', url: 'https://www.datacenterdynamics.com/en/news/saudi-arabian-ai-venture-humain-buys-18000-nvidia-gb300-chips-several-hundred-thousand-more-on-the-way/', date: '2025-08', type: 'news' },
    { name: 'CNBC', title: 'Saudi AI firm Humain is pouring billions into data centers. Will it pay off?', url: 'https://www.cnbc.com/2025/08/27/saudi-arabia-wants-to-be-worlds-third-largest-ai-provider-humain.html', date: '2025-08-27', type: 'news' },
    { name: 'CNBC', title: 'Mistral secures $830 million in debt financing to fund AI data center', url: 'https://www.cnbc.com/2026/03/30/mistral-ai-paris-data-center-cluster-debt-financing.html', date: '2026-03-30', type: 'news' },
    { name: 'DCD', title: 'Mistral AI raises $830m in debt financing for data center in Paris, France', url: 'https://www.datacenterdynamics.com/en/news/mistral-ai-raises-830m-in-debt-financing-for-data-center-in-paris-france/', date: '2026-03', type: 'news' },
    { name: 'DCD', title: 'MGX, Bpifrance, Nvidia, and Mistral AI plan 1.4GW Paris data center campus', url: 'https://www.datacenterdynamics.com/en/news/mgx-bpifrance-nvidia-and-mistral-ai-plan-14gw-paris-data-center-campus/', date: '2026-06', type: 'news' },
    { name: 'European Commission', title: 'AI Gigafactories', url: 'https://commission.europa.eu/topics/competitiveness/competitiveness-coordination-tool-projects/ai-gigafactories_en', date: '2026', type: 'official' },
    { name: 'European Commission', title: 'AI Factories — Shaping Europe\'s digital future', url: 'https://digital-strategy.ec.europa.eu/en/policies/ai-factories', date: '2026', type: 'official' },
    { name: 'Light Reading', title: 'EU defers formal call for AI gigafactories to early 2026', url: 'https://www.lightreading.com/ai-machine-learning/eu-defers-formal-call-for-ai-gigafactories-to-early-2026', date: '2025-Q4', type: 'news' },
    { name: 'IndiaAI', title: 'IndiaAI Compute Capacity', url: 'https://indiaai.gov.in/hub/indiaai-compute-capacity', date: '2026', type: 'official' },
    { name: 'NVIDIA Blog', title: 'India Fuels Its AI Mission With NVIDIA', url: 'https://blogs.nvidia.com/blog/india-ai-mission-infrastructure-models/', date: '2026-Q1', type: 'official' },
    { name: 'BusinessToday', title: 'India\'s AI dream runs on a stack it does not control', url: 'https://www.businesstoday.in/technology/artificial-intelligence/story/indias-ai-dream-runs-on-a-stack-it-does-not-control-537716-2026-06-18', date: '2026-06-18', type: 'news' },
    { name: 'NVIDIA Newsroom', title: 'NVIDIA Powers World\'s Largest Quantum Research Supercomputer (ABCI-Q)', url: 'https://nvidianews.nvidia.com/news/nvidia-powers-worlds-largest-quantum-research-supercomputer', date: '2026-03', type: 'official' },
    { name: 'NVIDIA Blog', title: 'Japan Enhances AI Sovereignty With ABCI 3.0 Supercomputer', url: 'https://blogs.nvidia.com/blog/abci-aist/', date: '2025', type: 'official' },
    { name: 'GOV.UK', title: 'AI Opportunities Action Plan: One Year On', url: 'https://www.gov.uk/government/publications/ai-opportunities-action-plan-one-year-on/ai-opportunities-action-plan-one-year-on', date: '2026-01', type: 'official' },
    { name: 'GOV.UK', title: 'AI Growth Zones', url: 'https://www.gov.uk/government/collections/ai-growth-zones', date: '2026', type: 'official' },
    { name: 'U.S. Department of Commerce BIS', title: 'Department of Commerce Announces Rescission of Biden-Era AI Diffusion Rule', url: 'https://www.bis.gov/press-release/department-commerce-announces-rescission-biden-era-artificial-intelligence-diffusion-rule-strengthens', date: '2025-05-13', type: 'official' },
    { name: 'Federal Register', title: 'Framework for Artificial Intelligence Diffusion', url: 'https://www.federalregister.gov/documents/2025/01/15/2025-00636/framework-for-artificial-intelligence-diffusion', date: '2025-01-15', type: 'official' },
    { name: 'SemiAnalysis', title: 'Huawei Ascend Production Ramp: Die Banks, TSMC Continued Production, HBM is The Bottleneck', url: 'https://newsletter.semianalysis.com/p/huawei-ascend-production-ramp', date: '2026', type: 'industry-report' },
    { name: 'Tom\'s Hardware', title: 'Huawei\'s Ascend and Kunpeng progress shows how China is rebuilding an AI compute stack under sanctions', url: 'https://www.tomshardware.com/tech-industry/semiconductors/huaweis-ascend-and-kunpeng-progress-shows-how-china-is-rebuilding-an-ai-compute-stack-under-sanctions', date: '2026', type: 'news' },
    { name: 'CNAS', title: 'Sovereign AI Index', url: 'https://interactives.cnas.org/reports/sovereign-ai-index/', date: '2026-01', type: 'industry-report' },
    { name: 'World Economic Forum / Bain', title: 'Rethinking AI Sovereignty: Pathways to Competitiveness through Strategic Investments', url: 'https://www3.weforum.org/docs/WEF_Rethinking_AI_Sovereignty_Pathways_to_Competitiveness_through_Strategic_Investments_2026.pdf', date: '2026-01', type: 'industry-report' },
    { name: 'McKinsey', title: 'Sovereign AI: Building ecosystems for strategic resilience and impact', url: 'https://www.mckinsey.com/industries/technology-media-and-telecommunications/our-insights/sovereign-ai-building-ecosystems-for-strategic-resilience-and-impact', date: '2025', type: 'industry-report' },
    { name: 'NVIDIA Blog', title: 'NVIDIA CEO: Every Country Needs Sovereign AI (World Governments Summit, Dubai)', url: 'https://blogs.nvidia.com/blog/world-governments-summit/', date: '2024-02-12', type: 'official' },
    { name: 'VentureBeat', title: 'Get ready for the age of sovereign AI — Jensen Huang interview', url: 'https://venturebeat.com/ai/get-ready-for-the-age-of-sovereign-ai-jensen-huang-interview', date: '2024', type: 'news' },
    { name: 'European Commission', title: 'EU AI Act — Regulatory framework for AI', url: 'https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai', date: '2026-08-02', type: 'official' },
  ],

  'ai-chips-silicon': [
    { name: 'NVIDIA', title: 'GB200 NVL72 product page', url: 'https://www.nvidia.com/en-us/data-center/gb200-nvl72/', date: '2025', type: 'official' },
    { name: 'NVIDIA / Primeline', title: 'Blackwell B200 Datasheet (PDF)', url: 'https://www.primeline-solutions.com/media/categories/server/nach-gpu/nvidia-hgx-h200/nvidia-blackwell-b200-datasheet.pdf', date: '2024', type: 'official' },
    { name: 'NVIDIA Newsroom', title: 'NVIDIA Vera Rubin Opens Agentic AI Frontier', url: 'https://nvidianews.nvidia.com/news/nvidia-vera-rubin-platform', date: '2026-03', type: 'official' },
    { name: 'NVIDIA', title: 'NVIDIA Blackwell Delivers Massive Performance Leaps in MLPerf Inference v5.0', url: 'https://developer.nvidia.com/blog/nvidia-blackwell-delivers-massive-performance-leaps-in-mlperf-inference-v5-0/', date: '2025', type: 'benchmark' },
    { name: 'HPCwire', title: 'MLPerf Inference v5.1 Results Land With New Benchmarks and Record Participation', url: 'https://www.hpcwire.com/2025/09/10/mlperf-inference-v5-1-results-land-with-new-benchmarks-and-record-participation/', date: '2025-09-10', type: 'benchmark' },
    { name: 'AMD', title: 'Instinct MI350 Series and Beyond: Accelerating the Future of AI and HPC', url: 'https://www.amd.com/en/blogs/2025/amd-instinct-mi350-series-and-beyond-accelerating-the-future-of-ai-and-hpc.html', date: '2025', type: 'official' },
    { name: 'SemiAnalysis', title: 'AMD Advancing AI: MI350X and MI400 UALoE72, MI500 UAL256', url: 'https://newsletter.semianalysis.com/p/amd-advancing-ai-mi350x-and-mi400-ualoe72-mi500-ual256', date: '2025', type: 'industry-report' },
    { name: 'Tom\'s Hardware', title: 'Intel cancels Falcon Shores GPU for AI workloads — Jaguar Shores to be successor', url: 'https://www.tomshardware.com/tech-industry/artificial-intelligence/intel-cancels-falcon-shores-gpu-for-ai-workloads-jaguar-shores-to-be-successor', date: '2025-01-31', type: 'news' },
    { name: 'Intel', title: 'Gaudi 3 AI Accelerator White Paper', url: 'https://cdrdv2-public.intel.com/817486/gaudi-3-ai-accelerator-white-paper.pdf', date: '2024', type: 'official' },
    { name: 'SemiAnalysis', title: 'Google TPUv7: The 900lb Gorilla In the Room', url: 'https://newsletter.semianalysis.com/p/tpuv7-google-takes-a-swing-at-the', date: '2025', type: 'industry-report' },
    { name: 'Google', title: 'Ironwood: The first Google TPU for the age of inference', url: 'https://blog.google/products/google-cloud/ironwood-tpu-age-of-inference/', date: '2025', type: 'official' },
    { name: 'Google Cloud', title: 'TPU7x (Ironwood) Documentation', url: 'https://docs.cloud.google.com/tpu/docs/tpu7x', date: '2025', type: 'official' },
    { name: 'SemiAnalysis', title: 'Amazon\'s AI Resurgence: AWS & Anthropic\'s Multi-Gigawatt Trainium Expansion', url: 'https://newsletter.semianalysis.com/p/amazons-ai-resurgence-aws-anthropics-multi-gigawatt-trainium-expansion', date: '2025', type: 'industry-report' },
    { name: 'SemiAnalysis', title: 'AWS Trainium3 Deep Dive | A Potential Challenger Approaching', url: 'https://newsletter.semianalysis.com/p/aws-trainium3-deep-dive-a-potential', date: '2025-12', type: 'industry-report' },
    { name: 'AWS', title: 'Trainium3 UltraServers now available', url: 'https://www.aboutamazon.com/news/aws/trainium-3-ultraserver-faster-ai-training-lower-cost', date: '2025-12', type: 'official' },
    { name: 'SemiAnalysis', title: 'Microsoft Infrastructure — AI & CPU Custom Silicon Maia 100, Athena, Cobalt 100', url: 'https://newsletter.semianalysis.com/p/microsoft-infrastructure-ai-and-cpu', date: '2025', type: 'industry-report' },
    { name: 'Microsoft', title: 'Inside Maia 100: Revolutionizing AI Workloads with Microsoft\'s Custom AI Accelerator', url: 'https://techcommunity.microsoft.com/blog/azureinfrastructureblog/inside-maia-100-revolutionizing-ai-workloads-with-microsofts-custom-ai-accelerat/4229118', date: '2024', type: 'official' },
    { name: 'IEEE Spectrum', title: 'Cerebras WSE-3: Third Generation Superchip for AI', url: 'https://spectrum.ieee.org/cerebras-chip-cs3', date: '2024', type: 'journal' },
    { name: 'Cerebras', title: 'Cerebras Announces Third-Generation Wafer-Scale Engine', url: 'https://www.cerebras.ai/press-release/cerebras-announces-third-generation-wafer-scale-engine', date: '2024', type: 'official' },
    { name: 'SambaNova', title: 'Why SambaNova\'s SN40L Chip Is the Best for Inference', url: 'https://sambanova.ai/blog/sn40l-chip-best-inference-solution', date: '2025', type: 'official' },
    { name: 'Chips and Cheese', title: 'd-Matrix Corsair: 256GB of LPDDR for AI Models', url: 'https://chipsandcheese.com/p/d-matrix-corsair-256gb-of-lpddr-for', date: '2025', type: 'blog' },
    { name: 'ServeTheHome', title: 'd-Matrix Corsair In-Memory Computing For AI Inference at Hot Chips 2025', url: 'https://www.servethehome.com/d-matrix-corsair-in-memory-computing-for-ai-inference-at-hot-chips-2025/', date: '2025', type: 'blog' },
    { name: 'Tom\'s Hardware', title: 'Etched Sohu: Transformer-Only Inference ASIC', url: 'https://www.tomshardware.com/tech-industry/artificial-intelligence/sohu-ai-chip-claimed-to-run-models-20x-faster-and-cheaper-than-nvidia-h100-gpus', date: '2024', type: 'news' },
    { name: 'Tenstorrent', title: 'Blackhole Specifications and Requirements', url: 'https://docs.tenstorrent.com/aibs/blackhole/specifications.html', date: '2025', type: 'official' },
    { name: 'Tom\'s Hardware', title: 'Nvidia DGX Spark review: the GB10 Superchip powers a fast and fun AI toolbox', url: 'https://www.tomshardware.com/pc-components/gpus/nvidia-dgx-spark-review', date: '2025', type: 'news' },
    { name: 'The Register', title: 'Tested: AMD\'s Strix Halo vs Nvidia\'s DGX Spark', url: 'https://www.theregister.com/2025/12/25/amd_strix_halo_nvidia_spark/', date: '2025-12-25', type: 'news' },
    { name: 'Local AI Master', title: 'NPU Comparison 2026: Intel vs Qualcomm vs AMD vs Apple', url: 'https://localaimaster.com/blog/npu-comparison-2026', date: '2026', type: 'benchmark' },
    { name: 'Lightmatter', title: 'Lightmatter Unveils Passage M1000 Photonic Superchip', url: 'https://lightmatter.co/press-release/lightmatter-unveils-passage-m1000-photonic-superchip-worlds-fastest-ai-interconnect/', date: '2025-03', type: 'official' },
    { name: 'SemiAnalysis', title: 'How Nvidia\'s CUDA Monopoly In Machine Learning Is Breaking — OpenAI Triton And PyTorch 2.0', url: 'https://newsletter.semianalysis.com/p/nvidiaopenaitritonpytorch', date: '2024', type: 'industry-report' },
    { name: 'SemiAnalysis', title: 'AMD 2.0 — New Sense of Urgency | MI450X Chance to Beat Nvidia | Nvidia\'s New Moat', url: 'https://semianalysis.com/2025/04/23/amd-2-0-new-sense-of-urgency-mi450x-chance-to-beat-nvidia-nvidias-new-moat/', date: '2025-04-23', type: 'industry-report' },
    { name: 'SemiAnalysis', title: 'Scaling the Memory Wall: The Rise and Roadmap of HBM', url: 'https://newsletter.semianalysis.com/p/scaling-the-memory-wall-the-rise-and-roadmap-of-hbm', date: '2025', type: 'industry-report' },
    { name: 'TechTimes', title: 'Custom AI Chips Outpace Nvidia GPU Growth in 2026: ASIC Shipments Set to Triple GPU Rate', url: 'https://www.techtimes.com/articles/317225/20260526/custom-ai-chips-outpace-nvidia-gpu-growth-2026-asic-shipments-set-triple-gpu-rate.htm', date: '2026-05-26', type: 'industry-report' },
    { name: 'Silicon Analysts', title: 'NVIDIA AI GPU Market Share 2026: ~80% of AI Accelerators', url: 'https://siliconanalysts.com/analysis/nvidia-ai-accelerator-market-share-2024-2026', date: '2026', type: 'industry-report' },
    { name: 'arXiv', title: 'Neuromorphic Principles for Efficient Large Language Models on Intel Loihi 2', url: 'https://arxiv.org/pdf/2503.18002', date: '2025-03', type: 'preprint' },
  ],

  'home-ai-labs': [
    { name: 'Apple Newsroom', title: 'Apple unveils new Mac Studio, the most powerful Mac ever', url: 'https://www.apple.com/newsroom/2025/03/apple-unveils-new-mac-studio-the-most-powerful-mac-ever/', date: '2025-03', type: 'official' },
    { name: 'MacSparky', title: 'Apple Drops 512GB RAM Option on M3 Ultra Mac Studio', url: 'https://www.macsparky.com/blog/2026/03/apple-drops-512gb-ram-option-on-m3-ultra-mac-studio/', date: '2026-03', type: 'blog' },
    { name: 'ServeTheHome', title: 'New 512GB Unified Memory Apple Mac Studio is the Local AI Play', url: 'https://www.servethehome.com/new-512gb-unified-memory-apple-mac-studio-is-the-local-ai-play/', date: '2025', type: 'blog' },
    { name: 'MacRumors', title: 'Mac Studio With M3 Ultra Runs Massive DeepSeek R1 AI Model Locally', url: 'https://www.macrumors.com/2025/03/17/apples-m3-ultra-runs-deepseek-r1-efficiently/', date: '2025-03', type: 'news' },
    { name: 'NVIDIA', title: 'Personal AI Supercomputer Powered by Blackwell | NVIDIA DGX Spark', url: 'https://www.nvidia.com/en-us/products/workstations/dgx-spark/', date: '2026', type: 'official' },
    { name: 'NVIDIA Newsroom', title: 'NVIDIA Announces DGX Spark and DGX Station Personal AI Computers', url: 'https://nvidianews.nvidia.com/news/nvidia-announces-dgx-spark-and-dgx-station-personal-ai-computers', date: '2025-03', type: 'official' },
    { name: 'Constellation Research', title: 'Nvidia DGX Spark now available — real impact will be AI at the edge', url: 'https://www.constellationr.com/insights/news/nvidia-dgx-spark-now-available-3999-real-impact-will-be-ai-edge', date: '2025', type: 'blog' },
    { name: 'NVIDIA Docs', title: 'Hardware Overview — DGX Spark User Guide', url: 'https://docs.nvidia.com/dgx/dgx-spark/hardware.html', date: '2026', type: 'official' },
    { name: 'Framework Community', title: 'AMD Strix Halo (Ryzen AI Max+ 395) GPU LLM Performance Tests — Framework Desktop', url: 'https://community.frame.work/t/amd-strix-halo-ryzen-ai-max-395-gpu-llm-performance-tests/72521', date: '2026', type: 'benchmark' },
    { name: 'kyuz0 (community)', title: 'AMD Strix Halo — Backend Benchmarks (Grid View)', url: 'https://kyuz0.github.io/amd-strix-halo-toolboxes/', date: '2026-06', type: 'benchmark' },
    { name: 'Tom\'s Hardware', title: 'GMKtec Evo X2 AI Mini PC review: Compact Strix Halo Powerhouse', url: 'https://www.tomshardware.com/desktops/mini-pcs/gmktec-evo-x2-ai-mini-pc-review', date: '2026', type: 'news' },
    { name: 'MiniPC Blogs', title: 'Beelink GTR9 Pro Review: The Local-LLM Mini PC of 2026', url: 'https://minipcblogs.com/en/a/beelink-gtr9-pro-review', date: '2026', type: 'blog' },
    { name: 'Hardware Corner', title: 'RTX 5090 LLM Benchmark Results: 10K Tokens/sec Prompt Processing, 139K Context', url: 'https://www.hardware-corner.net/rtx-5090-llm-benchmarks/', date: '2026', type: 'benchmark' },
    { name: 'OpenBenchmarking', title: 'Llama.cpp NVIDIA GeForce RTX 5090 Benchmarks', url: 'https://openbenchmarking.org/result/2501264-PTS-LLAMACPP76', date: '2025', type: 'benchmark' },
    { name: 'TechPowerUp', title: 'NVIDIA GeForce RTX 5090 Founders Edition Review — Temperatures & Fan Noise', url: 'https://www.techpowerup.com/review/nvidia-geforce-rtx-5090-founders-edition/41.html', date: '2025', type: 'benchmark' },
    { name: 'Puget Systems', title: 'Our Approach to Dual GeForce RTX 5090 Workstations', url: 'https://www.pugetsystems.com/blog/2025/10/28/our-approach-to-dual-geforce-rtx-5090-workstations/', date: '2025-10', type: 'blog' },
    { name: 'Jeff Geerling', title: '1.5 TB of VRAM on Mac Studio — RDMA over Thunderbolt 5', url: 'https://www.jeffgeerling.com/blog/2025/15-tb-vram-on-mac-studio-rdma-over-thunderbolt-5/', date: '2025', type: 'blog' },
    { name: 'Hardware Corner', title: 'RDMA over Thunderbolt Lets Mac Studios Run Huge Local LLMs Faster Than Expected', url: 'https://www.hardware-corner.net/mac-rdma-over-thunderbolt-llm/', date: '2026', type: 'benchmark' },
    { name: 'exo-explore', title: 'exo — Run frontier AI locally (GitHub)', url: 'https://github.com/exo-explore/exo', date: '2026', type: 'official' },
    { name: 'MacStories', title: 'Notes on Early Mac Studio AI Benchmarks with Qwen3-235B-A22B', url: 'https://www.macstories.net/notes/notes-on-early-mac-studio-ai-benchmarks-with-qwen3-235b-a22b-and-qwen2-5-vl-72b/', date: '2025', type: 'benchmark' },
    { name: 'Rost Glukhov', title: 'Ollama vs vLLM vs LM Studio: Best Way to Run LLMs Locally in 2026', url: 'https://www.glukhov.org/llm-hosting/comparisons/hosting-llms-ollama-localai-jan-lmstudio-vllm-comparison/', date: '2026', type: 'blog' },
    { name: 'yage.ai', title: 'MLX vs llama.cpp on Apple Silicon: Benchmarks, M5 Neural Accelerators, and Why Ollama Switched', url: 'https://yage.ai/share/mlx-apple-silicon-en-20260331.html', date: '2026-03', type: 'benchmark' },
    { name: 'bmdpat', title: 'GGUF Quantization Explained: Q4_K_M vs Q5_K_M vs Q8', url: 'https://bmdpat.com/blog/gguf-quantization-q4-q5-q8-explained-2026', date: '2026', type: 'blog' },
    { name: 'Hardware Corner', title: 'Llama 4 Scout & Maverick Benchmarks on Mac: How Fast Is Apple\'s M3 Ultra', url: 'https://www.hardware-corner.net/llama-4-on-mac-m3-ultra-speed/', date: '2026', type: 'benchmark' },
    { name: 'Local AI Master', title: 'Local AI Video Generation: Wan 2.2, LTX-Video & HunyuanVideo (2026)', url: 'https://localaimaster.com/blog/local-ai-video-generation', date: '2026', type: 'blog' },
    { name: 'Spheron', title: 'Self-Host AI Voice Cloning on GPU Cloud: XTTS-2, F5-TTS, OpenVoice V2 (2026)', url: 'https://www.spheron.network/blog/self-host-voice-cloning-gpu-cloud-xtts-f5-tts-openvoice-v2/', date: '2026', type: 'blog' },
  ],

  'autonomous-agent-runtimes': [
    { name: 'Wikipedia', title: 'OpenClaw', url: 'https://en.wikipedia.org/wiki/OpenClaw', date: '2026', type: 'news' },
    { name: 'GitHub', title: 'openclaw/openclaw — main repository', url: 'https://github.com/openclaw/openclaw', date: '2026', type: 'official' },
    { name: 'Peter Steinberger', title: 'OpenClaw, OpenAI and the future', url: 'https://steipete.me/posts/2026/openclaw', date: '2026-02', type: 'blog' },
    { name: 'TechCrunch', title: 'OpenClaw creator Peter Steinberger joins OpenAI', url: 'https://techcrunch.com/2026/02/15/openclaw-creator-peter-steinberger-joins-openai/', date: '2026-02-15', type: 'news' },
    { name: 'Yahoo Finance / Reuters', title: 'OpenClaw founder Steinberger joins OpenAI', url: 'https://finance.yahoo.com/news/openclaw-founder-steinberger-joins-openai-223554158.html', date: '2026-02-15', type: 'news' },
    { name: 'Podcast Transcript', title: 'Karpathy on Code Agents, AutoResearch, and the Loopy Era', url: 'https://podcasttranscript.ai/library/andrej-karpathy-on-code-agents-autoresearch-and', date: '2026-03', type: 'blog' },
    { name: 'karpathy-wiki', title: 'karpathy-x-2026-autoresearch-and-claws', url: 'https://github.com/nanzhipro/karpathy-wiki/blob/main/wiki/sources/karpathy-x-2026-autoresearch-and-claws.md', date: '2026-03', type: 'blog' },
    { name: 'Karpathy (X via xcancel)', title: 'On running OpenClaw', url: 'https://xcancel.com/karpathy/status/2024987174077432126', date: '2026', type: 'blog' },
    { name: 'GitHub', title: 'aaronjmars/soul.md — personality builder', url: 'https://github.com/aaronjmars/soul.md', date: '2026', type: 'official' },
    { name: 'GitHub', title: 'swarmclawai/swarmclaw — self-hosted multi-agent runtime', url: 'https://github.com/swarmclawai/swarmclaw', date: '2026', type: 'official' },
    { name: 'GitHub', title: 'TechNickAI/openclaw-config — OpenClaw on Claude Code', url: 'https://github.com/TechNickAI/openclaw-config', date: '2026', type: 'official' },
    { name: 'Mark Craddock', title: 'Building ClaudeClaw — an OpenClaw-style autonomous agent system on Claude Code', url: 'https://medium.com/@mcraddock/building-claudeclaw-an-openclaw-style-autonomous-agent-system-on-claude-code-fe0d7814ac2e', date: '2026-03', type: 'blog' },
    { name: 'NVIDIA Newsroom', title: 'NVIDIA Announces NemoClaw', url: 'https://nvidianews.nvidia.com/news/nvidia-announces-nemoclaw', date: '2026-03-16', type: 'official' },
    { name: 'VentureBeat', title: 'Nvidia\'s NemoClaw brings privacy and security controls to autonomous OpenClaw', url: 'https://venturebeat.com/technology/nvidias-nemoclaw-brings-privacy-and-security-controls-to-autonomous-openclaw', date: '2026-03', type: 'news' },
    { name: 'Milvus / Zilliz', title: 'We Extracted OpenClaw\'s Memory System and Open-Sourced It (memsearch)', url: 'https://milvus.io/blog/we-extracted-openclaws-memory-system-and-opensourced-it-memsearch.md', date: '2026-03-12', type: 'official' },
    { name: 'PR Newswire', title: 'Zilliz Open-Sources Memsearch — persistent, human-readable memory for AI agents', url: 'https://www.prnewswire.com/news-releases/zilliz-open-sources-memsearch-giving-ai-agents-persistent-human-readable-memory-302711968.html', date: '2026-03', type: 'official' },
    { name: 'clawdocs.org', title: 'SOUL.md Guide', url: 'https://clawdocs.org/guides/soul-md', date: '2026', type: 'official' },
    { name: 'Trend Micro', title: 'CISOs in a Pinch: A Security Analysis of OpenClaw', url: 'https://www.trendmicro.com/en_us/research/26/c/cisos-in-a-pinch-a-security-analysis-openclaw.html', date: '2026-03', type: 'industry-report' },
    { name: 'ISACA', title: 'Agentic AI Evolution and the Security Claw', url: 'https://www.isaca.org/resources/news-and-trends/isaca-now-blog/2026/agentic-ai-evolution-and-the-security-claw', date: '2026-04', type: 'industry-report' },
    { name: 'CrowdStrike', title: 'What Security Teams Need to Know About OpenClaw', url: 'https://www.crowdstrike.com/en-us/blog/what-security-teams-need-to-know-about-openclaw-ai-super-agent/', date: '2026', type: 'industry-report' },
    { name: 'The New Stack', title: 'OpenClaw rocks to GitHub\'s most-starred status', url: 'https://thenewstack.io/openclaw-github-stars-security/', date: '2026', type: 'news' },
    { name: 'NanoClaw', title: 'NanoClaw has no features', url: 'https://nanoclaw.dev/blog/nanoclaw-has-no-features/', date: '2026', type: 'blog' },
    { name: 'ToolHalla', title: 'Devin vs OpenHands vs SWE-agent — 2026 comparison', url: 'https://toolhalla.ai/blog/devin-vs-openhands-vs-swe-agent-2026', date: '2026', type: 'blog' },
  ],
}

export function getSourcesForDomain(slug: string): ResearchSource[] {
  return domainSources[slug] || []
}
