export type VisionaryCategoryId =
  | 'frontier-ai'
  | 'ai-toolsmiths'
  | 'creator-systems'
  | 'music-direction'
  | 'design-craft'
  | 'long-game-thinking'

export type VisionaryQualityTag =
  | 'Systems Thinking'
  | 'First-Principles'
  | 'Product Taste'
  | 'Craft Discipline'
  | 'Public Teaching'
  | 'Open Source'
  | 'Long-Horizon Vision'
  | 'Creative Risk'
  | 'Operational Excellence'
  | 'Distribution Mastery'
  | 'Human-Centered Leadership'
  | 'Resilience'

export interface VisionaryCategory {
  id: VisionaryCategoryId
  label: string
  description: string
  color: 'cyan' | 'indigo' | 'amber' | 'rose' | 'fuchsia' | 'emerald'
}

export interface VisionarySource {
  label: string
  url: string
  note: string
}

export interface VisionaryPerson {
  id: string
  name: string
  category: VisionaryCategoryId
  role: string
  builds: string
  why: string
  qualities: [VisionaryQualityTag, VisionaryQualityTag, VisionaryQualityTag]
  url: string
  youtubeId?: string
  top10Rank?: number
}

export const visionaryUpdatedAt = '2026-02-17'

export const visionaryMethodology: string[] = [
  'ACOS-routed workflow with research-engineer rigor and deep-research source cross-checking.',
  'Fit-to-FrankX lens: systems architecture, creator leverage, and craft depth.',
  'Cross-domain balance: AI, builder tools, creator economy, music, design, and long-game philosophy.',
  'Output over hype: selected for what they consistently ship, teach, or institutionalize.',
  'Top 10 are prioritized for direct imitation value in your current season of building.',
]

export const visionaryFitLens: string[] = [
  'Can this person help you build systems, not just consume tools?',
  'Do they prove craft through shipped work and repeatable practice?',
  'Do they teach in a way you can operationalize this week?',
  'Do they combine depth with leverage (distribution, product, or platform)?',
  'Do they model the long game under uncertainty?',
]

export const visionaryCategories: VisionaryCategory[] = [
  {
    id: 'frontier-ai',
    label: 'Frontier AI & Research',
    description: 'People shaping the state of AI models, safety, and research direction.',
    color: 'cyan',
  },
  {
    id: 'ai-toolsmiths',
    label: 'AI Toolsmiths & Platforms',
    description: 'Engineers and platform builders turning AI capability into usable systems.',
    color: 'indigo',
  },
  {
    id: 'creator-systems',
    label: 'Creator Systems & Distribution',
    description: 'Builders who turned expertise into repeatable audience and business engines.',
    color: 'amber',
  },
  {
    id: 'music-direction',
    label: 'Music & Creative Direction',
    description: 'Artists and producers who model high-output creative systems.',
    color: 'rose',
  },
  {
    id: 'design-craft',
    label: 'Design & Product Craft',
    description: 'Design leaders who prove that form, interaction, and taste are strategic.',
    color: 'fuchsia',
  },
  {
    id: 'long-game-thinking',
    label: 'Long-Game Thinking',
    description: 'Thinkers for decision quality, resilience, and compounding over decades.',
    color: 'emerald',
  },
]

export const visionarySources: VisionarySource[] = [
  {
    label: 'TIME100 AI 2025',
    url: 'https://time.com/collections/time100-ai-2025/',
    note: 'Used as a current influence baseline for AI leaders and innovators.',
  },
  {
    label: 'How TIME Chose TIME100 AI 2025',
    url: 'https://time.com/7312067/how-we-chose-time100-ai-2025/',
    note: 'Method framing for people-first influence analysis in AI.',
  },
  {
    label: 'Stanford HAI: 2025 AI Index Report',
    url: 'https://hai.stanford.edu/ai-index/2025-ai-index-report',
    note: 'Macro signal source for the current AI landscape and capability shifts.',
  },
  {
    label: 'GitHub Octoverse 2025',
    url: 'https://github.blog/news-insights/octoverse/octoverse-a-new-developer-joins-github-every-second-as-ai-leads-typescript-to-1/',
    note: 'Developer ecosystem trends used to prioritize builders and toolsmiths.',
  },
  {
    label: 'IAB Creator Economy 2025',
    url: 'https://www.iab.com/news/creator-economy-ad-spend-to-reach-37-billion-in-2025-growing-4x-faster-than-total-media-industry-according-to-iab/',
    note: 'Creator economy spend signal used for distribution and monetization weighting.',
  },
  {
    label: 'YouTube: Big Bets for 2025',
    url: 'https://blog.youtube/inside-youtube/our-big-bets-for-2025/',
    note: 'Distribution shift signal for creator strategy and media architecture.',
  },
  {
    label: 'Suno v4.5 Announcement',
    url: 'https://suno.com/blog/introducing-v4-5',
    note: 'Creative tooling signal for AI-native music workflows.',
  },
  {
    label: 'FrankX Brand Identity',
    url: '/BRAND_IDENTITY.md',
    note: 'Primary internal identity source for relevance scoring.',
  },
  {
    label: 'Dream 100 Framework',
    url: '/community/dream-100/README.md',
    note: 'Existing relationship and admiration framework baseline.',
  },
]

export const visionaries: VisionaryPerson[] = [
  {
    id: 'andrej-karpathy',
    name: 'Andrej Karpathy',
    category: 'frontier-ai',
    role: 'AI educator and research engineer',
    builds: 'Neural network learning systems and practical AI education loops',
    why: 'He turns deep model mechanics into operational practice you can apply immediately.',
    qualities: ['First-Principles', 'Public Teaching', 'Craft Discipline'],
    url: 'https://karpathy.ai',
    youtubeId: 'VMj-3S1tku0',
    top10Rank: 1,
  },
  {
    id: 'fei-fei-li',
    name: 'Fei-Fei Li',
    category: 'frontier-ai',
    role: 'Professor and AI institute builder',
    builds: 'Human-centered AI institutions and foundational vision datasets',
    why: 'She models how to lead frontier capability while keeping humans central.',
    qualities: ['Human-Centered Leadership', 'Long-Horizon Vision', 'Operational Excellence'],
    url: 'https://profiles.stanford.edu/fei-fei-li',
    youtubeId: 'ad79nYk2keg',
    top10Rank: 3,
  },
  {
    id: 'demis-hassabis',
    name: 'Demis Hassabis',
    category: 'frontier-ai',
    role: 'CEO, Google DeepMind',
    builds: 'Research organizations that convert deep science into world-scale products',
    why: 'He demonstrates long-cycle research translated into durable product advantage.',
    qualities: ['Long-Horizon Vision', 'Systems Thinking', 'Operational Excellence'],
    url: 'https://deepmind.google/about/people/demis-hassabis/',
    top10Rank: 4,
  },
  {
    id: 'andrew-ng',
    name: 'Andrew Ng',
    category: 'frontier-ai',
    role: 'AI educator and founder',
    builds: 'Applied AI education systems and enterprise adoption playbooks',
    why: 'He consistently bridges cutting-edge AI with practical execution for real teams.',
    qualities: ['Public Teaching', 'Systems Thinking', 'Human-Centered Leadership'],
    url: 'https://www.andrewng.org',
    top10Rank: 5,
  },
  {
    id: 'dario-amodei',
    name: 'Dario Amodei',
    category: 'frontier-ai',
    role: 'CEO, Anthropic',
    builds: 'Frontier model organizations with safety as a core architectural concern',
    why: 'He pushes capability and alignment together instead of treating them as trade-offs.',
    qualities: ['Long-Horizon Vision', 'Resilience', 'Operational Excellence'],
    url: 'https://www.anthropic.com/team/dario-amodei',
  },
  {
    id: 'ilya-sutskever',
    name: 'Ilya Sutskever',
    category: 'frontier-ai',
    role: 'AI researcher and lab founder',
    builds: 'High-performance learning systems and new research labs',
    why: 'He represents uncompromising research quality and conviction under uncertainty.',
    qualities: ['First-Principles', 'Long-Horizon Vision', 'Resilience'],
    url: 'https://en.wikipedia.org/wiki/Ilya_Sutskever',
  },
  {
    id: 'yann-lecun',
    name: 'Yann LeCun',
    category: 'frontier-ai',
    role: 'Chief AI Scientist, Meta',
    builds: 'Core deep learning architecture and long-range research agendas',
    why: 'He models scientific independence and sustained technical argumentation.',
    qualities: ['First-Principles', 'Long-Horizon Vision', 'Resilience'],
    url: 'https://ai.meta.com/people/yann-lecun/',
  },
  {
    id: 'geoffrey-hinton',
    name: 'Geoffrey Hinton',
    category: 'frontier-ai',
    role: 'Deep learning pioneer',
    builds: 'Foundational neural network methods that powered modern AI',
    why: 'He shows what decades of focused inquiry can compound into.',
    qualities: ['Long-Horizon Vision', 'First-Principles', 'Craft Discipline'],
    url: 'https://en.wikipedia.org/wiki/Geoffrey_Hinton',
  },
  {
    id: 'yoshua-bengio',
    name: 'Yoshua Bengio',
    category: 'frontier-ai',
    role: 'AI researcher and policy voice',
    builds: 'Research ecosystems balancing capability, openness, and safety priorities',
    why: 'He combines top-tier science with responsibility-driven public leadership.',
    qualities: ['Human-Centered Leadership', 'First-Principles', 'Long-Horizon Vision'],
    url: 'https://en.wikipedia.org/wiki/Yoshua_Bengio',
  },
  {
    id: 'richard-sutton',
    name: 'Richard Sutton',
    category: 'frontier-ai',
    role: 'Reinforcement learning pioneer',
    builds: 'Core RL frameworks and principles for autonomous learning systems',
    why: 'His work is a reminder that compounding ideas outlast trend cycles.',
    qualities: ['First-Principles', 'Long-Horizon Vision', 'Craft Discipline'],
    url: 'http://incompleteideas.net',
  },
  {
    id: 'david-silver',
    name: 'David Silver',
    category: 'frontier-ai',
    role: 'Research scientist, DeepMind',
    builds: 'Game-playing and planning systems that expand reasoning capabilities',
    why: 'He demonstrates how benchmark breakthroughs can reset entire research agendas.',
    qualities: ['Systems Thinking', 'First-Principles', 'Operational Excellence'],
    url: 'https://deepmind.google/about/people/david-silver/',
  },
  {
    id: 'percy-liang',
    name: 'Percy Liang',
    category: 'frontier-ai',
    role: 'Professor and evaluation leader',
    builds: 'Model evaluation, transparency, and benchmark governance initiatives',
    why: 'He emphasizes that better evaluation is the backbone of trustworthy progress.',
    qualities: ['Human-Centered Leadership', 'Systems Thinking', 'Public Teaching'],
    url: 'https://crfm.stanford.edu/people/percy',
  },
  {
    id: 'chelsea-finn',
    name: 'Chelsea Finn',
    category: 'frontier-ai',
    role: 'Professor, Stanford',
    builds: 'Robotics and meta-learning systems for adaptable intelligence',
    why: 'She connects machine learning research with real-world embodied systems.',
    qualities: ['First-Principles', 'Systems Thinking', 'Craft Discipline'],
    url: 'https://profiles.stanford.edu/chelsea-finn',
  },
  {
    id: 'stuart-russell',
    name: 'Stuart Russell',
    category: 'frontier-ai',
    role: 'Professor and AI safety thinker',
    builds: 'Foundational AI textbooks and risk frameworks',
    why: 'He provides strategic rigor for long-term AI alignment decisions.',
    qualities: ['First-Principles', 'Human-Centered Leadership', 'Public Teaching'],
    url: 'https://people.eecs.berkeley.edu/~russell/',
  },
  {
    id: 'ian-goodfellow',
    name: 'Ian Goodfellow',
    category: 'frontier-ai',
    role: 'Research scientist',
    builds: 'Generative adversarial methods and modern deep learning techniques',
    why: 'He represents technical originality that changes what is possible.',
    qualities: ['Creative Risk', 'First-Principles', 'Craft Discipline'],
    url: 'https://en.wikipedia.org/wiki/Ian_Goodfellow',
  },
  {
    id: 'aidan-gomez',
    name: 'Aidan Gomez',
    category: 'frontier-ai',
    role: 'Cofounder, Cohere',
    builds: 'Enterprise language model platforms for production AI applications',
    why: 'He focuses on shipping enterprise-grade model infrastructure, not just demos.',
    qualities: ['Operational Excellence', 'Systems Thinking', 'Long-Horizon Vision'],
    url: 'https://cohere.com/about',
  },
  {
    id: 'daniela-rus',
    name: 'Daniela Rus',
    category: 'frontier-ai',
    role: 'Director, MIT CSAIL',
    builds: 'Robotics and AI research labs with multi-disciplinary execution',
    why: 'She demonstrates how to build institutions that outlast individual hype cycles.',
    qualities: ['Human-Centered Leadership', 'Operational Excellence', 'Long-Horizon Vision'],
    url: 'https://www.csail.mit.edu/person/daniela-rus',
  },
  {
    id: 'jim-fan',
    name: 'Jim Fan',
    category: 'frontier-ai',
    role: 'Research lead, NVIDIA',
    builds: 'Embodied AI and agentic world models',
    why: 'He brings frontier AI into robotics and real-time systems contexts.',
    qualities: ['Systems Thinking', 'Creative Risk', 'Public Teaching'],
    url: 'https://research.nvidia.com/person/jim-fan',
  },
  {
    id: 'noam-brown',
    name: 'Noam Brown',
    category: 'frontier-ai',
    role: 'Research scientist',
    builds: 'Strategic reasoning systems for games and decision-making',
    why: 'He proves that constrained domains can produce transferable intelligence advances.',
    qualities: ['First-Principles', 'Craft Discipline', 'Systems Thinking'],
    url: 'https://en.wikipedia.org/wiki/Noam_Brown_(scientist)',
  },
  {
    id: 'sebastian-bubeck',
    name: 'Sebastian Bubeck',
    category: 'frontier-ai',
    role: 'Research scientist, Microsoft Research',
    builds: 'Reasoning-oriented model analysis and capability studies',
    why: 'He models rigorous interpretation of rapidly moving model behavior.',
    qualities: ['Public Teaching', 'First-Principles', 'Craft Discipline'],
    url: 'https://www.microsoft.com/en-us/research/people/sebubeck/',
  },

  {
    id: 'simon-willison',
    name: 'Simon Willison',
    category: 'ai-toolsmiths',
    role: 'Open source engineer and independent researcher',
    builds: 'Practical LLM tooling, knowledge pipelines, and daily research synthesis',
    why: 'He is the clearest model of shipping plus writing as one integrated system.',
    qualities: ['Open Source', 'Public Teaching', 'Craft Discipline'],
    url: 'https://simonwillison.net',
    youtubeId: 'pOLR5jE5Vjw',
    top10Rank: 2,
  },
  {
    id: 'guillermo-rauch',
    name: 'Guillermo Rauch',
    category: 'ai-toolsmiths',
    role: 'CEO, Vercel',
    builds: 'Developer platforms and AI-native web product infrastructure',
    why: 'He shows how product taste and infrastructure depth can compound together.',
    qualities: ['Product Taste', 'Operational Excellence', 'Long-Horizon Vision'],
    url: 'https://vercel.com/about',
    top10Rank: 8,
  },
  {
    id: 'chip-huyen',
    name: 'Chip Huyen',
    category: 'ai-toolsmiths',
    role: 'AI systems educator and advisor',
    builds: 'Production ML and LLM systems playbooks',
    why: 'She translates complex production realities into crisp architectural decisions.',
    qualities: ['Systems Thinking', 'Public Teaching', 'Operational Excellence'],
    url: 'https://huyenchip.com',
    top10Rank: 9,
  },
  {
    id: 'harrison-chase',
    name: 'Harrison Chase',
    category: 'ai-toolsmiths',
    role: 'CEO, LangChain',
    builds: 'Developer frameworks for LLM applications and agent orchestration',
    why: 'He shipped one of the fastest-evolving ecosystems in the AI tooling era.',
    qualities: ['Open Source', 'Operational Excellence', 'Resilience'],
    url: 'https://www.langchain.com',
  },
  {
    id: 'swyx',
    name: 'Shawn Wang (swyx)',
    category: 'ai-toolsmiths',
    role: 'Engineer and community builder',
    builds: 'AI engineering narratives and practitioner communities',
    why: 'He converts emerging technical shifts into actionable mental models.',
    qualities: ['Public Teaching', 'Distribution Mastery', 'Systems Thinking'],
    url: 'https://www.latent.space',
  },
  {
    id: 'hamel-husain',
    name: 'Hamel Husain',
    category: 'ai-toolsmiths',
    role: 'ML engineer and advisor',
    builds: 'Pragmatic LLM operations patterns for real deployments',
    why: 'He prioritizes applied truth over trend narratives.',
    qualities: ['Craft Discipline', 'Systems Thinking', 'Public Teaching'],
    url: 'https://hamel.dev',
  },
  {
    id: 'jeremy-howard',
    name: 'Jeremy Howard',
    category: 'ai-toolsmiths',
    role: 'Cofounder, fast.ai',
    builds: 'Applied deep learning education and open tools',
    why: 'He consistently lowers the barrier between theory and practical competence.',
    qualities: ['Public Teaching', 'Open Source', 'Human-Centered Leadership'],
    url: 'https://www.fast.ai',
  },
  {
    id: 'sebastian-raschka',
    name: 'Sebastian Raschka',
    category: 'ai-toolsmiths',
    role: 'ML educator and author',
    builds: 'Hands-on ML and LLM implementation guides',
    why: 'He is a benchmark for educational clarity in technical execution.',
    qualities: ['Public Teaching', 'Craft Discipline', 'First-Principles'],
    url: 'https://sebastianraschka.com',
  },
  {
    id: 'eugene-yan',
    name: 'Eugene Yan',
    category: 'ai-toolsmiths',
    role: 'Applied ML strategist',
    builds: 'Decision frameworks for production machine learning systems',
    why: 'He sharpens strategic thinking around what to build and why.',
    qualities: ['Systems Thinking', 'Public Teaching', 'Operational Excellence'],
    url: 'https://eugeneyan.com',
  },
  {
    id: 'lee-robinson',
    name: 'Lee Robinson',
    category: 'ai-toolsmiths',
    role: 'VP Product, Vercel',
    builds: 'Developer education and full-stack product patterns',
    why: 'He demonstrates how to teach and ship at platform scale.',
    qualities: ['Public Teaching', 'Product Taste', 'Operational Excellence'],
    url: 'https://leerob.io',
  },
  {
    id: 'theo-browne',
    name: 'Theo Browne',
    category: 'ai-toolsmiths',
    role: 'Engineer and educator',
    builds: 'Modern web and AI workflow content for builders',
    why: 'He is a strong example of clear opinions backed by shipped code.',
    qualities: ['Public Teaching', 'Craft Discipline', 'Distribution Mastery'],
    url: 'https://t3.gg',
  },
  {
    id: 'kent-c-dodds',
    name: 'Kent C. Dodds',
    category: 'ai-toolsmiths',
    role: 'Educator and open-source maintainer',
    builds: 'Testing and React engineering systems',
    why: 'He embodies rigorous quality standards in developer education.',
    qualities: ['Craft Discipline', 'Public Teaching', 'Open Source'],
    url: 'https://kentcdodds.com',
  },
  {
    id: 'dan-abramov',
    name: 'Dan Abramov',
    category: 'ai-toolsmiths',
    role: 'Software engineer and open source author',
    builds: 'Core React patterns and developer communication standards',
    why: 'He shows how precise language improves software architecture itself.',
    qualities: ['First-Principles', 'Open Source', 'Public Teaching'],
    url: 'https://overreacted.io',
  },
  {
    id: 'evan-you',
    name: 'Evan You',
    category: 'ai-toolsmiths',
    role: 'Creator of Vue.js',
    builds: 'Framework ecosystems with high adoption and maintainability',
    why: 'He balances elegance with practical developer experience.',
    qualities: ['Product Taste', 'Open Source', 'Craft Discipline'],
    url: 'https://evanyou.me',
  },
  {
    id: 'rich-harris',
    name: 'Rich Harris',
    category: 'ai-toolsmiths',
    role: 'Creator of Svelte',
    builds: 'Compiler-first frontend systems',
    why: 'He challenges defaults and ships alternatives that reduce complexity.',
    qualities: ['Creative Risk', 'Product Taste', 'Open Source'],
    url: 'https://svelte.dev',
  },
  {
    id: 'addy-osmani',
    name: 'Addy Osmani',
    category: 'ai-toolsmiths',
    role: 'Engineering leader, Google',
    builds: 'Performance playbooks and frontend architecture guidance',
    why: 'He translates performance engineering into applied team practice.',
    qualities: ['Public Teaching', 'Operational Excellence', 'Systems Thinking'],
    url: 'https://addyosmani.com',
  },
  {
    id: 'armin-ronacher',
    name: 'Armin Ronacher',
    category: 'ai-toolsmiths',
    role: 'Creator of Flask and systems engineer',
    builds: 'Minimal, durable developer frameworks and runtime tools',
    why: 'He proves that simple architecture can scale when designed carefully.',
    qualities: ['Craft Discipline', 'Open Source', 'First-Principles'],
    url: 'https://lucumr.pocoo.org',
  },
  {
    id: 'tj-holowaychuk',
    name: 'TJ Holowaychuk',
    category: 'ai-toolsmiths',
    role: 'Open-source software author',
    builds: 'Core Node ecosystem packages and developer tooling',
    why: 'He demonstrates ruthless focus on practical utility and code quality.',
    qualities: ['Open Source', 'Craft Discipline', 'Resilience'],
    url: 'https://github.com/tj',
  },
  {
    id: 'wes-bos',
    name: 'Wes Bos',
    category: 'ai-toolsmiths',
    role: 'Developer educator',
    builds: 'Applied JavaScript and full-stack training systems',
    why: 'He is an example of consistent teaching, shipping, and audience trust.',
    qualities: ['Public Teaching', 'Distribution Mastery', 'Craft Discipline'],
    url: 'https://wesbos.com',
  },
  {
    id: 'kelsey-hightower',
    name: 'Kelsey Hightower',
    category: 'ai-toolsmiths',
    role: 'Cloud systems engineer',
    builds: 'Infrastructure education and operational reliability practices',
    why: 'He models calm, principle-driven systems leadership at scale.',
    qualities: ['Systems Thinking', 'Operational Excellence', 'Public Teaching'],
    url: 'https://github.com/kelseyhightower',
  },

  {
    id: 'ali-abdaal',
    name: 'Ali Abdaal',
    category: 'creator-systems',
    role: 'Creator and educator',
    builds: 'Education products and creator business systems',
    why: 'He demonstrates structured output and creator-business compounding.',
    qualities: ['Distribution Mastery', 'Operational Excellence', 'Public Teaching'],
    url: 'https://aliabdaal.com',
    top10Rank: 10,
  },
  {
    id: 'dan-koe',
    name: 'Dan Koe',
    category: 'creator-systems',
    role: 'Digital writer and systems thinker',
    builds: 'One-person education business frameworks',
    why: 'He frames personal leverage as a system design problem.',
    qualities: ['Systems Thinking', 'Distribution Mastery', 'Long-Horizon Vision'],
    url: 'https://thedankoe.com',
  },
  {
    id: 'justin-welsh',
    name: 'Justin Welsh',
    category: 'creator-systems',
    role: 'Creator entrepreneur',
    builds: 'Solo business operating systems and audience funnels',
    why: 'He shows repeatable distribution mechanics for independent builders.',
    qualities: ['Distribution Mastery', 'Operational Excellence', 'Resilience'],
    url: 'https://thejustinwelsh.com',
  },
  {
    id: 'nathan-barry',
    name: 'Nathan Barry',
    category: 'creator-systems',
    role: 'Founder, Kit (ConvertKit)',
    builds: 'Creator email infrastructure and transparent growth systems',
    why: 'He proves platform plus education can compound over long horizons.',
    qualities: ['Operational Excellence', 'Long-Horizon Vision', 'Public Teaching'],
    url: 'https://nathanbarry.com',
  },
  {
    id: 'sahil-lavingia',
    name: 'Sahil Lavingia',
    category: 'creator-systems',
    role: 'Founder, Gumroad',
    builds: 'Creator monetization rails and open startup learning content',
    why: 'He is a model for shipping, reflecting, and iterating in public.',
    qualities: ['Resilience', 'Distribution Mastery', 'Public Teaching'],
    url: 'https://sahillavingia.com',
  },
  {
    id: 'david-perell',
    name: 'David Perell',
    category: 'creator-systems',
    role: 'Writing educator',
    builds: 'Writing-based intellectual business systems',
    why: 'He demonstrates how thinking quality maps to creator leverage.',
    qualities: ['Public Teaching', 'Craft Discipline', 'Distribution Mastery'],
    url: 'https://perell.com',
  },
  {
    id: 'pat-flynn',
    name: 'Pat Flynn',
    category: 'creator-systems',
    role: 'Entrepreneur and educator',
    builds: 'Audience-first business systems and creator education products',
    why: 'He models trust-driven monetization without hype tactics.',
    qualities: ['Human-Centered Leadership', 'Distribution Mastery', 'Resilience'],
    url: 'https://www.smartpassiveincome.com',
  },
  {
    id: 'tim-ferriss',
    name: 'Tim Ferriss',
    category: 'creator-systems',
    role: 'Author and interviewer',
    builds: 'Learning systems through high-signal interviewing and experimentation',
    why: 'He systematically extracts elite operating principles across domains.',
    qualities: ['Systems Thinking', 'Public Teaching', 'Long-Horizon Vision'],
    url: 'https://tim.blog',
  },
  {
    id: 'naval-ravikant',
    name: 'Naval Ravikant',
    category: 'creator-systems',
    role: 'Investor and thinker',
    builds: 'Mental models for leverage, ownership, and judgment',
    why: 'He provides a useful decision lens for creator-scale wealth building.',
    qualities: ['First-Principles', 'Long-Horizon Vision', 'Systems Thinking'],
    url: 'https://nav.al',
  },
  {
    id: 'alex-hormozi',
    name: 'Alex Hormozi',
    category: 'creator-systems',
    role: 'Entrepreneur and operator',
    builds: 'Acquisition and offer systems for business growth',
    why: 'He offers concrete operational frameworks for monetization execution.',
    qualities: ['Operational Excellence', 'Distribution Mastery', 'Resilience'],
    url: 'https://www.acquisition.com',
  },
  {
    id: 'lenny-rachitsky',
    name: 'Lenny Rachitsky',
    category: 'creator-systems',
    role: 'Product writer and podcaster',
    builds: 'Product strategy and operator knowledge networks',
    why: 'He compounds signal through curation and expert interviews.',
    qualities: ['Public Teaching', 'Distribution Mastery', 'Systems Thinking'],
    url: 'https://www.lennysnewsletter.com',
  },
  {
    id: 'april-dunford',
    name: 'April Dunford',
    category: 'creator-systems',
    role: 'Positioning strategist',
    builds: 'Market positioning systems for technical products',
    why: 'She sharpens the strategic language that drives product adoption.',
    qualities: ['First-Principles', 'Operational Excellence', 'Public Teaching'],
    url: 'https://www.aprildunford.com',
  },
  {
    id: 'katelyn-bourgoin',
    name: 'Katelyn Bourgoin',
    category: 'creator-systems',
    role: 'Customer psychology educator',
    builds: 'Demand and messaging systems rooted in buyer behavior',
    why: 'She translates psychology into practical growth decisions.',
    qualities: ['Systems Thinking', 'Distribution Mastery', 'Public Teaching'],
    url: 'https://www.katelynbourgoin.com',
  },
  {
    id: 'jay-clouse',
    name: 'Jay Clouse',
    category: 'creator-systems',
    role: 'Creator business educator',
    builds: 'Membership and audience operating systems for independents',
    why: 'He demonstrates disciplined, transparent creator business architecture.',
    qualities: ['Operational Excellence', 'Public Teaching', 'Resilience'],
    url: 'https://creatorscience.com',
  },
  {
    id: 'tiago-forte',
    name: 'Tiago Forte',
    category: 'creator-systems',
    role: 'Knowledge management educator',
    builds: 'Personal knowledge systems for high-output creators',
    why: 'He offers infrastructure for thinking, writing, and shipping consistently.',
    qualities: ['Systems Thinking', 'Public Teaching', 'Craft Discipline'],
    url: 'https://fortelabs.com',
  },

  {
    id: 'brian-eno',
    name: 'Brian Eno',
    category: 'music-direction',
    role: 'Producer and composer',
    builds: 'Generative music systems and ambient production frameworks',
    why: 'He is the blueprint for systemized creativity at artistic depth.',
    qualities: ['Creative Risk', 'Systems Thinking', 'Long-Horizon Vision'],
    url: 'https://en.wikipedia.org/wiki/Brian_Eno',
    top10Rank: 6,
  },
  {
    id: 'rick-rubin',
    name: 'Rick Rubin',
    category: 'music-direction',
    role: 'Producer and creative director',
    builds: 'Creative decision frameworks for artists across genres',
    why: 'He distills signal from noise and protects the essence of the work.',
    qualities: ['Product Taste', 'Human-Centered Leadership', 'Craft Discipline'],
    url: 'https://en.wikipedia.org/wiki/Rick_Rubin',
    top10Rank: 7,
  },
  {
    id: 'jacob-collier',
    name: 'Jacob Collier',
    category: 'music-direction',
    role: 'Composer and multi-instrumentalist',
    builds: 'Complex harmonic and arrangement systems with broad audience reach',
    why: 'He demonstrates high-technical complexity with emotional accessibility.',
    qualities: ['Craft Discipline', 'Creative Risk', 'Public Teaching'],
    url: 'https://www.jacobcollier.com',
  },
  {
    id: 'imogen-heap',
    name: 'Imogen Heap',
    category: 'music-direction',
    role: 'Artist and music technologist',
    builds: 'Music-technology interfaces and artist-first innovation projects',
    why: 'She bridges artistry, invention, and emerging technology cleanly.',
    qualities: ['Creative Risk', 'Systems Thinking', 'Human-Centered Leadership'],
    url: 'https://imogenheap.com',
  },
  {
    id: 'hans-zimmer',
    name: 'Hans Zimmer',
    category: 'music-direction',
    role: 'Film composer',
    builds: 'Scalable composition systems for cinematic storytelling',
    why: 'He shows how to turn musical identity into repeatable production architecture.',
    qualities: ['Operational Excellence', 'Product Taste', 'Craft Discipline'],
    url: 'https://en.wikipedia.org/wiki/Hans_Zimmer',
  },
  {
    id: 'trent-reznor',
    name: 'Trent Reznor',
    category: 'music-direction',
    role: 'Artist and composer',
    builds: 'Experimental production systems and high-impact scores',
    why: 'He models reinvention without sacrificing artistic edge.',
    qualities: ['Creative Risk', 'Resilience', 'Craft Discipline'],
    url: 'https://en.wikipedia.org/wiki/Trent_Reznor',
  },
  {
    id: 'finneas-oconnell',
    name: "Finneas O'Connell",
    category: 'music-direction',
    role: 'Producer and songwriter',
    builds: 'Modern pop production systems with tight emotional control',
    why: 'He demonstrates that minimal setups can still yield global-quality records.',
    qualities: ['Product Taste', 'Craft Discipline', 'Operational Excellence'],
    url: 'https://en.wikipedia.org/wiki/Finneas_O%27Connell',
  },
  {
    id: 'pharrell-williams',
    name: 'Pharrell Williams',
    category: 'music-direction',
    role: 'Producer and creative entrepreneur',
    builds: 'Cross-industry creative brands spanning music, fashion, and media',
    why: 'He shows how creative direction can scale across multiple verticals.',
    qualities: ['Distribution Mastery', 'Creative Risk', 'Product Taste'],
    url: 'https://en.wikipedia.org/wiki/Pharrell_Williams',
  },
  {
    id: 'joel-zimmerman',
    name: 'Joel Zimmerman (deadmau5)',
    category: 'music-direction',
    role: 'Producer and live performance technologist',
    builds: 'Electronic production workflows and high-control live systems',
    why: 'He models technical autonomy in modern music production.',
    qualities: ['Systems Thinking', 'Craft Discipline', 'Creative Risk'],
    url: 'https://en.wikipedia.org/wiki/Deadmau5',
  },
  {
    id: 'andrew-huang',
    name: 'Andrew Huang',
    category: 'music-direction',
    role: 'Music creator and educator',
    builds: 'Music education content and experimental production formats',
    why: 'He is a strong model for teaching through creative output.',
    qualities: ['Public Teaching', 'Creative Risk', 'Distribution Mastery'],
    url: 'https://www.andrewhuang.com',
  },
  {
    id: 'quincy-jones',
    name: 'Quincy Jones',
    category: 'music-direction',
    role: 'Producer and arranger',
    builds: 'Genre-defining production systems and collaborative music direction',
    why: 'He represents elite orchestration of people, process, and sound.',
    qualities: ['Operational Excellence', 'Human-Centered Leadership', 'Product Taste'],
    url: 'https://en.wikipedia.org/wiki/Quincy_Jones',
  },
  {
    id: 'nile-rodgers',
    name: 'Nile Rodgers',
    category: 'music-direction',
    role: 'Producer, guitarist, and songwriter',
    builds: 'Timeless groove systems and high-impact collaborations',
    why: 'He demonstrates stylistic consistency across decades and genres.',
    qualities: ['Craft Discipline', 'Resilience', 'Product Taste'],
    url: 'https://en.wikipedia.org/wiki/Nile_Rodgers',
  },
  {
    id: 'herbie-hancock',
    name: 'Herbie Hancock',
    category: 'music-direction',
    role: 'Composer and pianist',
    builds: 'Jazz innovation systems blending tradition with technology',
    why: 'He models curiosity-driven evolution over a lifetime of work.',
    qualities: ['Long-Horizon Vision', 'Creative Risk', 'Craft Discipline'],
    url: 'https://en.wikipedia.org/wiki/Herbie_Hancock',
  },
  {
    id: 'ar-rahman',
    name: 'A. R. Rahman',
    category: 'music-direction',
    role: 'Composer and producer',
    builds: 'Global composition systems bridging cinematic and popular music',
    why: 'He combines cultural depth with production modernity at scale.',
    qualities: ['Product Taste', 'Creative Risk', 'Operational Excellence'],
    url: 'https://en.wikipedia.org/wiki/A._R._Rahman',
  },
  {
    id: 'suzanne-ciani',
    name: 'Suzanne Ciani',
    category: 'music-direction',
    role: 'Composer and electronic music pioneer',
    builds: 'Modular synthesis and sonic identity systems',
    why: 'She models technical experimentation as a lifelong creative engine.',
    qualities: ['Creative Risk', 'Craft Discipline', 'Resilience'],
    url: 'https://en.wikipedia.org/wiki/Suzanne_Ciani',
  },

  {
    id: 'jony-ive',
    name: 'Jony Ive',
    category: 'design-craft',
    role: 'Industrial designer',
    builds: 'Iconic hardware and interaction systems',
    why: 'He demonstrates how design taste can shape entire product categories.',
    qualities: ['Product Taste', 'Craft Discipline', 'Long-Horizon Vision'],
    url: 'https://en.wikipedia.org/wiki/Jony_Ive',
  },
  {
    id: 'dieter-rams',
    name: 'Dieter Rams',
    category: 'design-craft',
    role: 'Industrial design legend',
    builds: 'Principle-driven design systems focused on clarity and utility',
    why: 'He is a benchmark for principled minimalism that lasts decades.',
    qualities: ['First-Principles', 'Product Taste', 'Craft Discipline'],
    url: 'https://en.wikipedia.org/wiki/Dieter_Rams',
  },
  {
    id: 'don-norman',
    name: 'Don Norman',
    category: 'design-craft',
    role: 'Design theorist',
    builds: 'Human-centered design frameworks used across product teams',
    why: 'He grounds product design in cognitive reality and user outcomes.',
    qualities: ['Human-Centered Leadership', 'Systems Thinking', 'Public Teaching'],
    url: 'https://en.wikipedia.org/wiki/Don_Norman',
  },
  {
    id: 'susan-kare',
    name: 'Susan Kare',
    category: 'design-craft',
    role: 'Interface iconographer',
    builds: 'Visual language systems for modern computing interfaces',
    why: 'She proves that tiny details can define entire product experiences.',
    qualities: ['Craft Discipline', 'Product Taste', 'Human-Centered Leadership'],
    url: 'https://en.wikipedia.org/wiki/Susan_Kare',
  },
  {
    id: 'paula-scher',
    name: 'Paula Scher',
    category: 'design-craft',
    role: 'Graphic designer',
    builds: 'Brand identity systems for institutions and products',
    why: 'She combines expressive typography with strategic communication clarity.',
    qualities: ['Product Taste', 'Creative Risk', 'Craft Discipline'],
    url: 'https://en.wikipedia.org/wiki/Paula_Scher',
  },
  {
    id: 'john-maeda',
    name: 'John Maeda',
    category: 'design-craft',
    role: 'Designer and technologist',
    builds: 'Design-tech frameworks and creative leadership models',
    why: 'He bridges computational thinking with design literacy.',
    qualities: ['Systems Thinking', 'Public Teaching', 'Long-Horizon Vision'],
    url: 'https://maeda.pm',
  },
  {
    id: 'julie-zhuo',
    name: 'Julie Zhuo',
    category: 'design-craft',
    role: 'Product design leader',
    builds: 'Product design management systems and team playbooks',
    why: 'She translates design leadership into practical team execution.',
    qualities: ['Human-Centered Leadership', 'Operational Excellence', 'Public Teaching'],
    url: 'https://www.juliezhuo.com',
  },
  {
    id: 'ryan-singer',
    name: 'Ryan Singer',
    category: 'design-craft',
    role: 'Product strategy and design thinker',
    builds: 'Shaping and product cycle decision frameworks',
    why: 'He helps teams ship better by tightening problem-definition quality.',
    qualities: ['Systems Thinking', 'First-Principles', 'Operational Excellence'],
    url: 'https://basecamp.com/shapeup',
  },
  {
    id: 'rauno-freiberg',
    name: 'Rauno Freiberg',
    category: 'design-craft',
    role: 'Design engineer',
    builds: 'High-fidelity web interaction systems and visual polish standards',
    why: 'He models how frontend detail quality compounds brand trust.',
    qualities: ['Product Taste', 'Craft Discipline', 'Creative Risk'],
    url: 'https://rauno.me',
  },
  {
    id: 'paco-coursey',
    name: 'Paco Coursey',
    category: 'design-craft',
    role: 'Design engineer and toolmaker',
    builds: 'Interface primitives and minimal interaction patterns',
    why: 'He demonstrates precision and restraint in modern UI craft.',
    qualities: ['Craft Discipline', 'Product Taste', 'Open Source'],
    url: 'https://paco.me',
  },
  {
    id: 'tobias-van-schneider',
    name: 'Tobias van Schneider',
    category: 'design-craft',
    role: 'Designer and entrepreneur',
    builds: 'Design-led products and independent brand systems',
    why: 'He is a strong model for independent creative direction with business leverage.',
    qualities: ['Distribution Mastery', 'Product Taste', 'Resilience'],
    url: 'https://vanschneider.com',
  },
  {
    id: 'refik-anadol',
    name: 'Refik Anadol',
    category: 'design-craft',
    role: 'Media artist',
    builds: 'AI-native visual systems and data-driven immersive art',
    why: 'He shows how machine intelligence can become a creative medium, not just a tool.',
    qualities: ['Creative Risk', 'Long-Horizon Vision', 'Product Taste'],
    url: 'https://refikanadol.com',
  },
  {
    id: 'bret-victor',
    name: 'Bret Victor',
    category: 'design-craft',
    role: 'Interface thinker and inventor',
    builds: 'Dynamic medium concepts for thinking and interaction design',
    why: 'He pushes you to design tools that amplify thought, not just output.',
    qualities: ['First-Principles', 'Creative Risk', 'Systems Thinking'],
    url: 'http://worrydream.com',
  },
  {
    id: 'jessica-walsh',
    name: 'Jessica Walsh',
    category: 'design-craft',
    role: 'Designer and creative director',
    builds: 'High-impact brand systems and visual storytelling products',
    why: 'She demonstrates expressive design with clear strategic intent.',
    qualities: ['Creative Risk', 'Product Taste', 'Distribution Mastery'],
    url: 'https://www.jessicawalsh.com',
  },
  {
    id: 'khoi-vinh',
    name: 'Khoi Vinh',
    category: 'design-craft',
    role: 'Designer and writer',
    builds: 'Design strategy frameworks for digital product organizations',
    why: 'He offers a systems-level lens on design decisions and org shape.',
    qualities: ['Systems Thinking', 'Public Teaching', 'Product Taste'],
    url: 'https://www.subtraction.com',
  },

  {
    id: 'peter-drucker',
    name: 'Peter Drucker',
    category: 'long-game-thinking',
    role: 'Management thinker',
    builds: 'Modern management principles and execution doctrine',
    why: 'He sharpens priorities, systems, and decision ownership.',
    qualities: ['Systems Thinking', 'First-Principles', 'Long-Horizon Vision'],
    url: 'https://en.wikipedia.org/wiki/Peter_Drucker',
  },
  {
    id: 'charlie-munger',
    name: 'Charlie Munger',
    category: 'long-game-thinking',
    role: 'Investor and mental model strategist',
    builds: 'Multi-disciplinary decision frameworks for compounding outcomes',
    why: 'He is a template for rational judgment under long time horizons.',
    qualities: ['First-Principles', 'Long-Horizon Vision', 'Resilience'],
    url: 'https://en.wikipedia.org/wiki/Charlie_Munger',
  },
  {
    id: 'warren-buffett',
    name: 'Warren Buffett',
    category: 'long-game-thinking',
    role: 'Investor and capital allocator',
    builds: 'Compounding systems through disciplined allocation and patience',
    why: 'He exemplifies consistency, process, and long-cycle conviction.',
    qualities: ['Long-Horizon Vision', 'Operational Excellence', 'Resilience'],
    url: 'https://en.wikipedia.org/wiki/Warren_Buffett',
  },
  {
    id: 'nassim-taleb',
    name: 'Nassim Nicholas Taleb',
    category: 'long-game-thinking',
    role: 'Risk thinker and author',
    builds: 'Decision frameworks for uncertainty, antifragility, and tail risk',
    why: 'He improves how you design systems that survive volatility.',
    qualities: ['First-Principles', 'Resilience', 'Systems Thinking'],
    url: 'https://en.wikipedia.org/wiki/Nassim_Nicholas_Taleb',
  },
  {
    id: 'james-clear',
    name: 'James Clear',
    category: 'long-game-thinking',
    role: 'Behavior and habit author',
    builds: 'Habit systems for repeatable long-term performance',
    why: 'He turns motivation into architecture and measurable behavior.',
    qualities: ['Systems Thinking', 'Public Teaching', 'Craft Discipline'],
    url: 'https://jamesclear.com',
  },
  {
    id: 'cal-newport',
    name: 'Cal Newport',
    category: 'long-game-thinking',
    role: 'Author and computer science professor',
    builds: 'Focus and deep work systems for knowledge workers',
    why: 'He protects attention quality in high-noise environments.',
    qualities: ['Craft Discipline', 'First-Principles', 'Public Teaching'],
    url: 'https://calnewport.com',
  },
  {
    id: 'ryan-holiday',
    name: 'Ryan Holiday',
    category: 'long-game-thinking',
    role: 'Author and strategist',
    builds: 'Stoic operating systems for discipline and emotional control',
    why: 'He gives practical resilience frameworks for long creative seasons.',
    qualities: ['Resilience', 'Public Teaching', 'Long-Horizon Vision'],
    url: 'https://ryanholiday.net',
  },
  {
    id: 'carol-dweck',
    name: 'Carol Dweck',
    category: 'long-game-thinking',
    role: 'Psychology researcher',
    builds: 'Growth mindset frameworks for learning and adaptation',
    why: 'She strengthens the mental model required for compounding skill.',
    qualities: ['Human-Centered Leadership', 'Public Teaching', 'Resilience'],
    url: 'https://en.wikipedia.org/wiki/Carol_Dweck',
  },
  {
    id: 'angela-duckworth',
    name: 'Angela Duckworth',
    category: 'long-game-thinking',
    role: 'Psychology researcher and author',
    builds: 'Grit and sustained effort frameworks',
    why: 'She reinforces that consistency outruns short-term intensity.',
    qualities: ['Resilience', 'Public Teaching', 'Long-Horizon Vision'],
    url: 'https://en.wikipedia.org/wiki/Angela_Duckworth',
  },
  {
    id: 'bj-fogg',
    name: 'B. J. Fogg',
    category: 'long-game-thinking',
    role: 'Behavior design researcher',
    builds: 'Tiny behavior systems for lasting change',
    why: 'He offers implementation-level behavior engineering.',
    qualities: ['Systems Thinking', 'Public Teaching', 'Human-Centered Leadership'],
    url: 'https://www.bjfogg.com',
  },
  {
    id: 'mihaly-csikszentmihalyi',
    name: 'Mihaly Csikszentmihalyi',
    category: 'long-game-thinking',
    role: 'Psychologist and flow researcher',
    builds: 'Flow state frameworks for optimal creative performance',
    why: 'He provides the science behind sustained creative immersion.',
    qualities: ['First-Principles', 'Public Teaching', 'Human-Centered Leadership'],
    url: 'https://en.wikipedia.org/wiki/Mihaly_Csikszentmihalyi',
  },
  {
    id: 'daniel-kahneman',
    name: 'Daniel Kahneman',
    category: 'long-game-thinking',
    role: 'Psychologist and Nobel laureate',
    builds: 'Cognitive bias and decision quality frameworks',
    why: 'He improves strategic judgment by revealing predictable thinking errors.',
    qualities: ['First-Principles', 'Public Teaching', 'Systems Thinking'],
    url: 'https://en.wikipedia.org/wiki/Daniel_Kahneman',
  },
  {
    id: 'annie-duke',
    name: 'Annie Duke',
    category: 'long-game-thinking',
    role: 'Decision strategist and author',
    builds: 'Probabilistic decision systems under uncertainty',
    why: 'She sharpens how to separate decision quality from outcomes.',
    qualities: ['First-Principles', 'Resilience', 'Public Teaching'],
    url: 'https://www.annieduke.com',
  },
  {
    id: 'ray-dalio',
    name: 'Ray Dalio',
    category: 'long-game-thinking',
    role: 'Investor and systems thinker',
    builds: 'Principles-based operating systems for organizations',
    why: 'He demonstrates codified principles as a scaling mechanism.',
    qualities: ['Systems Thinking', 'Operational Excellence', 'Long-Horizon Vision'],
    url: 'https://www.principles.com',
  },
  {
    id: 'adam-grant',
    name: 'Adam Grant',
    category: 'long-game-thinking',
    role: 'Organizational psychologist',
    builds: 'Evidence-based frameworks for work, motivation, and collaboration',
    why: 'He helps align high performance with healthier team cultures.',
    qualities: ['Human-Centered Leadership', 'Public Teaching', 'Systems Thinking'],
    url: 'https://adamgrant.net',
  },
]

export const topVisionaries = [...visionaries]
  .filter((person) => person.top10Rank)
  .sort((a, b) => (a.top10Rank ?? 999) - (b.top10Rank ?? 999))

export const qualityLegend: VisionaryQualityTag[] = [
  'Systems Thinking',
  'First-Principles',
  'Product Taste',
  'Craft Discipline',
  'Public Teaching',
  'Open Source',
  'Long-Horizon Vision',
  'Creative Risk',
  'Operational Excellence',
  'Distribution Mastery',
  'Human-Centered Leadership',
  'Resilience',
]
