export type VisionaryCategoryId =
  | 'frontier-ai'
  | 'ai-toolsmiths'
  | 'creator-systems'
  | 'music-direction'
  | 'design-craft'
  | 'long-game-thinking'

export type VisionaryQualityTag =
  | 'Systems Thinking'
  | 'First-Principles'
  | 'Product Taste'
  | 'Craft Discipline'
  | 'Public Teaching'
  | 'Open Source'
  | 'Long-Horizon Vision'
  | 'Creative Risk'
  | 'Operational Excellence'
  | 'Distribution Mastery'
  | 'Human-Centered Leadership'
  | 'Resilience'

export interface VisionaryCategory {
  id: VisionaryCategoryId
  label: string
  description: string
  color: 'cyan' | 'indigo' | 'amber' | 'rose' | 'fuchsia' | 'emerald'
}

export interface VisionarySource {
  label: string
  url: string
  note: string
}

export interface VisionarySocials {
  twitter?: string
  youtube?: string
  linkedin?: string
  github?: string
  website: string
}

export interface VisionaryStartHere {
  bestTalk?: { title: string; url: string; platform: string }
  bestArticle?: { title: string; url: string }
  bestBook?: { title: string; url: string }
}

export interface VisionaryProduct {
  title: string
  url: string
  type: 'book' | 'course' | 'tool' | 'newsletter'
  price?: string
}

export interface VisionaryPerson {
  id: string
  name: string
  slug?: string
  category: VisionaryCategoryId
  role: string
  builds: string
  why: string
  qualities: [VisionaryQualityTag, VisionaryQualityTag, VisionaryQualityTag]
  url: string
  youtubeId?: string
  top10Rank?: number
  // Enrichment fields (populated for Top 10+, optional for others)
  socials?: VisionarySocials
  startHere?: VisionaryStartHere
  products?: VisionaryProduct[]
  frankTake?: string
  whyDeep?: string           // Extended paragraph explaining why to study this person
  keyLessons?: string[]      // 3-5 specific, actionable lessons to take from this person
  featuredVideoId?: string   // YouTube video ID for the profile page embed (overrides youtubeId)
}

export const visionaryUpdatedAt = '2026-02-17'

export const visionaryMethodology: string[] = [
  'ACOS-routed workflow with research-engineer rigor and deep-research source cross-checking.',
  'Fit-to-FrankX lens: systems architecture, creator leverage, and craft depth.',
  'Cross-domain balance: AI, builder tools, creator economy, music, design, and long-game philosophy.',
  'Output over hype: selected for what they consistently ship, teach, or institutionalize.',
  'Top 10 are prioritized for direct imitation value in your current season of building.',
]

export const visionaryFitLens: string[] = [
  'Can this person help you build systems, not just consume tools?',
  'Do they prove craft through shipped work and repeatable practice?',
  'Do they teach in a way you can operationalize this week?',
  'Do they combine depth with leverage (distribution, product, or platform)?',
  'Do they model the long game under uncertainty?',
]

export const visionaryCategories: VisionaryCategory[] = [
  {
    id: 'frontier-ai',
    label: 'Frontier AI & Research',
    description: 'People shaping the state of AI models, safety, and research direction.',
    color: 'cyan',
  },
  {
    id: 'ai-toolsmiths',
    label: 'AI Toolsmiths & Platforms',
    description: 'Engineers and platform builders turning AI capability into usable systems.',
    color: 'indigo',
  },
  {
    id: 'creator-systems',
    label: 'Creator Systems & Distribution',
    description: 'Builders who turned expertise into repeatable audience and business engines.',
    color: 'amber',
  },
  {
    id: 'music-direction',
    label: 'Music & Creative Direction',
    description: 'Artists and producers who model high-output creative systems.',
    color: 'rose',
  },
  {
    id: 'design-craft',
    label: 'Design & Product Craft',
    description: 'Design leaders who prove that form, interaction, and taste are strategic.',
    color: 'fuchsia',
  },
  {
    id: 'long-game-thinking',
    label: 'Long-Game Thinking',
    description: 'Thinkers for decision quality, resilience, and compounding over decades.',
    color: 'emerald',
  },
]

export const visionarySources: VisionarySource[] = [
  {
    label: 'TIME100 AI 2025',
    url: 'https://time.com/collections/time100-ai-2025/',
    note: 'Used as a current influence baseline for AI leaders and innovators.',
  },
  {
    label: 'How TIME Chose TIME100 AI 2025',
    url: 'https://time.com/7312067/how-we-chose-time100-ai-2025/',
    note: 'Method framing for people-first influence analysis in AI.',
  },
  {
    label: 'Stanford HAI: 2025 AI Index Report',
    url: 'https://hai.stanford.edu/ai-index/2025-ai-index-report',
    note: 'Macro signal source for the current AI landscape and capability shifts.',
  },
  {
    label: 'GitHub Octoverse 2025',
    url: 'https://github.blog/news-insights/octoverse/octoverse-a-new-developer-joins-github-every-second-as-ai-leads-typescript-to-1/',
    note: 'Developer ecosystem trends used to prioritize builders and toolsmiths.',
  },
  {
    label: 'IAB Creator Economy 2025',
    url: 'https://www.iab.com/news/creator-economy-ad-spend-to-reach-37-billion-in-2025-growing-4x-faster-than-total-media-industry-according-to-iab/',
    note: 'Creator economy spend signal used for distribution and monetization weighting.',
  },
  {
    label: 'YouTube: Big Bets for 2025',
    url: 'https://blog.youtube/inside-youtube/our-big-bets-for-2025/',
    note: 'Distribution shift signal for creator strategy and media architecture.',
  },
  {
    label: 'Suno v4.5 Announcement',
    url: 'https://suno.com/blog/introducing-v4-5',
    note: 'Creative tooling signal for AI-native music workflows.',
  },
  {
    label: 'FrankX Brand Identity',
    url: '/BRAND_IDENTITY.md',
    note: 'Primary internal identity source for relevance scoring.',
  },
  {
    label: 'Dream 100 Framework',
    url: '/community/dream-100/README.md',
    note: 'Existing relationship and admiration framework baseline.',
  },
]

export const visionaries: VisionaryPerson[] = [
  {
    id: 'andrej-karpathy',
    name: 'Andrej Karpathy',
    slug: 'andrej-karpathy',
    category: 'frontier-ai',
    role: 'AI educator and research engineer',
    builds: 'Neural network learning systems and practical AI education loops',
    why: 'He turns deep model mechanics into operational practice you can apply immediately.',
    qualities: ['First-Principles', 'Public Teaching', 'Craft Discipline'],
    url: 'https://karpathy.ai',
    youtubeId: 'VMj-3S1tku0',
    top10Rank: 1,
    socials: { twitter: 'https://x.com/karpathy', youtube: 'https://www.youtube.com/@AndrejKarpathy', github: 'https://github.com/karpathy', website: 'https://karpathy.ai' },
    startHere: {
      bestTalk: { title: "Let's build GPT: from scratch, in code, spelled out", url: 'https://www.youtube.com/watch?v=kCc8FmEb1nY', platform: 'YouTube' },
      bestArticle: { title: 'A Recipe for Training Neural Networks', url: 'https://karpathy.github.io/2019/04/25/recipe/' },
    },
    products: [
      { title: 'Neural Networks: Zero to Hero', url: 'https://karpathy.ai/zero-to-hero.html', type: 'course', price: 'Free' },
    ],
    frankTake: 'Study his teaching method: he builds from first principles in code, never hand-waves. The Zero to Hero series is the gold standard for learning by building.',
    whyDeep: 'Karpathy is rare: a researcher who can explain transformers to beginners while also having built Tesla Autopilot. After leaving OpenAI and Tesla, he launched a free education series that has become the gold standard for learning deep learning by building. His approach — write every line from scratch, explain every gradient — is the opposite of framework-first tutorials. For builders, the lesson is not just the neural network content but the teaching method itself: radical transparency, first principles, no abstraction until the concrete is mastered.',
    keyLessons: [
      'Build from scratch before using frameworks — understanding beats convenience',
      'Teach by building in public: his entire YouTube catalog is live coding with explanations',
      'Simplify complex systems by decomposing them into atomic operations',
      'Ship educational content as a product — Zero to Hero has more impact than most startups',
      'Bridge research and practice: he reads papers and writes code in the same session',
    ],
    featuredVideoId: 'kCc8FmEb1nY',
  },
  {
    id: 'fei-fei-li',
    name: 'Fei-Fei Li',
    slug: 'fei-fei-li',
    category: 'frontier-ai',
    role: 'Professor and AI institute builder',
    builds: 'Human-centered AI institutions and foundational vision datasets',
    why: 'She models how to lead frontier capability while keeping humans central.',
    qualities: ['Human-Centered Leadership', 'Long-Horizon Vision', 'Operational Excellence'],
    url: 'https://profiles.stanford.edu/fei-fei-li',
    youtubeId: 'ad79nYk2keg',
    top10Rank: 3,
    socials: { twitter: 'https://x.com/drfeifei', linkedin: 'https://www.linkedin.com/in/fei-fei-li-4541247/', website: 'https://profiles.stanford.edu/fei-fei-li' },
    startHere: {
      bestTalk: { title: 'How we teach computers to understand pictures', url: 'https://www.youtube.com/watch?v=40riCqvRoMs', platform: 'TED' },
      bestBook: { title: 'The Worlds I See: Curiosity, Exploration, and Discovery at the Dawn of AI', url: 'https://www.amazon.com/Worlds-See-Curiosity-Exploration-Discovery/dp/1250897939' },
    },
    products: [
      { title: 'The Worlds I See', url: 'https://www.amazon.com/Worlds-See-Curiosity-Exploration-Discovery/dp/1250897939', type: 'book', price: '~$18' },
    ],
    frankTake: 'Read her memoir for the long arc of building a research institution from nothing. ImageNet changed the field because she invested in data infrastructure before it was fashionable.',
    whyDeep: 'Fei-Fei Li created ImageNet — the dataset that sparked the deep learning revolution — when the field thought vision was a solved problem. She built the Stanford Human-Centered AI Institute (HAI) to ensure AI development stays aligned with human values. Her memoir "The Worlds I See" reveals the 15-year arc from immigrant graduate student to one of the most influential voices in AI policy. For builders, the lesson is infrastructure investment: she spent years building a dataset everyone else thought was pointless, and it changed the entire field.',
    keyLessons: [
      'Invest in data infrastructure before it is fashionable — ImageNet was years ahead of its use',
      'Build institutions, not just projects — HAI outlasts any individual paper',
      'Bridge technical depth with policy influence — she advises governments on AI governance',
      'The long game wins: 15 years from ImageNet inception to Nobel-adjacent impact',
    ],
    featuredVideoId: '40riCqvRoMs',
  },
  {
    id: 'demis-hassabis',
    name: 'Demis Hassabis',
    slug: 'demis-hassabis',
    category: 'frontier-ai',
    role: 'CEO, Google DeepMind',
    builds: 'Research organizations that convert deep science into world-scale products',
    why: 'He demonstrates long-cycle research translated into durable product advantage.',
    qualities: ['Long-Horizon Vision', 'Systems Thinking', 'Operational Excellence'],
    url: 'https://deepmind.google/about/people/demis-hassabis/',
    top10Rank: 4,
    socials: { twitter: 'https://x.com/demishassabis', linkedin: 'https://www.linkedin.com/in/demishassabis/', website: 'https://deepmind.google/' },
    startHere: {
      bestTalk: { title: 'The Thinking Game — Full Documentary', url: 'https://www.youtube.com/watch?v=gNzNbCBr2Ak', platform: 'YouTube' },
      bestBook: { title: 'Infinity Machine (by Sebastian Mallaby)', url: 'https://www.amazon.com/dp/0593831845' },
    },
    products: [
      { title: 'AlphaFold Protein Structure Database', url: 'https://alphafold.ebi.ac.uk/', type: 'tool', price: 'Free' },
    ],
    frankTake: 'Study how he runs a 20-year research agenda inside a corporate structure. AlphaFold is the benchmark for turning pure science into a public good.',
    whyDeep: 'Hassabis is the architect of the longest-running AGI research program in the world. He co-founded DeepMind in 2010 with the explicit mission of "solving intelligence" — a 20+ year bet that has produced AlphaGo, AlphaFold (which predicted the structure of virtually every known protein), and a Nobel Prize in Chemistry. Inside Google, he has maintained research independence while shipping products that matter. For builders, the lesson is how to run a multi-decade research program inside a corporate structure without losing the mission.',
    keyLessons: [
      'Set a 20-year mission and protect it through acquisitions and corporate politics',
      'Turn pure research into public goods — AlphaFold database is free and used by 2M+ researchers',
      'Combine game-playing intuition with scientific rigor (chess prodigy → neuroscience PhD → AI lab)',
      'Build a team of researchers who stay for decades, not quarters',
    ],
    featuredVideoId: 'gNzNbCBr2Ak',
  },
  {
    id: 'andrew-ng',
    name: 'Andrew Ng',
    slug: 'andrew-ng',
    category: 'frontier-ai',
    role: 'AI educator and founder',
    builds: 'Applied AI education systems and enterprise adoption playbooks',
    why: 'He consistently bridges cutting-edge AI with practical execution for real teams.',
    qualities: ['Public Teaching', 'Systems Thinking', 'Human-Centered Leadership'],
    url: 'https://www.andrewng.org',
    top10Rank: 5,
    socials: { twitter: 'https://x.com/AndrewYNg', linkedin: 'https://www.linkedin.com/in/andrewyng/', website: 'https://www.andrewng.org' },
    startHere: {
      bestTalk: { title: 'Stanford CS229: Machine Learning (Full Course)', url: 'https://www.youtube.com/playlist?list=PLoROMvodv4rMiGQp3WXShtMGgzqpfVfbU', platform: 'YouTube' },
    },
    products: [
      { title: 'Machine Learning Specialization', url: 'https://www.coursera.org/specializations/machine-learning-introduction', type: 'course', price: '~$49/mo' },
      { title: 'Deep Learning Specialization', url: 'https://www.coursera.org/specializations/deep-learning', type: 'course', price: '~$49/mo' },
      { title: 'The Batch — weekly AI newsletter', url: 'https://www.deeplearning.ai/the-batch/', type: 'newsletter', price: 'Free' },
    ],
    frankTake: 'The most effective AI educator alive. His courses are the fastest path from zero to building. Subscribe to The Batch for a weekly signal-dense summary of what matters in AI.',
    whyDeep: 'Andrew Ng is the bridge between AI research and the working professional. He co-founded Coursera to democratize education, built Google Brain, led AI at Baidu, and then created DeepLearning.AI to make AI skills accessible to millions. His courses have trained more people in machine learning than any university program in history. For builders, the lesson is how to create a teaching empire that scales: structured curriculum, progressive complexity, and a newsletter (The Batch) that keeps 500K+ subscribers current on AI developments.',
    keyLessons: [
      'Structure education for progressive mastery — his courses build from linear algebra to production systems',
      'Build multiple vehicles for the same mission: Coursera (scale), Landing AI (enterprise), The Batch (signal)',
      'Make advanced concepts accessible without dumbing them down',
      'The teacher who reaches millions has more impact than the researcher who publishes dozens of papers',
    ],
  },
  {
    id: 'dario-amodei',
    name: 'Dario Amodei',
    category: 'frontier-ai',
    role: 'CEO, Anthropic',
    builds: 'Frontier model organizations with safety as a core architectural concern',
    why: 'He pushes capability and alignment together instead of treating them as trade-offs.',
    qualities: ['Long-Horizon Vision', 'Resilience', 'Operational Excellence'],
    url: 'https://www.anthropic.com/team/dario-amodei',
  },
  {
    id: 'ilya-sutskever',
    name: 'Ilya Sutskever',
    category: 'frontier-ai',
    role: 'AI researcher and lab founder',
    builds: 'High-performance learning systems and new research labs',
    why: 'He represents uncompromising research quality and conviction under uncertainty.',
    qualities: ['First-Principles', 'Long-Horizon Vision', 'Resilience'],
    url: 'https://en.wikipedia.org/wiki/Ilya_Sutskever',
  },
  {
    id: 'yann-lecun',
    name: 'Yann LeCun',
    category: 'frontier-ai',
    role: 'Chief AI Scientist, Meta',
    builds: 'Core deep learning architecture and long-range research agendas',
    why: 'He models scientific independence and sustained technical argumentation.',
    qualities: ['First-Principles', 'Long-Horizon Vision', 'Resilience'],
    url: 'https://ai.meta.com/people/yann-lecun/',
  },
  {
    id: 'geoffrey-hinton',
    name: 'Geoffrey Hinton',
    category: 'frontier-ai',
    role: 'Deep learning pioneer',
    builds: 'Foundational neural network methods that powered modern AI',
    why: 'He shows what decades of focused inquiry can compound into.',
    qualities: ['Long-Horizon Vision', 'First-Principles', 'Craft Discipline'],
    url: 'https://en.wikipedia.org/wiki/Geoffrey_Hinton',
  },
  {
    id: 'yoshua-bengio',
    name: 'Yoshua Bengio',
    category: 'frontier-ai',
    role: 'AI researcher and policy voice',
    builds: 'Research ecosystems balancing capability, openness, and safety priorities',
    why: 'He combines top-tier science with responsibility-driven public leadership.',
    qualities: ['Human-Centered Leadership', 'First-Principles', 'Long-Horizon Vision'],
    url: 'https://en.wikipedia.org/wiki/Yoshua_Bengio',
  },
  {
    id: 'richard-sutton',
    name: 'Richard Sutton',
    category: 'frontier-ai',
    role: 'Reinforcement learning pioneer',
    builds: 'Core RL frameworks and principles for autonomous learning systems',
    why: 'His work is a reminder that compounding ideas outlast trend cycles.',
    qualities: ['First-Principles', 'Long-Horizon Vision', 'Craft Discipline'],
    url: 'http://incompleteideas.net',
  },
  {
    id: 'david-silver',
    name: 'David Silver',
    category: 'frontier-ai',
    role: 'Research scientist, DeepMind',
    builds: 'Game-playing and planning systems that expand reasoning capabilities',
    why: 'He demonstrates how benchmark breakthroughs can reset entire research agendas.',
    qualities: ['Systems Thinking', 'First-Principles', 'Operational Excellence'],
    url: 'https://deepmind.google/about/people/david-silver/',
  },
  {
    id: 'percy-liang',
    name: 'Percy Liang',
    category: 'frontier-ai',
    role: 'Professor and evaluation leader',
    builds: 'Model evaluation, transparency, and benchmark governance initiatives',
    why: 'He emphasizes that better evaluation is the backbone of trustworthy progress.',
    qualities: ['Human-Centered Leadership', 'Systems Thinking', 'Public Teaching'],
    url: 'https://crfm.stanford.edu/people/percy',
  },
  {
    id: 'chelsea-finn',
    name: 'Chelsea Finn',
    category: 'frontier-ai',
    role: 'Professor, Stanford',
    builds: 'Robotics and meta-learning systems for adaptable intelligence',
    why: 'She connects machine learning research with real-world embodied systems.',
    qualities: ['First-Principles', 'Systems Thinking', 'Craft Discipline'],
    url: 'https://profiles.stanford.edu/chelsea-finn',
  },
  {
    id: 'stuart-russell',
    name: 'Stuart Russell',
    category: 'frontier-ai',
    role: 'Professor and AI safety thinker',
    builds: 'Foundational AI textbooks and risk frameworks',
    why: 'He provides strategic rigor for long-term AI alignment decisions.',
    qualities: ['First-Principles', 'Human-Centered Leadership', 'Public Teaching'],
    url: 'https://people.eecs.berkeley.edu/~russell/',
  },
  {
    id: 'ian-goodfellow',
    name: 'Ian Goodfellow',
    category: 'frontier-ai',
    role: 'Research scientist',
    builds: 'Generative adversarial methods and modern deep learning techniques',
    why: 'He represents technical originality that changes what is possible.',
    qualities: ['Creative Risk', 'First-Principles', 'Craft Discipline'],
    url: 'https://en.wikipedia.org/wiki/Ian_Goodfellow',
  },
  {
    id: 'aidan-gomez',
    name: 'Aidan Gomez',
    category: 'frontier-ai',
    role: 'Cofounder, Cohere',
    builds: 'Enterprise language model platforms for production AI applications',
    why: 'He focuses on shipping enterprise-grade model infrastructure, not just demos.',
    qualities: ['Operational Excellence', 'Systems Thinking', 'Long-Horizon Vision'],
    url: 'https://cohere.com/about',
  },
  {
    id: 'daniela-rus',
    name: 'Daniela Rus',
    category: 'frontier-ai',
    role: 'Director, MIT CSAIL',
    builds: 'Robotics and AI research labs with multi-disciplinary execution',
    why: 'She demonstrates how to build institutions that outlast individual hype cycles.',
    qualities: ['Human-Centered Leadership', 'Operational Excellence', 'Long-Horizon Vision'],
    url: 'https://www.csail.mit.edu/person/daniela-rus',
  },
  {
    id: 'jim-fan',
    name: 'Jim Fan',
    category: 'frontier-ai',
    role: 'Research lead, NVIDIA',
    builds: 'Embodied AI and agentic world models',
    why: 'He brings frontier AI into robotics and real-time systems contexts.',
    qualities: ['Systems Thinking', 'Creative Risk', 'Public Teaching'],
    url: 'https://research.nvidia.com/person/jim-fan',
  },
  {
    id: 'noam-brown',
    name: 'Noam Brown',
    category: 'frontier-ai',
    role: 'Research scientist',
    builds: 'Strategic reasoning systems for games and decision-making',
    why: 'He proves that constrained domains can produce transferable intelligence advances.',
    qualities: ['First-Principles', 'Craft Discipline', 'Systems Thinking'],
    url: 'https://en.wikipedia.org/wiki/Noam_Brown_(scientist)',
  },
  {
    id: 'sebastian-bubeck',
    name: 'Sebastian Bubeck',
    category: 'frontier-ai',
    role: 'Research scientist, Microsoft Research',
    builds: 'Reasoning-oriented model analysis and capability studies',
    why: 'He models rigorous interpretation of rapidly moving model behavior.',
    qualities: ['Public Teaching', 'First-Principles', 'Craft Discipline'],
    url: 'https://www.microsoft.com/en-us/research/people/sebubeck/',
  },

  {
    id: 'simon-willison',
    name: 'Simon Willison',
    slug: 'simon-willison',
    category: 'ai-toolsmiths',
    role: 'Open source engineer and independent researcher',
    builds: 'Practical LLM tooling, knowledge pipelines, and daily research synthesis',
    why: 'He is the clearest model of shipping plus writing as one integrated system.',
    qualities: ['Open Source', 'Public Teaching', 'Craft Discipline'],
    url: 'https://simonwillison.net',
    youtubeId: 'eTTMUWP5B0s',
    top10Rank: 2,
    socials: { twitter: 'https://x.com/simonw', linkedin: 'https://www.linkedin.com/in/simonwillison/', github: 'https://github.com/simonw', website: 'https://simonwillison.net' },
    startHere: {
      bestArticle: { title: 'What I learned from looking at 900 most popular open source AI tools', url: 'https://simonwillison.net/2024/Mar/22/ai-open-source/' },
    },
    products: [
      { title: 'LLM — CLI tool for language models', url: 'https://llm.datasette.io/', type: 'tool', price: 'Free / Open Source' },
      { title: 'Datasette — explore and publish data', url: 'https://datasette.io/', type: 'tool', price: 'Free / Open Source' },
      { title: "Simon Willison's Weblog", url: 'https://simonwillison.net/', type: 'newsletter', price: 'Free' },
    ],
    frankTake: 'The best builder-blogger in AI tooling. Watch how he ships small, composable tools fast and documents everything. His LLM CLI is how a craftsman integrates AI into real workflows.',
    whyDeep: 'Simon Willison is the best example of shipping and writing as a single integrated system. He builds small, composable tools (LLM CLI, Datasette, shot-scraper), writes extensively about every decision, and maintains a daily blog that has become required reading for AI practitioners. His approach to open source — small tools with clear boundaries, documented decisions, and welcoming contributor culture — is a masterclass in sustainable solo development. He proves that one person with craft discipline can create more lasting impact than many teams.',
    keyLessons: [
      'Ship small, composable tools — LLM CLI does one thing excellently and composes with everything',
      'Write about everything you build: the blog is the documentation, the marketing, and the thinking tool',
      'Name things well and make excellent developer experiences — Datasette and LLM are instantly understandable',
      'Maintain a daily practice of public learning — his TIL (Today I Learned) repository is legendary',
      'Open source as a craft: clear README, welcoming issues, responsive to contributors',
    ],
  },
  {
    id: 'guillermo-rauch',
    name: 'Guillermo Rauch',
    slug: 'guillermo-rauch',
    category: 'ai-toolsmiths',
    role: 'CEO, Vercel',
    builds: 'Developer platforms and AI-native web product infrastructure',
    why: 'He shows how product taste and infrastructure depth can compound together.',
    qualities: ['Product Taste', 'Operational Excellence', 'Long-Horizon Vision'],
    url: 'https://vercel.com/about',
    top10Rank: 8,
    socials: { twitter: 'https://x.com/rauchg', linkedin: 'https://www.linkedin.com/in/rauchg/', github: 'https://github.com/rauchg', website: 'https://rauchg.com/' },
    startHere: {
      bestArticle: { title: '7 Principles of Rich Web Applications', url: 'https://rauchg.com/2014/7-principles-of-rich-web-applications' },
    },
    products: [
      { title: 'Vercel — frontend cloud platform', url: 'https://vercel.com/', type: 'tool', price: 'Free tier / Pro $20/mo' },
      { title: 'v0 — AI web development', url: 'https://v0.dev/', type: 'tool', price: 'Free tier / Premium $20/mo' },
      { title: 'Next.js — React framework', url: 'https://nextjs.org/', type: 'tool', price: 'Free / Open Source' },
    ],
    frankTake: 'The best example of turning developer taste into a platform company. His "7 Principles" essay from 2014 is still the clearest articulation of what the modern web should be — and then he built it.',
    whyDeep: 'Guillermo Rauch wrote "7 Principles of Rich Web Applications" in 2014 — then spent the next decade building the infrastructure to make them real. Socket.io, Next.js, Vercel, and v0 each represent a step in a coherent product vision: real-time → server-rendered → deployed → AI-generated. He demonstrates that product taste — knowing which abstractions developers need before they ask — is the ultimate competitive advantage. Vercel is not the biggest cloud company, but it has the strongest developer brand because of relentless focus on experience.',
    keyLessons: [
      'Write the essay first, build the product second — his 2014 post is still the vision Vercel executes',
      'Product taste compounds: each product (Socket.io → Next.js → Vercel → v0) builds on the last',
      'Developer experience is a moat — Vercel wins on DX, not on price or features',
      'Ship fast and in public — Vercel Ship events are product launches that build community',
    ],
  },
  {
    id: 'chip-huyen',
    name: 'Chip Huyen',
    slug: 'chip-huyen',
    category: 'ai-toolsmiths',
    role: 'AI systems educator and advisor',
    builds: 'Production ML and LLM systems playbooks',
    why: 'She translates complex production realities into crisp architectural decisions.',
    qualities: ['Systems Thinking', 'Public Teaching', 'Operational Excellence'],
    url: 'https://huyenchip.com',
    top10Rank: 9,
    socials: { twitter: 'https://x.com/chipro', linkedin: 'https://www.linkedin.com/in/chiphuyen/', github: 'https://github.com/chiphuyen', website: 'https://huyenchip.com/' },
    startHere: {
      bestArticle: { title: 'What I learned from looking at 900 most popular open source AI tools', url: 'https://huyenchip.com/2024/03/14/ai-oss.html' },
      bestBook: { title: 'AI Engineering: Building Applications with Foundation Models', url: 'https://www.amazon.com/AI-Engineering-Building-Applications-Foundation/dp/1098166302' },
    },
    products: [
      { title: 'AI Engineering (2025)', url: 'https://www.amazon.com/AI-Engineering-Building-Applications-Foundation/dp/1098166302', type: 'book', price: '~$50' },
      { title: 'Designing Machine Learning Systems (2022)', url: 'https://www.amazon.com/Designing-Machine-Learning-Systems-Production-Ready/dp/1098107969', type: 'book', price: '~$45' },
    ],
    frankTake: 'The clearest writer on ML systems in production. Her AI Engineering book is the practical bridge between "I can prompt an LLM" and "I can ship an AI product." Required reading.',
    whyDeep: 'Chip Huyen bridges the gap between ML research and production engineering better than anyone writing today. Her first book "Designing Machine Learning Systems" became the standard reference for ML engineers. Her second, "AI Engineering," arrived at exactly the right moment — when the industry shifted from training models to building applications on top of them. She teaches at Stanford, advises startups, and maintains a blog that consistently ranks among the most-shared AI content. For builders, the lesson is clarity: she takes concepts that feel overwhelming and makes them architectural.',
    keyLessons: [
      'Write the book the industry needs right now — timing + clarity = category-defining impact',
      'Make architecture decisions visible: her system design frameworks are immediately usable',
      'Maintain a blog that industry leaders read — her "900 open source AI tools" post was shared 10K+ times',
      'Bridge academia and industry: teach at Stanford while advising production teams',
    ],
  },
  {
    id: 'harrison-chase',
    name: 'Harrison Chase',
    category: 'ai-toolsmiths',
    role: 'CEO, LangChain',
    builds: 'Developer frameworks for LLM applications and agent orchestration',
    why: 'He shipped one of the fastest-evolving ecosystems in the AI tooling era.',
    qualities: ['Open Source', 'Operational Excellence', 'Resilience'],
    url: 'https://www.langchain.com',
  },
  {
    id: 'swyx',
    name: 'Shawn Wang (swyx)',
    category: 'ai-toolsmiths',
    role: 'Engineer and community builder',
    builds: 'AI engineering narratives and practitioner communities',
    why: 'He converts emerging technical shifts into actionable mental models.',
    qualities: ['Public Teaching', 'Distribution Mastery', 'Systems Thinking'],
    url: 'https://www.latent.space',
  },
  {
    id: 'hamel-husain',
    name: 'Hamel Husain',
    category: 'ai-toolsmiths',
    role: 'ML engineer and advisor',
    builds: 'Pragmatic LLM operations patterns for real deployments',
    why: 'He prioritizes applied truth over trend narratives.',
    qualities: ['Craft Discipline', 'Systems Thinking', 'Public Teaching'],
    url: 'https://hamel.dev',
  },
  {
    id: 'jeremy-howard',
    name: 'Jeremy Howard',
    category: 'ai-toolsmiths',
    role: 'Cofounder, fast.ai',
    builds: 'Applied deep learning education and open tools',
    why: 'He consistently lowers the barrier between theory and practical competence.',
    qualities: ['Public Teaching', 'Open Source', 'Human-Centered Leadership'],
    url: 'https://www.fast.ai',
  },
  {
    id: 'sebastian-raschka',
    name: 'Sebastian Raschka',
    category: 'ai-toolsmiths',
    role: 'ML educator and author',
    builds: 'Hands-on ML and LLM implementation guides',
    why: 'He is a benchmark for educational clarity in technical execution.',
    qualities: ['Public Teaching', 'Craft Discipline', 'First-Principles'],
    url: 'https://sebastianraschka.com',
  },
  {
    id: 'eugene-yan',
    name: 'Eugene Yan',
    category: 'ai-toolsmiths',
    role: 'Applied ML strategist',
    builds: 'Decision frameworks for production machine learning systems',
    why: 'He sharpens strategic thinking around what to build and why.',
    qualities: ['Systems Thinking', 'Public Teaching', 'Operational Excellence'],
    url: 'https://eugeneyan.com',
  },
  {
    id: 'lee-robinson',
    name: 'Lee Robinson',
    category: 'ai-toolsmiths',
    role: 'VP Product, Vercel',
    builds: 'Developer education and full-stack product patterns',
    why: 'He demonstrates how to teach and ship at platform scale.',
    qualities: ['Public Teaching', 'Product Taste', 'Operational Excellence'],
    url: 'https://leerob.io',
  },
  {
    id: 'theo-browne',
    name: 'Theo Browne',
    category: 'ai-toolsmiths',
    role: 'Engineer and educator',
    builds: 'Modern web and AI workflow content for builders',
    why: 'He is a strong example of clear opinions backed by shipped code.',
    qualities: ['Public Teaching', 'Craft Discipline', 'Distribution Mastery'],
    url: 'https://t3.gg',
  },
  {
    id: 'kent-c-dodds',
    name: 'Kent C. Dodds',
    category: 'ai-toolsmiths',
    role: 'Educator and open-source maintainer',
    builds: 'Testing and React engineering systems',
    why: 'He embodies rigorous quality standards in developer education.',
    qualities: ['Craft Discipline', 'Public Teaching', 'Open Source'],
    url: 'https://kentcdodds.com',
  },
  {
    id: 'dan-abramov',
    name: 'Dan Abramov',
    category: 'ai-toolsmiths',
    role: 'Software engineer and open source author',
    builds: 'Core React patterns and developer communication standards',
    why: 'He shows how precise language improves software architecture itself.',
    qualities: ['First-Principles', 'Open Source', 'Public Teaching'],
    url: 'https://overreacted.io',
  },
  {
    id: 'evan-you',
    name: 'Evan You',
    category: 'ai-toolsmiths',
    role: 'Creator of Vue.js',
    builds: 'Framework ecosystems with high adoption and maintainability',
    why: 'He balances elegance with practical developer experience.',
    qualities: ['Product Taste', 'Open Source', 'Craft Discipline'],
    url: 'https://evanyou.me',
  },
  {
    id: 'rich-harris',
    name: 'Rich Harris',
    category: 'ai-toolsmiths',
    role: 'Creator of Svelte',
    builds: 'Compiler-first frontend systems',
    why: 'He challenges defaults and ships alternatives that reduce complexity.',
    qualities: ['Creative Risk', 'Product Taste', 'Open Source'],
    url: 'https://svelte.dev',
  },
  {
    id: 'addy-osmani',
    name: 'Addy Osmani',
    category: 'ai-toolsmiths',
    role: 'Engineering leader, Google',
    builds: 'Performance playbooks and frontend architecture guidance',
    why: 'He translates performance engineering into applied team practice.',
    qualities: ['Public Teaching', 'Operational Excellence', 'Systems Thinking'],
    url: 'https://addyosmani.com',
  },
  {
    id: 'armin-ronacher',
    name: 'Armin Ronacher',
    category: 'ai-toolsmiths',
    role: 'Creator of Flask and systems engineer',
    builds: 'Minimal, durable developer frameworks and runtime tools',
    why: 'He proves that simple architecture can scale when designed carefully.',
    qualities: ['Craft Discipline', 'Open Source', 'First-Principles'],
    url: 'https://lucumr.pocoo.org',
  },
  {
    id: 'tj-holowaychuk',
    name: 'TJ Holowaychuk',
    category: 'ai-toolsmiths',
    role: 'Open-source software author',
    builds: 'Core Node ecosystem packages and developer tooling',
    why: 'He demonstrates ruthless focus on practical utility and code quality.',
    qualities: ['Open Source', 'Craft Discipline', 'Resilience'],
    url: 'https://github.com/tj',
  },
  {
    id: 'wes-bos',
    name: 'Wes Bos',
    category: 'ai-toolsmiths',
    role: 'Developer educator',
    builds: 'Applied JavaScript and full-stack training systems',
    why: 'He is an example of consistent teaching, shipping, and audience trust.',
    qualities: ['Public Teaching', 'Distribution Mastery', 'Craft Discipline'],
    url: 'https://wesbos.com',
  },
  {
    id: 'kelsey-hightower',
    name: 'Kelsey Hightower',
    category: 'ai-toolsmiths',
    role: 'Cloud systems engineer',
    builds: 'Infrastructure education and operational reliability practices',
    why: 'He models calm, principle-driven systems leadership at scale.',
    qualities: ['Systems Thinking', 'Operational Excellence', 'Public Teaching'],
    url: 'https://github.com/kelseyhightower',
  },

  {
    id: 'ali-abdaal',
    name: 'Ali Abdaal',
    slug: 'ali-abdaal',
    category: 'creator-systems',
    role: 'Creator and educator',
    builds: 'Education products and creator business systems',
    why: 'He demonstrates structured output and creator-business compounding.',
    qualities: ['Distribution Mastery', 'Operational Excellence', 'Public Teaching'],
    url: 'https://aliabdaal.com',
    top10Rank: 10,
    socials: { twitter: 'https://x.com/AliAbdaal', youtube: 'https://www.youtube.com/@aliabdaal', linkedin: 'https://www.linkedin.com/in/ali-abdaal/', website: 'https://aliabdaal.com/' },
    startHere: {
      bestBook: { title: 'Feel-Good Productivity: How to Do More of What Matters to You', url: 'https://www.amazon.com/Feel-Good-Productivity-More-What-Matters/dp/1250865034' },
    },
    products: [
      { title: 'Feel-Good Productivity', url: 'https://www.amazon.com/Feel-Good-Productivity-More-What-Matters/dp/1250865034', type: 'book', price: '~$18' },
      { title: 'Part-Time YouTuber Academy', url: 'https://academy.aliabdaal.com/', type: 'course', price: '$2,000–$5,000' },
      { title: 'Ali Abdaal Newsletter', url: 'https://aliabdaal.com/newsletter/', type: 'newsletter', price: 'Free' },
    ],
    frankTake: 'Study his business model, not just his content. He turned a YouTube channel into a $4M+/year education business with clear product tiers. The system design behind his creator business is the real lesson.',
    whyDeep: 'Ali Abdaal is the most legible case study in turning a personal brand into a multi-million dollar education business. Doctor-turned-YouTuber with 6M+ subscribers, he documents his creator journey with full revenue transparency. The Part-Time YouTuber Academy ($2K-5K), Feel-Good Productivity book, and newsletter form a clear product ladder. For builders, the lesson is not the individual tactics but the system: consistent publishing schedule, clear product tiers, team scaling at each revenue milestone, and data-driven content optimization.',
    keyLessons: [
      'Build a product ladder: free YouTube → newsletter → book → premium course → cohort program',
      'Revenue transparency builds trust and creates a case study that attracts students',
      'Systematize content production: templates, batching, team delegation at each revenue tier',
      'Choose a niche intersection (productivity + medicine + YouTube) then expand from a position of authority',
    ],
  },
  {
    id: 'dan-koe',
    name: 'Dan Koe',
    category: 'creator-systems',
    role: 'Digital writer and systems thinker',
    builds: 'One-person education business frameworks',
    why: 'He frames personal leverage as a system design problem.',
    qualities: ['Systems Thinking', 'Distribution Mastery', 'Long-Horizon Vision'],
    url: 'https://thedankoe.com',
  },
  {
    id: 'justin-welsh',
    name: 'Justin Welsh',
    category: 'creator-systems',
    role: 'Creator entrepreneur',
    builds: 'Solo business operating systems and audience funnels',
    why: 'He shows repeatable distribution mechanics for independent builders.',
    qualities: ['Distribution Mastery', 'Operational Excellence', 'Resilience'],
    url: 'https://thejustinwelsh.com',
  },
  {
    id: 'nathan-barry',
    name: 'Nathan Barry',
    category: 'creator-systems',
    role: 'Founder, Kit (ConvertKit)',
    builds: 'Creator email infrastructure and transparent growth systems',
    why: 'He proves platform plus education can compound over long horizons.',
    qualities: ['Operational Excellence', 'Long-Horizon Vision', 'Public Teaching'],
    url: 'https://nathanbarry.com',
  },
  {
    id: 'sahil-lavingia',
    name: 'Sahil Lavingia',
    category: 'creator-systems',
    role: 'Founder, Gumroad',
    builds: 'Creator monetization rails and open startup learning content',
    why: 'He is a model for shipping, reflecting, and iterating in public.',
    qualities: ['Resilience', 'Distribution Mastery', 'Public Teaching'],
    url: 'https://sahillavingia.com',
  },
  {
    id: 'david-perell',
    name: 'David Perell',
    category: 'creator-systems',
    role: 'Writing educator',
    builds: 'Writing-based intellectual business systems',
    why: 'He demonstrates how thinking quality maps to creator leverage.',
    qualities: ['Public Teaching', 'Craft Discipline', 'Distribution Mastery'],
    url: 'https://perell.com',
  },
  {
    id: 'pat-flynn',
    name: 'Pat Flynn',
    category: 'creator-systems',
    role: 'Entrepreneur and educator',
    builds: 'Audience-first business systems and creator education products',
    why: 'He models trust-driven monetization without hype tactics.',
    qualities: ['Human-Centered Leadership', 'Distribution Mastery', 'Resilience'],
    url: 'https://www.smartpassiveincome.com',
  },
  {
    id: 'tim-ferriss',
    name: 'Tim Ferriss',
    category: 'creator-systems',
    role: 'Author and interviewer',
    builds: 'Learning systems through high-signal interviewing and experimentation',
    why: 'He systematically extracts elite operating principles across domains.',
    qualities: ['Systems Thinking', 'Public Teaching', 'Long-Horizon Vision'],
    url: 'https://tim.blog',
  },
  {
    id: 'naval-ravikant',
    name: 'Naval Ravikant',
    category: 'creator-systems',
    role: 'Investor and thinker',
    builds: 'Mental models for leverage, ownership, and judgment',
    why: 'He provides a useful decision lens for creator-scale wealth building.',
    qualities: ['First-Principles', 'Long-Horizon Vision', 'Systems Thinking'],
    url: 'https://nav.al',
  },
  {
    id: 'alex-hormozi',
    name: 'Alex Hormozi',
    category: 'creator-systems',
    role: 'Entrepreneur and operator',
    builds: 'Acquisition and offer systems for business growth',
    why: 'He offers concrete operational frameworks for monetization execution.',
    qualities: ['Operational Excellence', 'Distribution Mastery', 'Resilience'],
    url: 'https://www.acquisition.com',
  },
  {
    id: 'lenny-rachitsky',
    name: 'Lenny Rachitsky',
    category: 'creator-systems',
    role: 'Product writer and podcaster',
    builds: 'Product strategy and operator knowledge networks',
    why: 'He compounds signal through curation and expert interviews.',
    qualities: ['Public Teaching', 'Distribution Mastery', 'Systems Thinking'],
    url: 'https://www.lennysnewsletter.com',
  },
  {
    id: 'april-dunford',
    name: 'April Dunford',
    category: 'creator-systems',
    role: 'Positioning strategist',
    builds: 'Market positioning systems for technical products',
    why: 'She sharpens the strategic language that drives product adoption.',
    qualities: ['First-Principles', 'Operational Excellence', 'Public Teaching'],
    url: 'https://www.aprildunford.com',
  },
  {
    id: 'katelyn-bourgoin',
    name: 'Katelyn Bourgoin',
    category: 'creator-systems',
    role: 'Customer psychology educator',
    builds: 'Demand and messaging systems rooted in buyer behavior',
    why: 'She translates psychology into practical growth decisions.',
    qualities: ['Systems Thinking', 'Distribution Mastery', 'Public Teaching'],
    url: 'https://www.katelynbourgoin.com',
  },
  {
    id: 'jay-clouse',
    name: 'Jay Clouse',
    category: 'creator-systems',
    role: 'Creator business educator',
    builds: 'Membership and audience operating systems for independents',
    why: 'He demonstrates disciplined, transparent creator business architecture.',
    qualities: ['Operational Excellence', 'Public Teaching', 'Resilience'],
    url: 'https://creatorscience.com',
  },
  {
    id: 'tiago-forte',
    name: 'Tiago Forte',
    category: 'creator-systems',
    role: 'Knowledge management educator',
    builds: 'Personal knowledge systems for high-output creators',
    why: 'He offers infrastructure for thinking, writing, and shipping consistently.',
    qualities: ['Systems Thinking', 'Public Teaching', 'Craft Discipline'],
    url: 'https://fortelabs.com',
  },

  {
    id: 'brian-eno',
    name: 'Brian Eno',
    slug: 'brian-eno',
    category: 'music-direction',
    role: 'Producer and composer',
    builds: 'Generative music systems and ambient production frameworks',
    why: 'He is the blueprint for systemized creativity at artistic depth.',
    qualities: ['Creative Risk', 'Systems Thinking', 'Long-Horizon Vision'],
    url: 'https://en.wikipedia.org/wiki/Brian_Eno',
    top10Rank: 6,
    socials: { twitter: 'https://x.com/brianeno', website: 'https://enoshop.co.uk/' },
    startHere: {
      bestArticle: { title: 'Generative Music (1996 talk transcript)', url: 'https://www.inmotionmagazine.com/eno1.html' },
      bestBook: { title: "A Year with Swollen Appendices: Brian Eno's Diary", url: 'https://www.amazon.com/Year-Swollen-Appendices-Brian-Enos/dp/0571364616' },
    },
    products: [
      { title: 'A Year with Swollen Appendices', url: 'https://www.amazon.com/Year-Swollen-Appendices-Brian-Enos/dp/0571364616', type: 'book', price: '~$17' },
      { title: 'Oblique Strategies — creative thinking cards', url: 'https://enoshop.co.uk/products/oblique-strategies', type: 'tool', price: '~$55' },
    ],
    frankTake: 'The original systems thinker in music. His generative music concept in 1996 predicted AI-assisted creation decades early. Oblique Strategies is still the best creative unblocking tool ever made.',
    whyDeep: 'Brian Eno invented ambient music, coined the term, and then spent 50 years proving that the most important creative skill is designing systems that generate beauty without constant intervention. His 1996 generative music talk predicted AI-assisted creation decades before Suno or DALL-E existed. Oblique Strategies — a deck of cards with lateral thinking prompts — remains the most effective creative unblocking tool ever made. For builders, the lesson is that constraints and systems produce better art than raw inspiration. He produces by subtracting, not adding.',
    keyLessons: [
      'Design systems that generate output, not just individual pieces — generative music is a paradigm',
      'Constraints produce creativity: his "Oblique Strategies" are structured randomness applied to art',
      'Subtract to improve: his production philosophy is removing elements until only the essential remains',
      'Think in decades, not quarters: ambient music was dismissed for 20 years before becoming a genre',
      'Cross-pollinate: visual art, music, software, and philosophy are one practice for Eno',
    ],
  },
  {
    id: 'rick-rubin',
    name: 'Rick Rubin',
    slug: 'rick-rubin',
    category: 'music-direction',
    role: 'Producer and creative director',
    builds: 'Creative decision frameworks for artists across genres',
    why: 'He distills signal from noise and protects the essence of the work.',
    qualities: ['Product Taste', 'Human-Centered Leadership', 'Craft Discipline'],
    url: 'https://en.wikipedia.org/wiki/Rick_Rubin',
    top10Rank: 7,
    socials: { twitter: 'https://x.com/RickRubin', website: 'https://www.tetragrammaton.com/' },
    startHere: {
      bestBook: { title: 'The Creative Act: A Way of Being', url: 'https://www.amazon.com/Creative-Act-Way-Being/dp/0593652886' },
    },
    products: [
      { title: 'The Creative Act: A Way of Being', url: 'https://www.amazon.com/Creative-Act-Way-Being/dp/0593652886', type: 'book', price: '~$20' },
      { title: 'Tetragrammaton Podcast', url: 'https://www.tetragrammaton.com/podcasts', type: 'newsletter', price: 'Free' },
    ],
    frankTake: 'Read The Creative Act for the meta-skill behind all creative work: taste as a practice, not a gift. His production method — stripping everything to its essence — applies directly to product design and code.',
    whyDeep: 'Rick Rubin has produced genre-defining albums for Johnny Cash, Beastie Boys, Jay-Z, Red Hot Chili Peppers, Adele, and dozens more — across hip-hop, rock, country, and metal. His book "The Creative Act: A Way of Being" distills 40 years of production wisdom into a philosophy applicable far beyond music. His method: create the safest possible space for the artist, then strip everything non-essential until only the core remains. For builders, this is the product design philosophy most people miss — taste is not adding the right things, it is removing the wrong things.',
    keyLessons: [
      'Taste is subtraction: the producer\'s job is removing everything that does not serve the work',
      'Create psychological safety first — the best work comes when people feel free to experiment',
      'Genre is irrelevant: principles of quality apply identically across domains',
      'The audience is not the customer — serve the work itself, and the audience follows',
    ],
  },
  {
    id: 'jacob-collier',
    name: 'Jacob Collier',
    category: 'music-direction',
    role: 'Composer and multi-instrumentalist',
    builds: 'Complex harmonic and arrangement systems with broad audience reach',
    why: 'He demonstrates high-technical complexity with emotional accessibility.',
    qualities: ['Craft Discipline', 'Creative Risk', 'Public Teaching'],
    url: 'https://www.jacobcollier.com',
  },
  {
    id: 'imogen-heap',
    name: 'Imogen Heap',
    category: 'music-direction',
    role: 'Artist and music technologist',
    builds: 'Music-technology interfaces and artist-first innovation projects',
    why: 'She bridges artistry, invention, and emerging technology cleanly.',
    qualities: ['Creative Risk', 'Systems Thinking', 'Human-Centered Leadership'],
    url: 'https://imogenheap.com',
  },
  {
    id: 'hans-zimmer',
    name: 'Hans Zimmer',
    category: 'music-direction',
    role: 'Film composer',
    builds: 'Scalable composition systems for cinematic storytelling',
    why: 'He shows how to turn musical identity into repeatable production architecture.',
    qualities: ['Operational Excellence', 'Product Taste', 'Craft Discipline'],
    url: 'https://en.wikipedia.org/wiki/Hans_Zimmer',
  },
  {
    id: 'trent-reznor',
    name: 'Trent Reznor',
    category: 'music-direction',
    role: 'Artist and composer',
    builds: 'Experimental production systems and high-impact scores',
    why: 'He models reinvention without sacrificing artistic edge.',
    qualities: ['Creative Risk', 'Resilience', 'Craft Discipline'],
    url: 'https://en.wikipedia.org/wiki/Trent_Reznor',
  },
  {
    id: 'finneas-oconnell',
    name: "Finneas O'Connell",
    category: 'music-direction',
    role: 'Producer and songwriter',
    builds: 'Modern pop production systems with tight emotional control',
    why: 'He demonstrates that minimal setups can still yield global-quality records.',
    qualities: ['Product Taste', 'Craft Discipline', 'Operational Excellence'],
    url: 'https://en.wikipedia.org/wiki/Finneas_O%27Connell',
  },
  {
    id: 'pharrell-williams',
    name: 'Pharrell Williams',
    category: 'music-direction',
    role: 'Producer and creative entrepreneur',
    builds: 'Cross-industry creative brands spanning music, fashion, and media',
    why: 'He shows how creative direction can scale across multiple verticals.',
    qualities: ['Distribution Mastery', 'Creative Risk', 'Product Taste'],
    url: 'https://en.wikipedia.org/wiki/Pharrell_Williams',
  },
  {
    id: 'joel-zimmerman',
    name: 'Joel Zimmerman (deadmau5)',
    category: 'music-direction',
    role: 'Producer and live performance technologist',
    builds: 'Electronic production workflows and high-control live systems',
    why: 'He models technical autonomy in modern music production.',
    qualities: ['Systems Thinking', 'Craft Discipline', 'Creative Risk'],
    url: 'https://en.wikipedia.org/wiki/Deadmau5',
  },
  {
    id: 'andrew-huang',
    name: 'Andrew Huang',
    category: 'music-direction',
    role: 'Music creator and educator',
    builds: 'Music education content and experimental production formats',
    why: 'He is a strong model for teaching through creative output.',
    qualities: ['Public Teaching', 'Creative Risk', 'Distribution Mastery'],
    url: 'https://www.andrewhuang.com',
  },
  {
    id: 'quincy-jones',
    name: 'Quincy Jones',
    category: 'music-direction',
    role: 'Producer and arranger',
    builds: 'Genre-defining production systems and collaborative music direction',
    why: 'He represents elite orchestration of people, process, and sound.',
    qualities: ['Operational Excellence', 'Human-Centered Leadership', 'Product Taste'],
    url: 'https://en.wikipedia.org/wiki/Quincy_Jones',
  },
  {
    id: 'nile-rodgers',
    name: 'Nile Rodgers',
    category: 'music-direction',
    role: 'Producer, guitarist, and songwriter',
    builds: 'Timeless groove systems and high-impact collaborations',
    why: 'He demonstrates stylistic consistency across decades and genres.',
    qualities: ['Craft Discipline', 'Resilience', 'Product Taste'],
    url: 'https://en.wikipedia.org/wiki/Nile_Rodgers',
  },
  {
    id: 'herbie-hancock',
    name: 'Herbie Hancock',
    category: 'music-direction',
    role: 'Composer and pianist',
    builds: 'Jazz innovation systems blending tradition with technology',
    why: 'He models curiosity-driven evolution over a lifetime of work.',
    qualities: ['Long-Horizon Vision', 'Creative Risk', 'Craft Discipline'],
    url: 'https://en.wikipedia.org/wiki/Herbie_Hancock',
  },
  {
    id: 'ar-rahman',
    name: 'A. R. Rahman',
    category: 'music-direction',
    role: 'Composer and producer',
    builds: 'Global composition systems bridging cinematic and popular music',
    why: 'He combines cultural depth with production modernity at scale.',
    qualities: ['Product Taste', 'Creative Risk', 'Operational Excellence'],
    url: 'https://en.wikipedia.org/wiki/A._R._Rahman',
  },
  {
    id: 'suzanne-ciani',
    name: 'Suzanne Ciani',
    category: 'music-direction',
    role: 'Composer and electronic music pioneer',
    builds: 'Modular synthesis and sonic identity systems',
    why: 'She models technical experimentation as a lifelong creative engine.',
    qualities: ['Creative Risk', 'Craft Discipline', 'Resilience'],
    url: 'https://en.wikipedia.org/wiki/Suzanne_Ciani',
  },

  {
    id: 'jony-ive',
    name: 'Jony Ive',
    category: 'design-craft',
    role: 'Industrial designer',
    builds: 'Iconic hardware and interaction systems',
    why: 'He demonstrates how design taste can shape entire product categories.',
    qualities: ['Product Taste', 'Craft Discipline', 'Long-Horizon Vision'],
    url: 'https://en.wikipedia.org/wiki/Jony_Ive',
  },
  {
    id: 'dieter-rams',
    name: 'Dieter Rams',
    category: 'design-craft',
    role: 'Industrial design legend',
    builds: 'Principle-driven design systems focused on clarity and utility',
    why: 'He is a benchmark for principled minimalism that lasts decades.',
    qualities: ['First-Principles', 'Product Taste', 'Craft Discipline'],
    url: 'https://en.wikipedia.org/wiki/Dieter_Rams',
  },
  {
    id: 'don-norman',
    name: 'Don Norman',
    category: 'design-craft',
    role: 'Design theorist',
    builds: 'Human-centered design frameworks used across product teams',
    why: 'He grounds product design in cognitive reality and user outcomes.',
    qualities: ['Human-Centered Leadership', 'Systems Thinking', 'Public Teaching'],
    url: 'https://en.wikipedia.org/wiki/Don_Norman',
  },
  {
    id: 'susan-kare',
    name: 'Susan Kare',
    category: 'design-craft',
    role: 'Interface iconographer',
    builds: 'Visual language systems for modern computing interfaces',
    why: 'She proves that tiny details can define entire product experiences.',
    qualities: ['Craft Discipline', 'Product Taste', 'Human-Centered Leadership'],
    url: 'https://en.wikipedia.org/wiki/Susan_Kare',
  },
  {
    id: 'paula-scher',
    name: 'Paula Scher',
    category: 'design-craft',
    role: 'Graphic designer',
    builds: 'Brand identity systems for institutions and products',
    why: 'She combines expressive typography with strategic communication clarity.',
    qualities: ['Product Taste', 'Creative Risk', 'Craft Discipline'],
    url: 'https://en.wikipedia.org/wiki/Paula_Scher',
  },
  {
    id: 'john-maeda',
    name: 'John Maeda',
    category: 'design-craft',
    role: 'Designer and technologist',
    builds: 'Design-tech frameworks and creative leadership models',
    why: 'He bridges computational thinking with design literacy.',
    qualities: ['Systems Thinking', 'Public Teaching', 'Long-Horizon Vision'],
    url: 'https://maeda.pm',
  },
  {
    id: 'julie-zhuo',
    name: 'Julie Zhuo',
    category: 'design-craft',
    role: 'Product design leader',
    builds: 'Product design management systems and team playbooks',
    why: 'She translates design leadership into practical team execution.',
    qualities: ['Human-Centered Leadership', 'Operational Excellence', 'Public Teaching'],
    url: 'https://www.juliezhuo.com',
  },
  {
    id: 'ryan-singer',
    name: 'Ryan Singer',
    category: 'design-craft',
    role: 'Product strategy and design thinker',
    builds: 'Shaping and product cycle decision frameworks',
    why: 'He helps teams ship better by tightening problem-definition quality.',
    qualities: ['Systems Thinking', 'First-Principles', 'Operational Excellence'],
    url: 'https://basecamp.com/shapeup',
  },
  {
    id: 'rauno-freiberg',
    name: 'Rauno Freiberg',
    category: 'design-craft',
    role: 'Design engineer',
    builds: 'High-fidelity web interaction systems and visual polish standards',
    why: 'He models how frontend detail quality compounds brand trust.',
    qualities: ['Product Taste', 'Craft Discipline', 'Creative Risk'],
    url: 'https://rauno.me',
  },
  {
    id: 'paco-coursey',
    name: 'Paco Coursey',
    category: 'design-craft',
    role: 'Design engineer and toolmaker',
    builds: 'Interface primitives and minimal interaction patterns',
    why: 'He demonstrates precision and restraint in modern UI craft.',
    qualities: ['Craft Discipline', 'Product Taste', 'Open Source'],
    url: 'https://paco.me',
  },
  {
    id: 'tobias-van-schneider',
    name: 'Tobias van Schneider',
    category: 'design-craft',
    role: 'Designer and entrepreneur',
    builds: 'Design-led products and independent brand systems',
    why: 'He is a strong model for independent creative direction with business leverage.',
    qualities: ['Distribution Mastery', 'Product Taste', 'Resilience'],
    url: 'https://vanschneider.com',
  },
  {
    id: 'refik-anadol',
    name: 'Refik Anadol',
    category: 'design-craft',
    role: 'Media artist',
    builds: 'AI-native visual systems and data-driven immersive art',
    why: 'He shows how machine intelligence can become a creative medium, not just a tool.',
    qualities: ['Creative Risk', 'Long-Horizon Vision', 'Product Taste'],
    url: 'https://refikanadol.com',
  },
  {
    id: 'bret-victor',
    name: 'Bret Victor',
    category: 'design-craft',
    role: 'Interface thinker and inventor',
    builds: 'Dynamic medium concepts for thinking and interaction design',
    why: 'He pushes you to design tools that amplify thought, not just output.',
    qualities: ['First-Principles', 'Creative Risk', 'Systems Thinking'],
    url: 'http://worrydream.com',
  },
  {
    id: 'jessica-walsh',
    name: 'Jessica Walsh',
    category: 'design-craft',
    role: 'Designer and creative director',
    builds: 'High-impact brand systems and visual storytelling products',
    why: 'She demonstrates expressive design with clear strategic intent.',
    qualities: ['Creative Risk', 'Product Taste', 'Distribution Mastery'],
    url: 'https://www.jessicawalsh.com',
  },
  {
    id: 'khoi-vinh',
    name: 'Khoi Vinh',
    category: 'design-craft',
    role: 'Designer and writer',
    builds: 'Design strategy frameworks for digital product organizations',
    why: 'He offers a systems-level lens on design decisions and org shape.',
    qualities: ['Systems Thinking', 'Public Teaching', 'Product Taste'],
    url: 'https://www.subtraction.com',
  },

  {
    id: 'peter-drucker',
    name: 'Peter Drucker',
    category: 'long-game-thinking',
    role: 'Management thinker',
    builds: 'Modern management principles and execution doctrine',
    why: 'He sharpens priorities, systems, and decision ownership.',
    qualities: ['Systems Thinking', 'First-Principles', 'Long-Horizon Vision'],
    url: 'https://en.wikipedia.org/wiki/Peter_Drucker',
  },
  {
    id: 'charlie-munger',
    name: 'Charlie Munger',
    category: 'long-game-thinking',
    role: 'Investor and mental model strategist',
    builds: 'Multi-disciplinary decision frameworks for compounding outcomes',
    why: 'He is a template for rational judgment under long time horizons.',
    qualities: ['First-Principles', 'Long-Horizon Vision', 'Resilience'],
    url: 'https://en.wikipedia.org/wiki/Charlie_Munger',
  },
  {
    id: 'warren-buffett',
    name: 'Warren Buffett',
    category: 'long-game-thinking',
    role: 'Investor and capital allocator',
    builds: 'Compounding systems through disciplined allocation and patience',
    why: 'He exemplifies consistency, process, and long-cycle conviction.',
    qualities: ['Long-Horizon Vision', 'Operational Excellence', 'Resilience'],
    url: 'https://en.wikipedia.org/wiki/Warren_Buffett',
  },
  {
    id: 'nassim-taleb',
    name: 'Nassim Nicholas Taleb',
    category: 'long-game-thinking',
    role: 'Risk thinker and author',
    builds: 'Decision frameworks for uncertainty, antifragility, and tail risk',
    why: 'He improves how you design systems that survive volatility.',
    qualities: ['First-Principles', 'Resilience', 'Systems Thinking'],
    url: 'https://en.wikipedia.org/wiki/Nassim_Nicholas_Taleb',
  },
  {
    id: 'james-clear',
    name: 'James Clear',
    category: 'long-game-thinking',
    role: 'Behavior and habit author',
    builds: 'Habit systems for repeatable long-term performance',
    why: 'He turns motivation into architecture and measurable behavior.',
    qualities: ['Systems Thinking', 'Public Teaching', 'Craft Discipline'],
    url: 'https://jamesclear.com',
  },
  {
    id: 'cal-newport',
    name: 'Cal Newport',
    category: 'long-game-thinking',
    role: 'Author and computer science professor',
    builds: 'Focus and deep work systems for knowledge workers',
    why: 'He protects attention quality in high-noise environments.',
    qualities: ['Craft Discipline', 'First-Principles', 'Public Teaching'],
    url: 'https://calnewport.com',
  },
  {
    id: 'ryan-holiday',
    name: 'Ryan Holiday',
    category: 'long-game-thinking',
    role: 'Author and strategist',
    builds: 'Stoic operating systems for discipline and emotional control',
    why: 'He gives practical resilience frameworks for long creative seasons.',
    qualities: ['Resilience', 'Public Teaching', 'Long-Horizon Vision'],
    url: 'https://ryanholiday.net',
  },
  {
    id: 'carol-dweck',
    name: 'Carol Dweck',
    category: 'long-game-thinking',
    role: 'Psychology researcher',
    builds: 'Growth mindset frameworks for learning and adaptation',
    why: 'She strengthens the mental model required for compounding skill.',
    qualities: ['Human-Centered Leadership', 'Public Teaching', 'Resilience'],
    url: 'https://en.wikipedia.org/wiki/Carol_Dweck',
  },
  {
    id: 'angela-duckworth',
    name: 'Angela Duckworth',
    category: 'long-game-thinking',
    role: 'Psychology researcher and author',
    builds: 'Grit and sustained effort frameworks',
    why: 'She reinforces that consistency outruns short-term intensity.',
    qualities: ['Resilience', 'Public Teaching', 'Long-Horizon Vision'],
    url: 'https://en.wikipedia.org/wiki/Angela_Duckworth',
  },
  {
    id: 'bj-fogg',
    name: 'B. J. Fogg',
    category: 'long-game-thinking',
    role: 'Behavior design researcher',
    builds: 'Tiny behavior systems for lasting change',
    why: 'He offers implementation-level behavior engineering.',
    qualities: ['Systems Thinking', 'Public Teaching', 'Human-Centered Leadership'],
    url: 'https://www.bjfogg.com',
  },
  {
    id: 'mihaly-csikszentmihalyi',
    name: 'Mihaly Csikszentmihalyi',
    category: 'long-game-thinking',
    role: 'Psychologist and flow researcher',
    builds: 'Flow state frameworks for optimal creative performance',
    why: 'He provides the science behind sustained creative immersion.',
    qualities: ['First-Principles', 'Public Teaching', 'Human-Centered Leadership'],
    url: 'https://en.wikipedia.org/wiki/Mihaly_Csikszentmihalyi',
  },
  {
    id: 'daniel-kahneman',
    name: 'Daniel Kahneman',
    category: 'long-game-thinking',
    role: 'Psychologist and Nobel laureate',
    builds: 'Cognitive bias and decision quality frameworks',
    why: 'He improves strategic judgment by revealing predictable thinking errors.',
    qualities: ['First-Principles', 'Public Teaching', 'Systems Thinking'],
    url: 'https://en.wikipedia.org/wiki/Daniel_Kahneman',
  },
  {
    id: 'annie-duke',
    name: 'Annie Duke',
    category: 'long-game-thinking',
    role: 'Decision strategist and author',
    builds: 'Probabilistic decision systems under uncertainty',
    why: 'She sharpens how to separate decision quality from outcomes.',
    qualities: ['First-Principles', 'Resilience', 'Public Teaching'],
    url: 'https://www.annieduke.com',
  },
  {
    id: 'ray-dalio',
    name: 'Ray Dalio',
    category: 'long-game-thinking',
    role: 'Investor and systems thinker',
    builds: 'Principles-based operating systems for organizations',
    why: 'He demonstrates codified principles as a scaling mechanism.',
    qualities: ['Systems Thinking', 'Operational Excellence', 'Long-Horizon Vision'],
    url: 'https://www.principles.com',
  },
  {
    id: 'adam-grant',
    name: 'Adam Grant',
    category: 'long-game-thinking',
    role: 'Organizational psychologist',
    builds: 'Evidence-based frameworks for work, motivation, and collaboration',
    why: 'He helps align high performance with healthier team cultures.',
    qualities: ['Human-Centered Leadership', 'Public Teaching', 'Systems Thinking'],
    url: 'https://adamgrant.net',
  },
]

export const topVisionaries = [...visionaries]
  .filter((person) => person.top10Rank)
  .sort((a, b) => (a.top10Rank ?? 999) - (b.top10Rank ?? 999))

export function getVisionaryBySlug(slug: string): VisionaryPerson | undefined {
  return visionaries.find(v => v.slug === slug)
}

export function getRelatedVisionaries(person: VisionaryPerson): VisionaryPerson[] {
  return visionaries
    .filter(v => v.id !== person.id && v.category === person.category)
    .slice(0, 4)
}

export function getEnrichedVisionaries(): VisionaryPerson[] {
  return visionaries.filter(v => v.slug)
}

export const qualityLegend: VisionaryQualityTag[] = [
  'Systems Thinking',
  'First-Principles',
  'Product Taste',
  'Craft Discipline',
  'Public Teaching',
  'Open Source',
  'Long-Horizon Vision',
  'Creative Risk',
  'Operational Excellence',
  'Distribution Mastery',
  'Human-Centered Leadership',
  'Resilience',
]
