#!/usr/bin/env node
// Affiliate monetization audit — connects the affiliate catalog to the actual content.
//
// The question: "Which blog posts mention tools that PAY, but carry no affiliate link —
// and which of those should I monetize first (by traffic)?"
//
// Joins three sources:
//   data/affiliate/programs.json      — the program catalog (which tools pay, ourLink)
//   content/blog/*.mdx                — what each post actually mentions
//   docs/ops/analytics/traffic-latest — visitors per post (to rank the gaps)
//
// Output: ranked "join these programs first" + "add links to these posts first".
//
// Usage:
//   node scripts/affiliate-audit.mjs            # print report
//   node scripts/affiliate-audit.mjs --write    # also write docs/ops/affiliate/AUDIT.md

import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const BLOG_DIR = join(ROOT, 'content', 'blog')
const CATALOG = join(ROOT, 'data', 'affiliate', 'programs.json')
const TRAFFIC = join(ROOT, 'docs', 'ops', 'analytics', 'traffic-latest.json')
const OUT_DIR = join(ROOT, 'docs', 'ops', 'affiliate')
const OUT = join(OUT_DIR, 'AUDIT.md')

const doWrite = process.argv.includes('--write')

const catalog = JSON.parse(readFileSync(CATALOG, 'utf8'))
const programs = catalog.programs
const visitorsByPath = existsSync(TRAFFIC)
  ? new Map((JSON.parse(readFileSync(TRAFFIC, 'utf8')).pages || []).map((p) => [p.path.replace(/\/$/, ''), p.visitors]))
  : new Map()

// Build an alias → program lookup. Match on word-boundary, case-insensitive.
const aliasHits = programs.map((p) => ({
  program: p,
  rx: new RegExp(`\\b(${(p.aliases || [p.tool]).map((a) => a.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|')})\\b`, 'i'),
}))

const rows = []
for (const file of readdirSync(BLOG_DIR)) {
  if (!file.endsWith('.mdx')) continue
  const slug = file.replace(/\.mdx$/, '')
  const body = readFileSync(join(BLOG_DIR, file), 'utf8')
  const path = `/blog/${slug}`
  const visitors = visitorsByPath.get(path) || 0

  const payers = []   // mentioned tools that HAVE a program
  const deadends = [] // mentioned tools with NO program (traffic we can't monetize directly)
  for (const { program, rx } of aliasHits) {
    if (!rx.test(body)) continue
    if (program.hasProgram) payers.push(program)
    else deadends.push(program.tool)
  }
  if (!payers.length && !deadends.length) continue

  const hasAnyLink = payers.some((p) => p.ourLink)
  const monetizableNoLink = payers.filter((p) => p.status === 'active' && !p.ourLink)
  rows.push({ slug, path, visitors, payers, deadends, hasAnyLink, monetizableNoLink })
}

// ── Ranked: which PROGRAMS to join first (priority × total traffic of posts that mention them) ──
const programScore = new Map()
for (const r of rows) {
  for (const p of r.payers) {
    if (p.status !== 'active' || p.ourLink) continue
    const cur = programScore.get(p.tool) || { program: p, traffic: 0, posts: 0 }
    cur.traffic += r.visitors
    cur.posts += 1
    programScore.set(p.tool, cur)
  }
}
const joinFirst = [...programScore.values()].sort(
  (a, b) => a.program.priority - b.program.priority || b.traffic - a.traffic
)

// ── Ranked: which POSTS to add links to first (by traffic, among those mentioning a payer) ──
const addLinks = rows
  .filter((r) => r.monetizableNoLink.length)
  .sort((a, b) => b.visitors - a.visitors)

const fmtPosts = addLinks
  .map((r, i) => `| ${i + 1} | \`${r.slug}\` | ${r.visitors || '—'} | ${r.monetizableNoLink.map((p) => p.tool).join(', ')} |`)
  .join('\n')

const fmtJoin = joinFirst
  .map((j, i) => `| ${i + 1} | ${j.program.tool} | ${j.program.commission} | ${j.program.recurring || '—'} | ${j.traffic} | ${j.posts} | ${j.program.signupUrl} |`)
  .join('\n')

const md = `# Affiliate Monetization Audit

_Generated by \`scripts/affiliate-audit.mjs\` from \`data/affiliate/programs.json\` + \`traffic-latest.json\`. Re-run after signing up for a program (set its \`ourLink\`) or after the weekly traffic paste._

## 1. Join these programs first

Ranked by program priority, then by the total traffic of the posts that already mention the tool. Sign up → set \`ourLink\` in \`programs.json\` → re-run.

| # | Program | Commission | Recurring | Traffic of mentioning posts | # posts | Signup |
|---|---------|-----------|-----------|------------------------------|---------|--------|
${fmtJoin || '| — | (all mentioned programs already have ourLink) | | | | | |'}

## 2. Add affiliate links to these posts first

Posts that mention an active payer but carry no link yet, ranked by traffic.

| # | Post | Visitors | Monetizable mentions (no link yet) |
|---|------|----------|-------------------------------------|
${fmtPosts || '| — | (no gaps) | | |'}

## 3. The honest reality

Frontier names drive the traffic but **don't pay** (OpenAI, Anthropic, Google, Runway, Luma, Midjourney = no programs). The play: keep ranking for those big names, but place affiliate links on the **adjacent recurring payers** the post naturally mentions. Lead with Higgsfield (you use it), then the recurring spine (Systeme.io / CapCut / ElevenLabs / Copy.ai).

> Disclosure to add near any affiliate link: _"${catalog.disclosure}"_
`

console.log(md)
if (doWrite) {
  if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true })
  writeFileSync(OUT, md)
  console.log(`\n[affiliate-audit] wrote ${OUT}`)
}
