#!/usr/bin/env node
// Weekly analytics-learning journal generator.
// Auto-fills the "Shipped this week" half from production-repo git history.
// Traffic numbers are pasted by the operator from the Vercel Analytics tab —
// Vercel gates page-view aggregates behind a token + plan, so there is no silent pull.
//
// Usage:
//   node scripts/analytics-journal.mjs                 # current ISO week
//   node scripts/analytics-journal.mjs --week=2026-W23 # a specific week
//   node scripts/analytics-journal.mjs --force         # overwrite existing file

import { execSync } from 'node:child_process'
import { writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const OUT_DIR = join(ROOT, 'docs', 'ops', 'analytics')
// The site whose traffic we learn from. Shipping happens in the production repo.
const PROD_REPO = process.env.FRANKX_PROD_REPO || join(ROOT, '..', 'frankx.ai-vercel-website')

const args = process.argv.slice(2)
const force = args.includes('--force')
const weekArg = args.find((a) => a.startsWith('--week='))?.split('=')[1]

function isoWeek(d) {
  const date = new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()))
  const day = date.getUTCDay() || 7
  date.setUTCDate(date.getUTCDate() + 4 - day)
  const yearStart = new Date(Date.UTC(date.getUTCFullYear(), 0, 1))
  const week = Math.ceil(((date - yearStart) / 86400000 + 1) / 7)
  return { year: date.getUTCFullYear(), week }
}

// Monday 00:00 → Sunday 23:59 for a given ISO year-week.
function weekRange(year, week) {
  const jan4 = new Date(Date.UTC(year, 0, 4))
  const jan4Day = jan4.getUTCDay() || 7
  const week1Mon = new Date(jan4)
  week1Mon.setUTCDate(jan4.getUTCDate() - jan4Day + 1)
  const start = new Date(week1Mon)
  start.setUTCDate(week1Mon.getUTCDate() + (week - 1) * 7)
  const end = new Date(start)
  end.setUTCDate(start.getUTCDate() + 7)
  const iso = (x) => x.toISOString().slice(0, 10)
  return { since: iso(start), until: iso(end) }
}

let year, week
if (weekArg) {
  const m = weekArg.match(/^(\d{4})-W(\d{1,2})$/)
  if (!m) {
    console.error(`Bad --week value "${weekArg}". Expected YYYY-Www, e.g. 2026-W23.`)
    process.exit(1)
  }
  year = Number(m[1])
  week = Number(m[2])
} else {
  ;({ year, week } = isoWeek(new Date()))
}
const tag = `${year}-W${String(week).padStart(2, '0')}`
const { since, until } = weekRange(year, week)

function gitLog() {
  if (!existsSync(PROD_REPO)) {
    return { error: `Production repo not found at ${PROD_REPO}. Set FRANKX_PROD_REPO.` }
  }
  try {
    const raw = execSync(
      `git -C "${PROD_REPO}" log main --since="${since}" --until="${until}" --pretty=%s`,
      { encoding: 'utf8' }
    )
    return { subjects: raw.split('\n').map((s) => s.trim()).filter(Boolean) }
  } catch (e) {
    return { error: `git log failed: ${e.message}` }
  }
}

// Pull every "/route" token out of the commit subjects → which surfaces moved.
function routesTouched(subjects) {
  const seen = new Map()
  for (const s of subjects) {
    for (const m of s.matchAll(/\/[a-z0-9][a-z0-9-]*(?:\/[a-z0-9-]+)*/g)) {
      const r = m[0].replace(/[.,)]+$/, '')
      if (r.length < 3) continue
      seen.set(r, (seen.get(r) || 0) + 1)
    }
  }
  return [...seen.entries()].sort((a, b) => b[1] - a[1]).map(([r, n]) => `${r} (${n})`)
}

const { subjects = [], error } = gitLog()
const routes = routesTouched(subjects)

const shipped = error
  ? `> ⚠ ${error}\n> Fill this section in manually from \`git -C <prod-repo> log\`.`
  : subjects.length
    ? subjects.map((s) => `- ${s}`).join('\n')
    : '- (no commits on main this week)'

const routeBlock = routes.length
  ? routes.map((r) => `- ${r}`).join('\n')
  : '- (no route tokens detected in commit subjects)'

const body = `# Analytics Journal — ${tag}

_Range: ${since} → ${until} (Mon–Sun, UTC). Site: frankx.ai. Generated by \`scripts/analytics-journal.mjs\`._

---

## 1. Shipped this week  ·  _auto-filled from git_

**Surfaces touched (by commit frequency):**
${routeBlock}

<details><summary>All ${subjects.length} commits on main</summary>

${shipped}

</details>

---

## 2. Traffic  ·  _paste from Vercel → Analytics tab_

> Open the Vercel dashboard → \`frankx-ai-vercel-website\` → **Analytics**. Set range to this week.
> Copy/paste the numbers below. (No API token on file, so this is a manual 30-second step.)

**Totals:** visitors __ · page views __ · bounce __% · (vs last week: __)

**Top pages (path — views):**
| # | Path | Views | Notes |
|---|------|-------|-------|
| 1 |  |  |  |
| 2 |  |  |  |
| 3 |  |  |  |
| 4 |  |  |  |
| 5 |  |  |  |

**Top referrers (source — visits):**
| Source | Visits |
|--------|--------|
|  |  |

**Speed Insights:** LCP __ · CLS __ · INP __ (real-user, this week)

---

## 3. What got traffic & why  ·  _analysis_

_Filled after the paste. Correlate §1 (what we shipped) ↔ §2 (what moved)._

- **Winners:**
- **Surprises:**
- **Dead weight** (shipped but no traffic):
- **Traffic with no recent work** (evergreen — protect it):

---

## 4. Predictions to validate next week

_Pre-register hypotheses now; check them against next week's paste. This is the learning edge._

- [ ]

---

## 5. Refine next week  ·  _actions_

- [ ]
`

if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true })
const outFile = join(OUT_DIR, `WEEK-${tag}.md`)
if (existsSync(outFile) && !force) {
  console.error(`${outFile} already exists. Re-run with --force to overwrite.`)
  process.exit(1)
}
writeFileSync(outFile, body)
console.log(`Wrote ${outFile}`)
console.log(`  ${subjects.length} commits, ${routes.length} surfaces touched.`)
if (error) console.log(`  NOTE: ${error}`)
