#!/usr/bin/env node
/**
 * Tier-1 smoke fixture scaffolder.
 *
 * Generates tests/fixtures/<name>/smoke.mjs for agents that lack one. The
 * generated fixture is a CONTRACT smoke, not a tautology of the audit:
 *   - parses the agent file with a REAL YAML parser (js-yaml) — standing
 *     canary for drift between Claude Code's parser and the audit's
 *     line-based parser
 *   - asserts the frontmatter contract (name/dir match, valid model,
 *     description ≥50 chars with a trigger cue, declared tools referenced)
 *   - memory round-trip via the in-memory driver
 *   - emits TODO(domain-assert) stubs the rewriting subagent must resolve
 *
 * Usage:
 *   node scripts/agents/scaffold-smoke.mjs --check          # list missing / TODO-unresolved
 *   node scripts/agents/scaffold-smoke.mjs --write          # generate missing fixtures
 *   node scripts/agents/scaffold-smoke.mjs --write <name>   # one agent
 */

import { readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..', '..')
const AGENTS_DIR = path.join(ROOT, '.claude', 'agents')
const FIXTURES_DIR = path.join(ROOT, 'tests', 'fixtures')
const SKIP_FILES = new Set(['CLAUDE.md', 'README.md', 'PRODUCT_TEAMS.md'])

const write = process.argv.includes('--write')
const filterAgent = process.argv.slice(2).find((a) => !a.startsWith('--'))

function discoverAgents() {
  return readdirSync(AGENTS_DIR, { withFileTypes: true })
    .filter((e) => e.isFile() && e.name.endsWith('.md') && !SKIP_FILES.has(e.name))
    .map((e) => path.basename(e.name, '.md'))
    .filter((n) => !filterAgent || n === filterAgent)
    .sort()
}

const TEMPLATE = (name) => `#!/usr/bin/env node
/**
 * Tier-1 contract smoke for ${name}.
 * Generated by scripts/agents/scaffold-smoke.mjs — domain asserts filled per-agent.
 * Run: node tests/fixtures/${name}/smoke.mjs
 */

process.env.ACOS_MEMORY_DRIVER = 'in-memory'
process.env.ACOS_MEMORY_QUIET = '1'
delete process.env.ACOS_MEMORY_INMEM_SNAPSHOT

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import yaml from 'js-yaml'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..', '..', '..')
const AGENT_FILE = path.join(ROOT, '.claude', 'agents', '${name}.md')

function fail(msg) {
  console.error(\`FAIL: \${msg}\`)
  process.exit(1)
}

// --- 1. Frontmatter contract (real YAML parse = parser-drift canary) ---
const raw = fs.readFileSync(AGENT_FILE, 'utf-8')
const fmMatch = raw.match(/^---\\r?\\n([\\s\\S]*?)\\r?\\n---/)
if (!fmMatch) fail('no frontmatter block')
let fm
try {
  fm = yaml.load(fmMatch[1])
} catch (e) {
  fail(\`frontmatter is not valid YAML: \${e.message}\`)
}
const body = raw.slice(fmMatch[0].length)

if (fm.name !== '${name}') fail(\`frontmatter name '\${fm.name}' != fixture dir '${name}'\`)
if (!['haiku', 'sonnet', 'opus'].includes(fm.model)) fail(\`invalid model: \${fm.model}\`)
if (!fm.description || fm.description.length < 50) fail('description missing or < 50 chars')
const triggerRe = /(auto[- ]?invoke|auto[- ]?fire|use when|trigger|\\bsays\\b|when frank|\\/[a-z-]+\\b)/i
if (!triggerRe.test(fm.description)) fail('description has no trigger language')

// tools: accept comma-string or YAML list (Claude Code accepts both)
const tools = Array.isArray(fm.tools)
  ? fm.tools
  : String(fm.tools || '').split(',').map((t) => t.trim()).filter(Boolean)
if (tools.length === 0) fail('no tools declared')
for (const tool of tools) {
  const re = new RegExp(\`\\\\b\${tool.replace(/[.*+?^\${}()|[\\]\\\\]/g, '\\\\$&')}\\\\b\`)
  if (!re.test(body)) fail(\`declared tool '\${tool}' never referenced in body\`)
}

// --- 2. Memory round-trip (in-memory driver, no side effects) ---
const { recall, remember, close } = await import('../../../lib/acos/memory.mjs')
try {
  const id = await remember({
    agent: '${name}',
    intent: 'smoke contract check for ${name}',
    approach: 'tier-1 generated fixture: frontmatter + tools + memory round-trip',
    score: 1.0,
    tags: ['smoke', '${name}'],
  })
  if (typeof id !== 'number') fail(\`remember did not return numeric id, got \${id}\`)
  const recalled = await recall('smoke contract ${name}', 3)
  if (recalled.length === 0) fail('persisted smoke entry not recallable')
  if ((recalled[0].similarity ?? 0) < 0.25) fail(\`recall similarity \${recalled[0].similarity} < 0.25\`)
} finally {
  await close().catch(() => {})
}

// --- 3. Domain asserts (agent-specific invariants — resolve before shipping) ---
// TODO(domain-assert): assert 1-3 invariants specific to ${name}'s contract,
// e.g. a file path the agent reads exists, a threshold value appears in body,
// a dispatch target agent file exists. Filled by the rewrite subagent.

console.log('PASS: ${name} tier-1 smoke green (frontmatter contract + tools referenced + memory round-trip)')
process.exit(0)
`

const agents = discoverAgents()
const missing = []
const unresolvedTodo = []

for (const name of agents) {
  const fixturePath = path.join(FIXTURES_DIR, name, 'smoke.mjs')
  if (!existsSync(fixturePath)) {
    missing.push(name)
    if (write) {
      mkdirSync(path.dirname(fixturePath), { recursive: true })
      writeFileSync(fixturePath, TEMPLATE(name))
      console.log(`WRITE  tests/fixtures/${name}/smoke.mjs`)
    }
  } else if (readFileSync(fixturePath, 'utf-8').includes('TODO(domain-assert)')) {
    unresolvedTodo.push(name)
  }
}

console.log(`\n${agents.length} agents · ${missing.length} ${write ? 'fixtures generated' : 'missing fixtures'} · ${unresolvedTodo.length} with unresolved TODO(domain-assert)`)
if (!write && missing.length > 0) {
  console.log(`\nMissing:`)
  for (const n of missing) console.log(`  ${n}`)
  console.log(`\nRun with --write to generate.`)
}
if (unresolvedTodo.length > 0) {
  console.log(`\nUnresolved domain asserts (not ship-ready):`)
  for (const n of unresolvedTodo) console.log(`  ${n}`)
}
